import {mkdir,writeFile,copyFile,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {siteHeader,siteSidebar,siteMobileNav} from '../src/site-shell.mjs';
import {courseUnits} from '../src/course.mjs';
import {edition} from './content/lessons.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name='Algebra_2_Units_1_10_Complete_Course';
const zipTable=Array.from({length:256},(_,i)=>{let n=i;for(let b=0;b<8;b++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(buffer){let c=0xffffffff;for(const b of buffer)c=zipTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
async function zipFiles(entries,target){let offset=0;const local=[],central=[];for(const {name,data}of entries){const path=Buffer.from(name),checksum=crc(data),header=Buffer.alloc(30);header.writeUInt32LE(0x04034b50);header.writeUInt16LE(20,4);header.writeUInt16LE(0x800,6);header.writeUInt16LE(33,12);header.writeUInt32LE(checksum,14);header.writeUInt32LE(data.length,18);header.writeUInt32LE(data.length,22);header.writeUInt16LE(path.length,26);local.push(header,path,data);const c=Buffer.alloc(46);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(33,14);c.writeUInt32LE(checksum,16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(data.length,24);c.writeUInt16LE(path.length,28);c.writeUInt32LE(offset,42);central.push(c,path);offset+=header.length+path.length+data.length;}
 const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);await writeFile(target,Buffer.concat([...local,directory,end]));}
const title=q=>`Q${q.difficulty} — ${q.difficultyLabel}`;
function questionMarkdown(q){return `### ${title(q)}\n\n${q.prompt}\n\n${q.isGraph?`![Four graph choices for ${q.lessonId} Q${q.difficulty}, arranged A/B above C/D](images/${q.questionId}-choices.svg)\n\n**Choose A, B, C, or D.**`:`#### Multiple Choice\n\n${q.choices.map(c=>`- **${c.letter}.** ${c.text}`).join('\n')}\n\n#### Written Response\n\nAnswer (${q.fields.map(f=>f.label).join('; ')}):\n\n____________________\n\nWork:\n\n____________________\n\n____________________`}\n`;}
function questionHtml(q){return `<article class="panel question-card workbook-question" id="${q.questionId}"><header class="workbook-header"><div class="question-topline"><h3 class="section-title">${q.lessonId} · Q${q.difficulty}</h3><span class="difficulty-tag" data-level="${q.difficulty}">${title(q)}</span></div></header><div class="question-content">${q.promptHtml}</div><section class="answer-section"><h4 class="section-title">Multiple Choice</h4><div class="choice-grid ${q.isGraph?'graph-choices':''}">${q.choices.map(c=>`<div class="answer-choice"><span class="choice-letter">${c.letter}</span><div class="choice-content">${q.isGraph?`<img src="${c.image}" alt="Graph ${c.letter}: ${esc(c.description)}" width="370" height="370" loading="lazy">`:c.html}</div></div>`).join('')}</div>${q.isGraph?`<a class="text-button graph-enlarge" target="_blank" rel="noopener" href="/practice/graphs/${q.questionId}-choices.svg">Enlarge all four graphs ↗</a>`:''}</section>${q.isGraph?'':`<section class="answer-section written-space"><h4 class="section-title">Written Response</h4><p>Answer: <span>${q.fields.map(f=>esc(f.label)).join(' · ')}</span></p><div class="work-line"></div><p>Work:</p><div class="work-line"></div><div class="work-line"></div></section>`}<p class="one-question-note">One question · One grade · One adaptive weight</p></article>`;}
function shell(title,content){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#172c42"><title>${esc(title)} · Fieldnotes</title><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/practice/katex.min.css"><link rel="stylesheet" href="/practice/styles.css"><link rel="stylesheet" href="/assets/site.css"></head><body><a class="skip-link" href="#main">Skip to workbook</a>${siteHeader('practice')}<div class="site-frame">${siteSidebar('practice')}<main class="site-main main workbook-main" id="main">${content}</main></div>${siteMobileNav('practice')}</body></html>`;}
function lessonMarkdown(l){return `## Lesson explanation\n\n${l.explanation}\n\n## Key formulas and rules\n\n${l.rule}\n\n## Worked examples\n\n${l.examples.map((e,i)=>`### Example ${i+1} — ${e.title}\n\n${e.prompt}\n\n**Work:** ${e.work}\n\n${e.explanation}`).join('\n\n')}\n\n## Common mistakes\n\n${l.mistakes.map(m=>'- '+m).join('\n')}\n\n${l.extensions?.length?`## Source-aligned labs and extensions\n\n${l.extensions.map(e=>`### ${e.title}\n\n[Original textbook activity](https://fieldnotes-mathematics-ebook.netlify.app${e.ebookUrl})\n\n${e.prompt}\n\n${e.work}`).join('\n\n')}\n\n`:''}## Lesson summary\n\n${l.recap}\n\n${l.connection}\n\n`;}
function teachingHtml(l,render){return `<section class="panel lesson-teaching" id="explanation"><h2>Understand the lesson</h2><div class="question-content">${render(l.explanation)}</div><h3>Key formulas and rules</h3><div class="question-content">${render(l.rule)}</div></section><section class="panel lesson-teaching" id="examples"><h2>Worked examples</h2>${l.examples.map((e,i)=>`<article class="worked-example"><p class="eyebrow">Example ${i+1}</p><h3>${esc(e.title)}</h3><div class="question-content">${render(e.prompt)}<div class="example-work">${render(e.work)}</div>${render(e.explanation)}</div></article>`).join('')}</section><section class="panel lesson-teaching"><h2>Common mistakes</h2><ul>${l.mistakes.map(m=>`<li>${esc(m)}</li>`).join('')}</ul></section>${l.extensions?.length?`<section class="panel lesson-teaching" id="extensions"><h2>Labs and extensions</h2>${l.extensions.map(e=>`<article class="worked-example"><h3>${esc(e.title)}</h3><div class="question-content">${render(e.prompt)}<div class="example-work">${render(e.work)}</div></div><a class="text-button" href="${e.ebookUrl}">Original textbook activity · page ${e.ebookPage} →</a></article>`).join('')}</section>`:''}<section class="panel lesson-teaching"><h2>Lesson summary</h2><div class="question-content">${render(l.recap)}${render(l.connection)}</div></section>`;}
export async function buildWorkbook(questions,lessons,root,render){
 const dist=join(root,'../dist'),folder=join(root,'../artifacts',name);await mkdir(join(folder,'images'),{recursive:true});await mkdir(join(dist,'downloads'),{recursive:true});await mkdir(join(dist,'workbook'),{recursive:true});
 let md=`# Algebra 2 — Complete Unit 1–10 Course\n\n**${edition.title} · ${edition.publisher}, ${edition.year} · ISBN ${edition.isbn}**\n\n[Publisher edition reference](${edition.publisherUrl})\n\nLesson guides, worked examples, and original practice follow every numbered lesson in the supplied course. All original textbook photographs, including reviews and assessments, remain in the website’s reader.\n\n## Using this course\n\n${lessons.length} lessons · ${questions.length} questions · Q1 Standard, Q2 Hard, Q3 Hard–Challenge, Q4 Challenge, Q5 Hardest.\n\nNon-graph questions offer Multiple Choice and Written Response for the same question. Graph questions have four graph choices only. In Both mode, both answers must be correct; the question still receives one result and one weight. Work is retained for review without separate grading. Student selections remain hard constraints. The existing weighting, cooldown, spaced review, and mastery behavior are unchanged.\n\n## Contents\n\n${courseUnits.map(u=>`### Unit ${u.id} — ${u.title}\n\n${lessons.filter(l=>l.chapter===u.id).map(l=>`- [${l.id} ${l.name}](https://fieldnotes-mathematics-ebook.netlify.app${l.url})`).join('\n')}`).join('\n\n')}\n\n`;
 const assets=[];
 for(const [index,l] of lessons.entries()){
  const qs=questions.filter(q=>q.lessonId===l.id),prev=lessons[index-1],next=lessons[index+1];
  md+=`---\n\n# ${l.id} ${l.name}\n\n${l.summary}\n\n[Original textbook lesson](https://fieldnotes-mathematics-ebook.netlify.app${l.ebookUrl})\n\n${lessonMarkdown(l)}## Practice questions\n\n${qs.map(questionMarkdown).join('\n')}\n## Answers and complete solutions\n\n${qs.map(q=>`### Q${q.difficulty}\n\n${q.explanation}\n`).join('\n')}\n`;
  const nav=`<nav class="lesson-navigation" aria-label="Lesson navigation">${prev?`<a class="button secondary" rel="prev" href="${prev.url}">← ${prev.id} ${esc(prev.name)}</a>`:'<span></span>'}${next?`<a class="button secondary" rel="next" href="${next.url}">${next.id} ${esc(next.name)} →</a>`:'<a class="button secondary" href="/workbook">Course contents →</a>'}</nav>`;
  const page=`<div class="page-heading"><div><p class="eyebrow">Unit ${l.chapter} · Lesson ${l.id}</p><h1>${l.id} ${esc(l.name)}</h1><p>${esc(l.summary)}</p></div><a class="button secondary" href="/workbook">All lessons</a></div><div class="panel workbook-intro"><nav class="lesson-shortcuts" aria-label="On this page"><a href="#explanation">Explanation</a><a href="#examples">Worked examples</a><a href="#practice">Practice</a><a href="#solutions">Solutions</a></nav><div class="workbook-actions"><a class="button" href="/practice/setup">Set up adaptive practice</a><a class="button secondary" href="${l.ebookUrl}">Original textbook · p.${l.ebookPage}</a></div></div>${teachingHtml(l,render)}<h2 class="workbook-section-title" id="practice">Practice questions</h2><p>Five questions · Standard to Hardest</p>${qs.map(questionHtml).join('')}<section class="panel workbook-solutions" id="solutions"><h2>Answers and complete solutions</h2><p>Finish the questions, then open a solution to review your work.</p>${qs.map(q=>`<details id="solution-${q.questionId}"><summary>${title(q)}</summary><div class="question-content">${q.explanationHtml}</div></details>`).join('')}</section>${nav}`;
  await writeFile(join(dist,'workbook',`${l.id}.html`),shell(`${l.id} ${l.name}`,page));
 }
 for(const q of questions.filter(q=>q.isGraph)){const filename=`${q.questionId}-choices.svg`,source=join(dist,'practice/graphs',filename);await copyFile(source,join(folder,'images',filename));assets.push({name:`${name}/images/${filename}`,data:await readFile(source)});}
 await writeFile(join(folder,name+'.md'),md);await writeFile(join(dist,'downloads',name+'.md'),md);
 await mkdir(join(dist,'downloads/images'),{recursive:true});for(const q of questions.filter(q=>q.isGraph))await copyFile(join(folder,'images',q.questionId+'-choices.svg'),join(dist,'downloads/images',q.questionId+'-choices.svg'));
 await zipFiles([{name:`${name}/${name}.md`,data:Buffer.from(md)},...assets],join(folder,'../'+name+'.zip'));await copyFile(join(folder,'../'+name+'.zip'),join(dist,'downloads',name+'.zip'));
 const index=`<div class="page-heading"><div><p class="eyebrow">One course · Units 1–10</p><h1>Build your understanding.</h1><p>${lessons.length} lessons · ${questions.length} questions · Complete worked solutions</p></div><a class="button" href="/downloads/${name}.zip" download>Download complete course</a></div><section class="panel workbook-intro"><h2>Algebra 2 · 2018 Student Edition</h2><p>Lesson guides follow your supplied textbook, from linear equations through trigonometric identities. Read an explanation, study worked examples, and practice at five levels.</p><div class="workbook-actions"><a class="button secondary" href="/practice/setup">Choose adaptive practice</a><a class="text-button" href="/downloads/${name}.md" download>Markdown file</a><a class="text-button" href="/ebook/chapter1/p1">Original textbook</a></div><nav class="unit-shortcuts" aria-label="Course units">${courseUnits.map(u=>`<a href="#unit-${u.id}">Unit ${u.id}</a>`).join('')}</nav></section>${courseUnits.map(u=>`<section class="workbook-chapter" id="unit-${u.id}"><div class="section-heading"><h2>Unit ${u.id} — ${esc(u.title)}</h2><span>${lessons.filter(l=>l.chapter===u.id).length*5} questions</span></div><div class="panel lesson-index">${lessons.filter(l=>l.chapter===u.id).map(l=>`<a href="${l.url}"><span class="lesson-code">${l.id}</span><span><strong>${esc(l.name)}</strong><small>Explanation · Examples · Q1–Q5 · Solutions</small></span><span aria-hidden="true">→</span></a>`).join('')}</div></section>`).join('')}`;
 await writeFile(join(dist,'workbook/index.html'),shell('Complete Algebra 2 Course',index));
 return {folder,markdown:join(folder,name+'.md'),zip:join(folder,'../'+name+'.zip')};
}
