import {foundations} from './foundations.mjs';
import {extensions} from './extensions.mjs';
import {unit3} from './units/unit3.mjs';
import {unit4} from './units/unit4.mjs';
import {unit5} from './units/unit5.mjs';
import {unit6} from './units/unit6.mjs';
import {unit7} from './units/unit7.mjs';
import {unit8} from './units/unit8.mjs';
import {unit9} from './units/unit9.mjs';
import {unit10} from './units/unit10.mjs';
const R=String.raw;
const rows=[
 ['1-1','Solving Linear Equations',2,'Isolate a variable using equivalent operations, and distinguish one solution, no solution, and identities.',R`Apply the same operation to both sides. After simplifying, \(ax=b\) has one solution if \(a\ne0\); \(0x=b\ne0\) has none; \(0x=0\) has all real solutions.`],
 ['1-2','Solving Linear Inequalities',10,'Solve inequalities and compound conditions while tracking which endpoints belong to the solution.',R`Multiplying or dividing an inequality by a negative number reverses its sign. “And” means intersection; “or” means union. Brackets include an endpoint; parentheses exclude it.`],
 ['1-3','Rate of Change and Slope',18,'Compare changes in output and input, interpret units, and use slope constraints to find unknown coordinates.',R`\[m=\frac{y_2-y_1}{x_2-x_1},\qquad x_2\ne x_1.\] A horizontal line has slope 0; a vertical line has undefined slope. Rate units are output units per input unit.`],
 ['1-4','Writing Linear Equations',25,'Write a line from geometric information, including parallel and perpendicular relationships.',R`\[y=mx+b,\qquad y-y_1=m(x-x_1).\] Parallel nonvertical lines have equal slopes. Perpendicular nonvertical lines have slopes whose product is \(-1\).`],
 ['1-5','Graphing Linear Inequalities',32,'Represent half-planes using a boundary and a tested shading direction.',R`Use a solid boundary for \(\le\) or \(\ge\), and a dashed boundary for \(<\) or \(>\). Test a point off the boundary to choose the shaded side. Recheck the sign when dividing by a negative coefficient.`],
 ['1-6','Solving Systems of Equations',39,'Find common solutions, detect dependent or inconsistent equations, and model mixtures.',R`Use substitution or elimination, then check both original equations. Equal coefficient ratios with unequal constant ratios give parallel, distinct lines. For a mixture, conserve both total volume and pure substance.`],
 ['1-7','Solving Systems of Inequalities by Graphing',49,'Find the overlap of several half-planes and identify the complete feasible region.',R`A point is feasible only if it satisfies every inequality. Find vertices from boundary intersections, then reject intersections that violate any other constraint. Boundary inclusion is determined separately for each inequality.`],
 ['1-8','Optimization with Linear Programming',57,'Optimize a linear objective over a feasible region, including restrictions to integer decisions.',R`For a bounded polygonal feasible region, a linear objective attains an optimum at a vertex. If integer decisions are required, a fractional vertex is not an admissible answer; compare feasible integer candidates.`],
 ['1-9','Solving Systems of Equations in Three Variables',64,'Eliminate variables in stages and recognize contradictions caused by dependent equations.',R`Reduce three equations to two by elimination, solve for the remaining variables, then back-substitute. If a linear combination gives \(0=c\) with \(c\ne0\), the system is inconsistent.`],
 ['2-1','Functions and Continuity',4,'Evaluate functions, distinguish inputs from outputs, and reason about values where pieces join.',R`A function assigns exactly one output to each input in its domain. A graph passes the vertical line test when it represents a function. At a continuous join, the values approached from each side agree with the function value.`],
 ['2-2','Linearity and Symmetry',12,'Use constant rate of change and algebraic symmetry to characterize functions.',R`Linearity requires a constant slope. On a symmetric domain, \(f(-x)=f(x)\) means even (y-axis symmetry), and \(f(-x)=-f(x)\) means odd (origin symmetry). Symmetry about \(x=h\) is expressed by \(f(h+t)=f(h-t)\).`],
 ['2-3','Extrema and End Behavior',20,'Separate local from absolute extrema and account for domain restrictions and distant end behavior.',R`A local extremum is relative to nearby inputs; an absolute extremum compares the whole domain. For \(a(x-h)^2+k\), the vertex is \((h,k)\). On a closed interval, check relevant turning points and endpoints. A polynomial’s leading term determines its end behavior.`],
 ['2-4','Sketching Graphs of Functions',28,'Combine intercepts, signs, symmetry, monotonicity, and endpoints to select a valid sketch.',R`A sketch must satisfy all given features at once. A filled endpoint is included; an open endpoint is excluded. Check where the graph is above or below the x-axis and where it increases or decreases, not just its general shape.`],
 ['2-5','Graphing Special Functions',35,'Analyze piecewise, greatest-integer, step, and absolute-value functions with careful endpoint choices.',R`\[|u|=\begin{cases}u,&u\ge0,\\-u,&u<0.\end{cases}\] For an integer \(n\), \(\lfloor x\rfloor=n\) exactly when \(n\le x<n+1\). This workbook uses floor notation for the textbook’s greatest-integer function. Ceiling notation, when used, is defined in the question.`],
 ['2-6','Transformations of Functions',42,'Track changes to inputs and outputs and recover transformation parameters from points.',R`For \(g(x)=a f(b(x-h))+k\), a parent point \((u,v)\) becomes \((h+u/b,av+k)\), where \(b\ne0\). The horizontal scale is \(1/|b|\); the vertical scale is \(|a|\). Negative multipliers also reflect the graph.`],
 ['2-7','Solving Equations by Graphing',50,'Interpret solutions as intersections and distinguish intersection points from their x-coordinates.',R`The equation \(f(x)=g(x)\) asks where the two graphs have equal outputs. Report x-values for an equation, and ordered pairs when intersection points are requested. With piecewise functions, validate each candidate in its own branch and count a shared vertex only once.`]
];
export const units=[unit3,unit4,unit5,unit6,unit7,unit8,unit9,unit10];
export const lessons=[...rows.map(([id,name,ebookPage,summary,rule])=>({id,name,chapter:Number(id.split('-')[0]),ebookPage,ebookUrl:`/ebook/chapter${id.split('-')[0]}/p${ebookPage}`,url:`/workbook/${id}`,summary,rule,...foundations[id],recap:summary,connection:'Apply these ideas in the following lessons and revisit them through adaptive practice.'})),...units.flatMap(u=>u.lessons)].map(l=>({...l,extensions:extensions.filter(e=>e.lessonId===l.id)}));
export const edition={title:'Glencoe Algebra 2, Student Edition',publisher:'McGraw-Hill Education',year:2018,isbn:'978-0-07-903990-3',publisherUrl:'https://www.mheducation.com/prek-12/product/algebra-2-2018-student-edition-mcgraw-hill/9780079039903.html'};
