import {siteHeader,siteSidebar,siteMobileNav} from '/assets/site-shell.mjs';
import {readView,runCommand} from './store.mjs';
import {eligibleQuestions,availableMethods} from './engine.mjs';
let bank=[],view=null,draftScope=null,busy=false,error='',mistakeTab='active',lessonFilter='all',historyFilter='all',historyPage=0;
const levels=['Standard','Hard','Hard–Challenge','Challenge','Hardest'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${{
 book:'M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H3z M21 4h-6a3 3 0 0 0-3 3v14a4 4 0 0 1 4-2h5z',practice:'m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9z',mistakes:'M6 3h12v18l-6-4-6 4z M10 8h4 M10 11h4',history:'M3 11a9 9 0 1 1 2.5 7 M3 4v7h7 M12 7v5l3 2',arrow:'M4 12h16 m-6-6 6 6-6 6',back:'M20 12H4 m6-6-6 6 6 6',check:'m5 12 4 4L19 6',cross:'m6 6 12 12 M18 6 6 18',target:'M12 3a9 9 0 1 0 0 18 9 9 0 1 0 0-18 M12 7a5 5 0 1 0 0 10 5 5 0 1 0 0-10 M12 11v2',chart:'M4 20h16 M7 16v-5 M12 16V5 M17 16V8',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3',external:'M14 3h7v7 M21 3l-9 9 M10 5H5v14h14v-5',sliders:'M4 7h16 M4 17h16 M9 4v6 M15 14v6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',cloud:'M7 17H6a4 4 0 1 1 1-7 6 6 0 0 1 11-2 4.5 4.5 0 1 1 1 9h-2 M9 16l2 2 4-5',info:'M12 8h.01 M12 11v6 M12 2a10 10 0 1 0 0 20 10 10 0 1 0 0-20'
}[name]}"/></svg>`;
const route=()=>location.pathname.split('/').filter(Boolean)[1]||'setup';
const navUrl=name=>`/practice/${name}`;
function navigate(name,query=''){history.pushState({},'',navUrl(name)+query);error='';render();window.scrollTo({top:0,behavior:'instant'});$('#main')?.focus({preventScroll:true});}
function sourceLabel(q){return `<div class="source-label"><span>${esc(q.lessonId)} · ${esc(q.lessonName)}</span><a href="${esc(q.ebookUrl)}" target="_blank" rel="noopener noreferrer">Ebook p.${q.ebookPage} ${icon('external')}</a><a href="/workbook/${q.lessonId}" target="_blank" rel="noopener">Lesson workbook ${icon('external')}</a></div>`;}
const difficulty=q=>`<span class="difficulty-tag" data-level="${q.difficulty}">Q${q.difficulty} — ${esc(q.difficultyLabel)}</span>`;
function questionHeader(q,label){return `<header class="workbook-header" data-question-id="${esc(q.questionId)}"><div class="question-topline"><span class="question-index">${esc(label)}</span>${difficulty(q)}</div>${sourceLabel(q)}</header>`;}
function questionBody(q){return `<section class="question-block"><h2 class="section-title">Question</h2><div class="question-content">${q.promptHtml}</div></section>`;}
function solutionSection(a){return `<section class="explanation"><h2 class="section-title">Worked solution</h2><div class="question-content">${a.explanationHtml}</div></section>`;}
function reviewChoices(q){return q.choices?.length?`<section class="review-choices"><h3 class="section-title">Multiple Choice</h3>${choicesHtml(q,false)}</section>`:'';}
const date=s=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(s));
const time=ms=>ms<60000?`${Math.round(ms/1000)}s`:`${Math.floor(ms/60000)}m ${Math.round(ms%60000/1000)}s`;
const answerModes={mc:'Multiple Choice only',written:'Written Response only',both:'Both'};
function defaultScope(){return {answerMode:'written',selectedCourseIds:view.catalog.map(c=>c.id),selectedLessonIds:view.catalog.flatMap(c=>c.lessons.map(l=>l.id)),difficultyMode:'auto',selectedDifficulties:[1,2,3,4,5]};}
function scopeDraft(){if(!draftScope){const s=view.session;draftScope=s?{answerMode:s.answerMode??'written',selectedCourseIds:[...s.selectedCourseIds],selectedLessonIds:[...s.selectedLessonIds],difficultyMode:s.difficultyMode,selectedDifficulties:[...s.selectedDifficulties]}:defaultScope();}return draftScope;}
function totals(){const correct=view.history.filter(a=>a.isCorrect).length;return {answered:view.history.length,accuracy:view.history.length?Math.round(correct/view.history.length*100)+'%':'—',mistakes:view.mistakes.filter(m=>!m.isMastered).length};}
function stats(){const t=totals();return `<div class="stats-strip" aria-label="Your practice progress">${[['chart',t.answered,'Questions answered'],['target',t.accuracy,'Overall accuracy'],['mistakes',t.mistakes,'Mistakes to revisit']].map(([i,n,label])=>`<div class="stat"><div class="stat-icon">${icon(i)}</div><div><strong>${n}</strong><span>${label}</span></div></div>`).join('')}</div>`;}
function layout(content){const active=route()==='mistakes'?'mistakes':route()==='history'?'history':'practice';return `${siteHeader(active)}<div class="site-frame">${siteSidebar(active)}<main class="site-main main" id="main" tabindex="-1">${error?`<div class="notice error" role="alert">${esc(error)}</div>`:''}${content}</main></div>${siteMobileNav(active)}<dialog class="dialog" id="attempt-dialog" aria-labelledby="attempt-title"></dialog>`;}
function setup(){
 const s=scopeDraft(),newSession=new URLSearchParams(location.search).has('new');const allowed=s.difficultyMode==='auto'?[1,2,3,4,5]:s.selectedDifficulties;
 const eligible=eligibleQuestions(bank,s);
 const lessons=[...new Set(eligible.map(q=>q.lessonId))];
 return `<div class="page-heading"><div><p class="eyebrow">Practice, on your terms</p><h1>Choose your practice.</h1><p>Pick your lessons, difficulty, and answer method. We’ll help you work on what needs attention within your choices.</p></div>${view.session&&eligible.length?`<button class="button secondary" data-start>Continue practice ${icon('arrow')}</button>`:''}</div>${stats()}${view.session&&!newSession?`<div class="notice session-banner"><p><strong>Your session is in progress.</strong> Change your selections without losing your answers or learning history.</p><a class="text-button" href="/practice/setup?new=1" data-new-session>New session</a></div>`:''}<div class="setup-grid"><section class="panel"><div class="panel-heading"><div><h2>Lessons to practice</h2><p>Choose as many as you like.</p></div><div class="text-actions"><button class="text-button" data-scope-all="select">Select all</button><span>/</span><button class="text-button" data-scope-all="clear">Clear all</button></div></div>${view.catalog.map(c=>{
 const selected=c.lessons.filter(l=>s.selectedLessonIds.includes(l.id)&&s.selectedCourseIds.includes(c.id)).length;
 return `<div class="course-group"><label class="course-header"><input id="course-${c.id}" type="checkbox" data-course="${c.id}" ${selected===c.lessons.length?'checked':''} ${selected>0&&selected<c.lessons.length?'data-indeterminate':''}><div><strong>${esc(c.name)}</strong><small>${c.lessons.length} lessons · ${c.lessons.reduce((n,l)=>n+l.count,0)} questions</small></div><span class="count">${selected} selected</span></label>${c.lessons.map(l=>`<label class="lesson-row ${s.selectedLessonIds.includes(l.id)?'is-selected':''}"><input id="lesson-${l.id}" type="checkbox" data-lesson="${l.id}" data-parent="${c.id}" ${s.selectedLessonIds.includes(l.id)&&s.selectedCourseIds.includes(c.id)?'checked':''}><span class="lesson-code">${l.id}</span><span class="lesson-copy"><strong>${esc(l.name)}</strong><span class="lesson-meta">${l.count} questions · Ebook p.${l.ebookPage}</span></span>${view.mastery[l.id]?`<span class="mastery">${view.mastery[l.id].attempts} practiced</span>`:''}</label>`).join('')}</div>`;
 }).join('')}</section><div class="setup-aside"><section class="panel difficulty-panel"><h2>How challenging?</h2><p>Set the range that feels right for today.</p><div class="mode-control" role="radiogroup" aria-label="Difficulty mode">${[['auto','Auto'],['custom','Custom']].map(([value,label])=>`<label class="mode-option"><input id="mode-${value}" type="radio" name="difficulty-mode" value="${value}" ${s.difficultyMode===value?'checked':''}>${value==='auto'?icon('spark'):icon('sliders')}${label}</label>`).join('')}</div>${s.difficultyMode==='auto'?`<div class="auto-steps" aria-hidden="true">${[12,25,25,20,8].map(h=>`<i style="--height:${h}px"></i>`).join('')}</div><p class="auto-copy">A balanced mix that gradually adjusts to your recent answers. Your selected lessons always stay in control.</p>`:`<div class="difficulty-options">${levels.map((name,i)=>`<label class="difficulty-option"><input id="level-${i+1}" type="checkbox" data-difficulty="${i+1}" ${s.selectedDifficulties.includes(i+1)?'checked':''}>Q${i+1} — ${name}<span class="difficulty-level" aria-hidden="true">${levels.map((_,j)=>`<i class="${j<=i?'on':''}"></i>`).join('')}</span></label>`).join('')}</div><p class="auto-copy">Only checked levels can appear. Choose just one to keep every question at that level.</p>`}</section><section class="panel answer-mode-panel"><h2>How will you answer?</h2><div class="answer-mode-options" role="radiogroup" aria-label="Answer methods">${Object.entries(answerModes).map(([value,label])=>`<label><input id="answer-mode-${value}" name="answer-mode" type="radio" value="${value}" ${s.answerMode===value?'checked':''}><span>${label}</span></label>`).join('')}</div><p>Both methods belong to the same question and share one result and one practice weight. In Both mode, both answers must be correct.</p><p>Graphing questions use Multiple Choice only. Written Response only excludes graphing questions.</p></section><section class="start-panel"><h2>Your practice mix</h2><div class="summary-line"><span>Lessons</span><strong>${lessons.length} selected</strong></div><div class="summary-line"><span>Question pool</span><strong>${eligible.length} questions</strong></div><div class="summary-line"><span>Difficulty</span><strong>${s.difficultyMode==='auto'?'Auto':allowed.length===1?levels[allowed[0]-1]:allowed.length+' levels'}</strong></div><button id="start-practice" class="button" data-start ${!eligible.length||busy?'disabled':''}>${view.session&&!newSession?'Apply & continue':'Start practice'} ${icon('arrow')}</button>${!eligible.length?`<p class="selection-error" role="status">Choose lessons, difficulty, and an answer method with available questions.</p>`:''}<p class="start-note">${icon('lock')} Your selections are always respected.</p></section></div></div><p class="bank-limit">This edition includes 360 questions across Units 1–10: one question per difficulty in each lesson. Small selections may need to repeat questions.</p>`;
}
function sessionAside(){const s=view.session;if(!s)return '';return `<aside class="work-aside"><div class="panel session-card"><h2>This session</h2><div class="session-metrics"><div><strong>${s.questionsAnswered}</strong><span>Answered</span></div><div><strong>${s.questionsAnswered?Math.round(s.correctCount/s.questionsAnswered*100)+'%':'—'}</strong><span>Accuracy</span></div></div><div class="scope-info"><strong>Your practice scope</strong><div class="scope-chips">${s.selectedLessonIds.map(id=>`<span class="scope-chip">${esc(id)}</span>`).join('')}</div><span>${s.difficultyMode==='auto'?'Auto difficulty':s.selectedDifficulties.map(d=>`Q${d} — ${levels[d-1]}`).join(' · ')}</span><span>${answerModes[s.answerMode??'written']}</span></div><a class="button secondary" href="/practice/setup" data-route="setup">${icon('sliders')} Change practice selections</a></div><p class="paper-tip">Take your time. Enter your final answer and keep your reasoning in the Work box below it.</p></aside>`;}
function getDraft(){try{return JSON.parse(sessionStorage.getItem('practice-draft-'+view.current?.instanceId)||'{}');}catch{return {};}}
function fieldsHtml(q){const draft=getDraft();return q.fields.map(f=>`<div class="field ${f.type==='number'?'':'wide'}"><label for="answer-${f.key}">${esc(f.label)}</label><input id="answer-${f.key}" name="${f.key}" type="text" autocomplete="off" autocapitalize="none" spellcheck="false" maxlength="500" value="${esc(draft[f.key]||'')}" placeholder="${f.type==='line'?'Enter an equation':f.type==='interval'?'Enter an interval':f.type==='inequality'?'Enter an inequality':'Your answer'}" required ${f.hint?`aria-describedby="hint-${f.key}"`:''}>${f.hint?`<span class="field-hint" id="hint-${f.key}">${esc(f.hint)}</span>`:''}</div>`).join('');}
function choicesHtml(q,interactive=true){const draft=interactive?getDraft():{};return `<div class="choice-grid ${q.isGraph?'graph-choices':''}">${(q.choices??[]).map(c=>`<${interactive?'label':'div'} class="answer-choice">${interactive?`<input type="radio" name="choice" value="${c.letter}" aria-label="Choice ${c.letter}" ${draft.choice===c.letter?'checked':''} required>`:''}<span class="choice-letter">${c.letter}</span><div class="choice-content">${q.isGraph?`<img src="${c.image}" width="370" height="370" alt="Graph ${c.letter}: ${esc(c.description)}">`:c.html}</div></${interactive?'label':'div'}>`).join('')}</div>${q.isGraph?`<a class="text-button graph-enlarge" href="/practice/graphs/${q.questionId.replace(/^v2:/,'')}-choices.svg" target="_blank" rel="noopener">Enlarge all four graphs ↗</a>`:''}`;}
function answerSections(q){const methods=availableMethods(q,view.session);return `${methods.map(method=>`<fieldset class="answer-section"><legend>${method==='mc'?'Multiple Choice':'Written Response'}</legend><p class="answer-instruction">${method==='mc'?(q.isGraph?'Choose the graph that matches the question.':'Choose one answer.'):'Enter your final answer below.'}</p>${method==='mc'?choicesHtml(q):`<div class="fields">${fieldsHtml(q)}</div><div class="working-field"><label for="answer-work">Work / reasoning</label><textarea id="answer-work" name="work" rows="5" maxlength="5000" placeholder="Show your steps and explain your reasoning.">${esc(getDraft().work||'')}</textarea><p class="field-hint">Saved with your answer for review. Your working is not automatically graded.</p></div>`}</fieldset>`).join('')}<p class="one-question-note">${methods.length===2?'Both answers must be correct · ':''}One question · One result</p>`;}
function question(){
 if(!view.session)return empty('Choose where to begin.','Select your lessons and difficulty to start a practice session.','Set up practice','setup');
 if(!view.current){if(view.feedback)return feedback();if(!eligibleQuestions(bank,view.session).length)return empty('Choose your practice scope.','Select at least one lesson and one difficulty to continue. Your previous progress is saved.','Choose lessons','setup');return empty('Ready for another problem?','Continue with your selected lessons and difficulty.','Next question','next');}
 const q=view.current.question;
 return `<div class="page-heading"><div><p class="eyebrow">Algebra 2 · Chapter ${q.lessonId.split('-')[0]}</p><h1>A little more understanding.</h1><p>Work through the problem, then check your answer.</p></div></div>${view.current.onlyOneEligible?'<div class="notice">Your selection contains one question. It will repeat until you choose more lessons or difficulty levels.</div>':''}<div class="work-grid"><section class="panel question-card">${questionHeader(q,`Question ${view.session.questionsAnswered+1}`)}${questionBody(q)}<form class="answer-area" id="answer-form">${answerSections(q)}<div id="answer-error" role="alert"></div><div class="question-actions"><span>Your progress saves after each answer.</span><button class="button" type="submit" ${busy?'disabled':''}>Check answer ${icon('arrow')}</button></div></form></section>${sessionAside()}</div>`;
}
function comparison(attempt){return `<section class="answer-review"><h2 class="section-title">Your answer</h2><div class="answer-comparison"><div class="comparison-row heading"><span>Answer</span><span>You entered</span><span>Correct answer</span></div>${attempt.details.map(d=>`<div class="comparison-row"><span>${d.method==='written'?'<small class="answer-method-label">Written Response</small>':''}${esc(d.label)}</span><span class="${d.isCorrect?'answer-right':'answer-wrong'}">${esc(d.studentAnswer)}</span><span>${esc(d.correctAnswer)}</span></div>`).join('')}</div>${attempt.studentAnswer?.work?`<div class="saved-working"><h3 class="section-title">Your working</h3><p>${esc(attempt.studentAnswer.work)}</p></div>`:''}</section>`;}
function feedback(){const a=view.feedback;if(!a)return question();const q=a.question;const mistake=view.mistakes.find(m=>m.questionId===a.questionId);return `<div class="page-heading"><div><p class="eyebrow">Every answer is a step forward</p><h1>${a.isCorrect?'Keep building on it.':'Let’s work through it.'}</h1><p>${a.isCorrect?'Review the reasoning, then try your next question.':'Use the worked solution to see where the reasoning changes.'}</p></div></div><div class="work-grid"><section class="panel question-card"><div class="feedback-status ${a.isCorrect?'':'incorrect'}">${icon(a.isCorrect?'check':'info')}<div><h2>${a.isCorrect?'Correct':'Not quite — keep going'}</h2><p>${a.isCorrect?(mistake?mistake.isMastered?'This mistake is now marked mastered.':`${mistake.correctStreak} of 3 consecutive correct answers toward mastery.`:'Your answer is saved.'):'Saved to your Mistake Book. You can revisit it anytime.'}</p></div></div>${questionHeader(q,`Question ${view.session.questionsAnswered} · ${time(a.responseTime)}`)}<details class="feedback-prompt"><summary>View the question</summary>${questionBody(q)}${reviewChoices(q)}</details>${comparison(a)}${solutionSection(a)}<div class="feedback-bottom"><a class="button secondary" href="${q.ebookUrl}" target="_blank" rel="noopener">${icon('book')} Review ${q.lessonId} in Ebook</a><button class="button" data-next ${busy?'disabled':''}>Next question ${icon('arrow')}</button></div></section>${sessionAside()}</div>`;}
function empty(title,copy,label,action){return `<section class="panel empty-state"><div class="empty-icon">${icon(route()==='mistakes'?'mistakes':route()==='history'?'history':'practice')}</div><h2>${title}</h2><p>${copy}</p>${action==='next'?`<button class="button" data-next>${label} ${icon('arrow')}</button>`:`<a class="button" href="${navUrl(action)}" data-route="${action}">${label} ${icon('arrow')}</a>`}</section>`;}
function lessonOptions(){return `<option value="all">All lessons</option>${view.catalog.flatMap(c=>c.lessons).map(l=>`<option value="${l.id}" ${lessonFilter===l.id?'selected':''}>${l.id} · ${esc(l.name)}</option>`).join('')}`;}
function mistakes(){const all=view.mistakes,active=all.filter(m=>!m.isMastered).length,mastered=all.length-active;const list=all.filter(m=>(mistakeTab==='all'||(mistakeTab==='mastered'?m.isMastered:!m.isMastered))&&(lessonFilter==='all'||m.question.lessonId===lessonFilter)).sort((a,b)=>b.lastWrongAt.localeCompare(a.lastWrongAt));return `<div class="page-heading"><div><p class="eyebrow">Turn mistakes into understanding</p><h1>Your Mistake Book.</h1><p>A question stays here until you answer it correctly three times in a row. Mastered questions keep their history.</p></div></div><div class="filters"><div class="tabs" role="group" aria-label="Mistake status">${[['active',`To revisit · ${active}`],['mastered',`Mastered · ${mastered}`],['all',`All · ${all.length}`]].map(([value,label])=>`<button class="tab ${mistakeTab===value?'active':''}" data-mistake-tab="${value}" aria-pressed="${mistakeTab===value}">${label}</button>`).join('')}</div><select class="filter-select" aria-label="Filter mistakes by lesson" data-lesson-filter>${lessonOptions()}</select></div>${!list.length?empty(all.length?'No questions in this view.':'A fresh start.','Questions you miss will appear here with their worked solutions and a link to the lesson.','Choose practice','setup'):`<div class="mistake-list">${list.map(m=>{const q=m.question;return `<article class="panel mistake-card">${questionHeader(q,`Lesson ${q.lessonId}`)}${m.isMastered?'<span class="mastered-tag">Mastered</span>':''}<div class="mistake-preview question-content">${q.promptHtml}</div><div class="mistake-footer"><div class="mistake-counts"><strong>${m.wrongCount} ${m.wrongCount===1?'miss':'misses'} · ${m.correctStreak}/3 correct in a row</strong><br>Last practiced ${date(m.lastAttemptAt)}</div><div class="mistake-actions"><button class="button secondary" data-mistake-detail="${q.questionId}">See answer</button><button class="button" data-review="${q.questionId}" ${!m.eligible||busy?'disabled':''}>Practice again ${icon('arrow')}</button></div></div>${!m.eligible?`<div class="outside-scope">${q.active===false?'Earlier edition. Your original question and worked solution are preserved here.':'Outside your current selection. <a class="scope-link" href="/practice/setup" data-route="setup">Change practice selections</a> to include it.'}</div>`:''}</article>`;}).join('')}</div>`}`;}
function historyView(){const list=[...view.history].reverse().filter(a=>(lessonFilter==='all'||a.lessonId===lessonFilter)&&(historyFilter==='all'||(historyFilter==='correct'?a.isCorrect:!a.isCorrect)));const pages=Math.max(1,Math.ceil(list.length/20));historyPage=Math.min(historyPage,pages-1);const shown=list.slice(historyPage*20,historyPage*20+20);return `<div class="page-heading"><div><p class="eyebrow">A record of your work</p><h1>Practice history.</h1><p>Every answer, across every session. Changing your practice selection keeps this history intact.</p></div><a class="button secondary" href="/practice/setup?new=1" data-new-session>New session ${icon('arrow')}</a></div>${stats()}<div class="filters"><div class="tabs" role="group" aria-label="Answer result">${[['all','All answers'],['correct','Correct'],['incorrect','Incorrect']].map(([value,label])=>`<button class="tab ${historyFilter===value?'active':''}" data-history-tab="${value}" aria-pressed="${historyFilter===value}">${label}</button>`).join('')}</div><select class="filter-select" aria-label="Filter history by lesson" data-lesson-filter>${lessonOptions()}</select></div>${!shown.length?empty('Your progress starts here.','Your answers and worked solutions will be saved here after you begin practicing.','Start practicing','setup'):`<section class="panel"><table class="history-table"><thead><tr><th>Lesson</th><th class="difficulty-cell">Difficulty</th><th>Result</th><th class="time-cell">Time</th><th>Details</th></tr></thead><tbody>${shown.map(a=>`<tr><td><strong>${a.lessonId} · ${esc(a.question.lessonName)}</strong><small>${date(a.timestamp)}</small></td><td class="difficulty-cell">${difficulty(a.question)}</td><td><span class="result ${a.isCorrect?'':'wrong'}">${icon(a.isCorrect?'check':'cross')}${a.isCorrect?'Correct':'Incorrect'}</span></td><td class="time-cell">${time(a.responseTime)}</td><td><button class="text-button" data-attempt="${a.attemptId}">Review</button></td></tr>`).join('')}</tbody></table></section><div class="pagination"><button class="button secondary" data-history-page="${historyPage-1}" ${historyPage===0?'disabled':''}>${icon('back')} Previous</button><span>${historyPage+1} / ${pages} · ${list.length} answers</span><button class="button secondary" data-history-page="${historyPage+1}" ${historyPage>=pages-1?'disabled':''}>Next ${icon('arrow')}</button></div>`}`;}
function render(){if(!view)return;const focused=document.activeElement?.id;const r=route();const content=r==='setup'?setup():r==='question'?question():r==='feedback'?feedback():r==='mistakes'?mistakes():r==='history'?historyView():empty('Find your next step.','Choose Practice, Mistake Book, or History to continue.','Go to practice','setup');$('#app').innerHTML=layout(content);document.title=`${r==='mistakes'?'Mistake Book':r==='history'?'Practice History':'Adaptive Practice'} · Fieldnotes`;document.querySelectorAll('[data-indeterminate]').forEach(i=>i.indeterminate=true);bind();if(focused)document.getElementById(focused)?.focus({preventScroll:true});}
let updates;
try{updates=new BroadcastChannel('fieldnotes-practice-updates');updates.onmessage=async()=>{if(busy)return;try{const latest=await readView(bank);if(latest.revision!==view?.revision){view=latest;error='Practice was updated in another tab. Your saved history is up to date.';render();}}catch{}};}catch{}
async function act(command,nextRoute){
 if(busy)return;busy=true;error='';document.querySelectorAll('button').forEach(b=>b.disabled=true);
 try{view=await runCommand(bank,{operationId:crypto.randomUUID(),...command});draftScope=null;busy=false;updates?.postMessage({revision:view.revision});if(nextRoute)navigate(nextRoute);else render();$('#announcer').textContent=command.action==='answer'?(view.feedback?.isCorrect?'Correct. Your answer is saved.':'Not quite. Your answer is saved to your Mistake Book.'):'Practice updated.';}
 catch(e){busy=false;error=e.message||'Something went wrong. Please try again.';render();if(command.action==='answer'){$('#answer-error').innerHTML=`<div class="form-error">${esc(error)}</div>`;$('#answer-error').scrollIntoView({block:'nearest'});}else window.scrollTo({top:0,behavior:'instant'});}
}

async function scopeChanged(){
 if(!view.session||new URLSearchParams(location.search).has('new')){render();return;}
 const chosen=structuredClone(scopeDraft());busy=true;
 document.querySelectorAll('#main input,#main button').forEach(el=>el.disabled=true);
 try{view=await runCommand(bank,{operationId:crypto.randomUUID(),action:'configure',scope:chosen});draftScope=null;updates?.postMessage({revision:view.revision});}
 catch(e){error=e.message;}
 busy=false;render();
}

function toggle(array,value,on){return on?[...new Set([...array,value])]:array.filter(x=>x!==value);}
function bind(){
 document.querySelectorAll('[data-route]').forEach(a=>a.addEventListener('click',e=>{if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();draftScope=null;lessonFilter='all';if(a.dataset.route==='question'&&!view.current&&view.feedback)navigate('feedback');else navigate(a.dataset.route);}));
 document.querySelectorAll('[data-new-session]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();draftScope=null;navigate('setup','?new=1');}));
 document.querySelectorAll('[data-scope-all]').forEach(b=>b.addEventListener('click',()=>{const s=scopeDraft();s.selectedCourseIds=b.dataset.scopeAll==='select'?view.catalog.map(c=>c.id):[];s.selectedLessonIds=b.dataset.scopeAll==='select'?view.catalog.flatMap(c=>c.lessons.map(l=>l.id)):[];scopeChanged();}));
 document.querySelectorAll('[data-course]').forEach(input=>input.addEventListener('change',()=>{const s=scopeDraft(),c=view.catalog.find(c=>c.id===input.dataset.course);s.selectedCourseIds=toggle(s.selectedCourseIds,c.id,input.checked);for(const l of c.lessons)s.selectedLessonIds=toggle(s.selectedLessonIds,l.id,input.checked);scopeChanged();}));
 document.querySelectorAll('[data-lesson]').forEach(input=>input.addEventListener('change',()=>{const s=scopeDraft(),c=view.catalog.find(c=>c.id===input.dataset.parent);s.selectedLessonIds=toggle(s.selectedLessonIds,input.dataset.lesson,input.checked);s.selectedCourseIds=toggle(s.selectedCourseIds,c.id,c.lessons.some(l=>s.selectedLessonIds.includes(l.id)));scopeChanged();}));
 document.querySelectorAll('[name="difficulty-mode"]').forEach(input=>input.addEventListener('change',()=>{scopeDraft().difficultyMode=input.value;scopeChanged();}));
 document.querySelectorAll('[name="answer-mode"]').forEach(input=>input.addEventListener('change',()=>{scopeDraft().answerMode=input.value;scopeChanged();}));
 document.querySelectorAll('[data-difficulty]').forEach(input=>input.addEventListener('change',()=>{scopeDraft().selectedDifficulties=toggle(scopeDraft().selectedDifficulties,Number(input.dataset.difficulty),input.checked).sort();scopeChanged();}));
 document.querySelectorAll('[data-start]').forEach(button=>button.addEventListener('click',()=>{const action=view.session&&!new URLSearchParams(location.search).has('new')?'scope':'start';act({action,scope:structuredClone(scopeDraft())},'question');}));
 $('#answer-form')?.addEventListener('submit',e=>{e.preventDefault();const {choice,work,...written}=Object.fromEntries(new FormData(e.target));const methods=availableMethods(view.current.question,view.session);const answer={method:methods.length===2?'both':methods[0],choice,written,...(work!==undefined?{work}:{})};act({action:'answer',instanceId:view.current.instanceId,answer},'feedback');});
 $('#answer-form')?.addEventListener('input',e=>{const draft=Object.fromEntries(new FormData($('#answer-form')));try{sessionStorage.setItem('practice-draft-'+view.current.instanceId,JSON.stringify(draft));}catch{}});
 document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>act({action:'next'},'question')));
 document.querySelectorAll('[data-review]').forEach(b=>b.addEventListener('click',()=>act({action:'review',questionId:b.dataset.review},'question')));
 document.querySelectorAll('[data-mistake-tab]').forEach(b=>b.addEventListener('click',()=>{mistakeTab=b.dataset.mistakeTab;render();}));
 document.querySelectorAll('[data-history-tab]').forEach(b=>b.addEventListener('click',()=>{historyFilter=b.dataset.historyTab;historyPage=0;render();}));
 document.querySelectorAll('[data-lesson-filter]').forEach(s=>s.addEventListener('change',()=>{lessonFilter=s.value;historyPage=0;render();}));
 document.querySelectorAll('[data-history-page]').forEach(b=>b.addEventListener('click',()=>{historyPage=Number(b.dataset.historyPage);render();window.scrollTo({top:0,behavior:'instant'});}));
 document.querySelectorAll('[data-attempt]').forEach(b=>b.addEventListener('click',()=>showAttempt(view.history.find(a=>a.attemptId===b.dataset.attempt))));
 document.querySelectorAll('[data-mistake-detail]').forEach(b=>b.addEventListener('click',()=>showAttempt([...view.history].reverse().find(a=>a.questionId===b.dataset.mistakeDetail))));
}
function showAttempt(a){if(!a)return;const dialog=$('#attempt-dialog');dialog.innerHTML=`<div class="dialog-top"><h2 id="attempt-title">Review your answer</h2><button class="icon-button" aria-label="Close answer review" data-close-dialog>${icon('cross')}</button></div>${questionHeader(a.question,date(a.timestamp))}<p class="result ${a.isCorrect?'':'wrong'}">${icon(a.isCorrect?'check':'cross')}${a.isCorrect?'Correct':'Incorrect'}</p>${questionBody(a.question)}${reviewChoices(a.question)}${comparison(a)}${solutionSection(a)}`;dialog.querySelector('[data-close-dialog]').onclick=()=>dialog.close();dialog.showModal();}
window.addEventListener('popstate',()=>{draftScope=null;error='';render();});
window.addEventListener('focus',async()=>{if(!bank.length||busy)return;try{const latest=await readView(bank);if(latest.revision!==view?.revision){view=latest;render();}}catch{}});
async function boot(){try{const response=await fetch('/practice/questions.json');if(!response.ok)throw new Error('Practice questions could not be loaded.');bank=await response.json();view=await readView(bank);if(!location.pathname.startsWith('/practice/'))history.replaceState({},'','/practice/setup');render();}catch(e){$('#app').innerHTML=`<main class="loading-screen"><div class="loading-mark">ƒ</div><h1>Practice couldn’t open.</h1><p>${esc(e.message)}</p><button class="button" id="retry-load">Try again</button></main>`;$('#retry-load').onclick=()=>location.reload();}}
boot();
