import {R,N,T,S,I,P,unitContent,example as E} from '../course-common.mjs';
const U=unitContent(5,'Inverses and Radical Functions');const {lesson:L,add:Q}=U;
const root=(degree,a,h,k)=>({kind:'root',degree,a,h,k});
L(1,'Operations with Functions',4,'Add, subtract, multiply, and divide functions while keeping the domain of the original operation.',R`\[(f\pm g)(x)=f(x)\pm g(x),\quad(fg)(x)=f(x)g(x),\quad(f/g)(x)=f(x)/g(x).\] Use the common domain, and for a quotient also require \(g(x)\ne0\).`,R`Function operations combine outputs at the same input. Their domain is constrained by every original function, even if algebraic simplification later hides a restriction. For square roots, radicands must be nonnegative; for rational expressions, denominators cannot be zero. A quotient adds another condition: the entire denominator function must not equal zero. Write these restrictions before simplifying, then solve or evaluate using only valid inputs. The simplified formula and the original function can have different natural domains if the inherited restrictions are omitted.`,[E('Add at one input',R`If \(f(x)=x^2-1\) and \(g(x)=3x+2\), find \((f+g)(2)\).`,R`\(f(2)=3\) and \(g(2)=8\), so \((f+g)(2)=11\).`,'Both outputs are evaluated at the same input before addition.'),E('A quotient with a missing input',R`Simplify \((x^2-4)/(x-2)\) as a function.`,R`It equals \((x-2)(x+2)/(x-2)=x+2\) for \(x\ne2\).`,'The formula simplifies, but x = 2 is still excluded from the original quotient.')],['A simplified formula does not restore an excluded input.','For f/g, exclude both undefined values of g and zeros of g.','The common domain is an intersection, not a union.'],'Determine the domain first, simplify the operation second, and check proposed inputs last.','Builds on polynomial operations and prepares for rational-function analysis.');
Q(1,1,R`Let \(f(x)=2x-3\) and \(g(x)=x^2+1\). Find \((f+g)(2)\).`,['5','6','8','10'],'B',[N('value','(f + g)(2)',6)],R`\(f(2)=1\) and \(g(2)=5\), so their sum is 6.`,'The operation adds outputs, not the formulas’ inputs.');
Q(1,2,R`Let \(f(x)=x^2-9\) and \(g(x)=x-3\). Find \((f/g)(5)\) and the input excluded from this quotient's domain.`,[R`Value 8; exclude −3`,R`Value 5; exclude 3`,R`Value 8; exclude 3`,R`Value 8; exclude no inputs`],'C',[N('value','(f / g)(5)',8),N('excluded','Excluded input',3)],R`\(f/g=(x-3)(x+3)/(x-3)=x+3\), but the original denominator excludes 3. At input 5, the value is 8.`,'Cancellation does not remove the original domain restriction.');
Q(1,3,R`Let \(f(x)=\sqrt{x+2}\) and \(g(x)=\sqrt{5-x}\). Find the domain of \(fg\).`,[R`\((-2,5)\)`,R`\([-5,2]\)`,R`\(( -\infty,\infty)\)`,R`\([-2,5]\)`],'D',[I('[-2,5]')],R`The first radicand requires \(x\ge-2\); the second requires \(x\le5\). Both must hold, so the domain is \([-2,5]\).`,'Square roots may equal zero, so both endpoints are allowed.');
Q(1,4,R`Let \(f(x)=(x+1)/(x-2)\) and \(g(x)=(x-2)/(x+3)\). Find every excluded input of \(f/g\), and evaluate \((f/g)(1)\).`,[R`Exclude −3 and 2; value 8`,R`Exclude 2 only; value 8`,R`Exclude −3 and 2; value 1/2`,R`Exclude −1 and 2; value 8`],'A',[S('-3,2','Excluded inputs'),N('value','(f / g)(1)',8)],R`The original domains exclude 2 and −3. Also g must be nonzero, excluding 2 again. The quotient simplifies to \((x+1)(x+3)/(x-2)^2\), which at 1 is \(2(4)/1=8\).`,'Dividing by a rational function requires preserving both functions’ original restrictions.');
Q(1,5,R`Define \(f(x)=(x^2-1)/(x-1)\), \(g(x)=(x-1)/(x+1)\), and \(h=f/g\) on its original domain. For which real k does \(h(x)=k\) have exactly one real solution?`,[R`\(k=0\)`,R`\(k=8\)`,R`\(k=0\) or \(8\)`,R`Every \(k\ge8\)`],'B',[N('k','k',8)],R`The domain excludes \(x=1,-1\), and \(h(x)=(x+1)^2/(x-1)\). The equation becomes \(x^2+(2-k)x+(1+k)=0\), with discriminant \(k(k-8)\). A repeated root occurs at k = 0 or 8. At k = 0 the only root is −1, which is excluded; at k = 8 the root is 3, which is valid. When the discriminant is positive, both roots are valid because an excluded root can occur only at k = 0 (x = −1), while x = 1 never satisfies the quadratic.`,'The discriminant alone suggests two parameter values, but the inherited hole eliminates one of them.');

L(2,'Composition of Functions',11,'Evaluate nested functions in the correct order and determine which inputs make the whole composition meaningful.',R`\[(f\circ g)(x)=f(g(x)).\] Its domain consists of inputs in the domain of g whose outputs lie in the domain of f.`,R`Composition feeds one function's output into another function, so it generally depends on order. Work from the inside outward when evaluating. When constructing a formula, substitute the complete inner expression for every occurrence of the outer variable and keep parentheses around it. Domain analysis has two stages: the inner function must be defined, and its output must be an allowed input for the outer function. Functional identities such as f ∘ g = g ∘ f compare the resulting formulas for every input, which can impose several coefficient conditions.`,[E('Order matters',R`Let \(f(x)=x+2\), \(g(x)=3x-1\). Compare both compositions at 4.`,R`\(f(g(4))=f(11)=13\), while \(g(f(4))=g(6)=17\).`,'The same two functions can produce different answers in different orders.'),E('A composition domain',R`Let \(f(u)=\sqrt u\), \(g(x)=6-2x\). Find the domain of \(f\circ g\).`,R`The inner function accepts every real x, but its output must satisfy \(6-2x\ge0\). Therefore \(x\le3\).`,'Dividing the inequality by a negative number reverses its direction.')],['f ∘ g applies g first.','Use parentheses around a substituted expression.','Retain restrictions of the inner function even if they cancel in the final formula.'],'Evaluate inside first and check both stages of the domain.',
'Connects function operations to inverses and transformed radical functions.');
Q(2,1,R`Let \(f(x)=2x+1\) and \(g(x)=x^2\). Find \((f\circ g)(3)\).`,['49','10','19','37'],'C',[N('value','(f composed with g)(3)',19)],R`\(g(3)=9\), then \(f(9)=2(9)+1=19\).`,'Apply the inner function first.');
Q(2,2,R`Let \(f(x)=x+2\) and \(g(x)=3x-1\). Find \((f\circ g)(4)\) and \((g\circ f)(4)\), in that order.`,[R`\(17,13\)`,R`\(13,13\)`,R`\(17,17\)`,R`\(13,17\)`],'D',[N('fg','f(g(4))',13),N('gf','g(f(4))',17)],R`\(f(g(4))=f(11)=13\). Separately, \(g(f(4))=g(6)=17\).`,'Composition is not generally commutative.');
Q(2,3,R`For \(f(u)=\sqrt u\) and \(g(x)=6-2x\), the domain of \(f\circ g\) has the form \(x\le c\). Find c.`,['3','−3','6','−6'],'A',[N('c','Largest allowed input c',3)],R`Require \(6-2x\ge0\). This gives \(-2x\ge-6\), or \(x\le3\).`,'A zero radicand is allowed, so the boundary belongs to the domain.');
Q(2,4,R`Let \(f(u)=1/(u-2)\) and \(g(x)=(x+1)/(x-1)\). Find every input excluded from \(f\circ g\), and evaluate the composition at x = 2.`,[R`Exclude 3 only; value 1`,R`Exclude 1 and 3; value 1`,R`Exclude 1 and 2; value 1`,R`Exclude 1 and 3; value −1`],'B',[S('1,3','Excluded inputs'),N('value','f(g(2))',1)],R`The inner function excludes x = 1. The outer denominator also requires \(g(x)\ne2\); solving \((x+1)/(x-1)=2\) gives x = 3. The simplified composition is \((x-1)/(3-x)\), so its value at 2 is 1.`,'The missing input 1 is inherited from the inner function even though the simplified expression would assign it a value.');
Q(2,5,R`Let \(f(x)=3x+2\) and \(g(x)=ax+b\). Suppose \(f(g(x))=g(f(x))\) for every real x and \(g(g(1))=7\). Find every possible ordered pair \((a,b)\).`,[R`\((2,1)\) only`,R`\((-2,-3)\) only`,R`\((2,1),(-2,-3)\)`,R`\((2,-1),(-2,3)\)`],'C',[P('(2,1);(-2,-3)')],R`The composition identity gives \(3ax+3b+2=3ax+2a+b\), hence \(b=a-1\). Then \(g(1)=2a-1\), so \(g(g(1))=a(2a-1)+(a-1)=2a^2-1=7\). Thus \(a=\pm2\), with b = 1 or −3 respectively. Both pairs satisfy the original conditions.`,'The universal identity gives a linear relation between parameters; the iterated value supplies a second, quadratic constraint with two valid branches.');

L(3,'Inverse Functions and Relations',18,'Reverse input-output roles, restrict a domain when necessary, and distinguish an inverse function from a reciprocal.',R`\[f^{-1}(f(x))=x\] on the domain of f. To find an inverse relation, interchange x and y and solve for y. The domain and range swap.`,R`An inverse undoes a function, so each output must come from only one input if the inverse is to be a function. The horizontal line test checks this one-to-one condition. A quadratic on all real numbers fails, but a suitable half-domain can select one branch. Algebraically, swap input and output and solve, then use the original domain to choose a sign. The inverse graph is the reflection of the original across y = x. The symbol f⁻¹ denotes an inverse function, not 1/f; these operations have different formulas and domains.`,[E('Invert a linear function',R`Find the inverse of \(f(x)=(2x+1)/3\).`,R`Write \(y=(2x+1)/3\), swap to \(x=(2y+1)/3\), and solve: \(3x=2y+1\), so \(f^{-1}(x)=(3x-1)/2\).`,'Substituting either function into the other returns the original input.'),E('Select the correct square-root branch',R`Invert \(f(x)=(x-2)^2+1\) with domain \(x\ge2\).`,R`After swapping, \((y-2)^2=x-1\). The original domain requires \(y\ge2\), so \(f^{-1}(x)=2+\sqrt{x-1}\), for \(x\ge1\).`,'The domain restriction selects the positive square-root branch.')],['An inverse is not the reciprocal.','A ± formula gives two branches unless a domain restriction selects one.','The original range becomes the inverse domain.'],'Check one-to-one behavior, solve the swapped equation, and carry the domain and range through the reversal.','Connects composition with radical graphs and rational transformations.');
Q(3,1,R`If \(f(x)=3x-5\), find \(f^{-1}(7)\).`,['2','4','16','1/7'],'B',[N('value','Inverse value',4)],R`Solve \(3x-5=7\): \(3x=12\), so x = 4.`,'The inverse asks which input produced 7.');
Q(3,2,R`The inverse of \(f(x)=(2x+1)/3\) is \(f^{-1}(x)=ax+b\). Find a and b.`,[R`\((a,b)=(2/3,1/3)\)`,R`\((3/2,1/2)\)`,R`\((3/2,-1/2)\)`,R`\((2/3,-1/3)\)`],'C',[N('a','a','3/2'),N('b','b','-1/2')],R`Swap x and y and solve \(3x=2y+1\). Then \(y=(3x-1)/2\).`,'The order of undoing addition and multiplication is reversed.');
Q(3,3,R`For \(f(x)=(x-2)^2+1\) on \(x\ge2\), express the inverse as \(h+\sqrt{x-k}\). Find h and k.`,[R`\(2-\sqrt{x-1}\)`,R`\(-2+\sqrt{x-1}\)`,R`\(2+\sqrt{x+1}\)`,R`\(2+\sqrt{x-1}\)`],'D',[N('h','h',2),N('k','k',1)],R`The swapped equation gives \(y-2=\pm\sqrt{x-1}\). The required inverse outputs satisfy \(y\ge2\), selecting the plus sign. Thus h = 2 and k = 1.`,'The original domain determines which reflected branch is the inverse function.');
Q(3,4,R`For \(f(x)=(2x+3)/(x-1)\), express \(f^{-1}(x)\) as \((x+a)/(x+b)\). Find a and b.`,[R`\((x+3)/(x-2)\)`,R`\((x-3)/(x+2)\)`,R`\((2x+3)/(x-1)\)`,R`\((x+1)/(x-2)\)`],'A',[N('a','a',3),N('b','b',-2)],R`Swap and solve: \(x=(2y+3)/(y-1)\), so \(xy-x=2y+3\). Thus \((x-2)y=x+3\), giving \(y=(x+3)/(x-2)\), with x ≠ 2.`,'Collect the terms containing the unknown y before dividing; the inverse excludes the value absent from the original range.');
Q(3,5,R`Let \(f(x)=x^2-4x+7\) with domain \(x\ge c\). Choose c so that f has an inverse function whose domain is exactly \([3,\infty)\). Then determine the number of intersections between the graphs of f and its inverse.`,[R`\(c=2\); 1 intersection`,R`\(c=3\); 0 intersections`,R`\(c=2\); 0 intersections`,R`\(c=2\); 2 intersections`],'C',[N('c','c',2),N('count','Number of intersections',0)],R`Since \(f(x)=(x-2)^2+3\), attaining the full range \([3,\infty)\) requires including x = 2. One-to-one behavior on a right half-line requires c ≥ 2, so c = 2. Also \(f(x)-x=x^2-5x+7=(x-5/2)^2+3/4>0\). Thus f lies above y = x, and its inverse lies below y = x on its domain; they cannot intersect.`,'The range requirement and injectivity force a single domain choice. The strict comparison with the diagonal rules out intersections without relying on an approximate graph.');

L(4,'Graphing Square Root Functions',27,'Use the endpoint, domain, and reference points to graph transformed square-root functions.',R`\[y=a\sqrt{x-h}+k\quad (x\ge h).\] The endpoint is \((h,k)\). Positive a gives range \([k,\infty)\); negative a gives \(( -\infty,k]\).`,R`The parent square-root graph starts at the origin because negative radicands have no real square roots. A horizontal shift moves its endpoint, a vertical shift moves every output, and a negative outside multiplier reflects the curve vertically. Choose radicands 0, 1, 4, and 9 to obtain exact reference points. If the input expression has a negative coefficient, solve its inequality before deciding which way the curve extends. For a sum of square roots, intersect their domains and use algebraic comparisons to locate extreme values.`,[E('Build a graph from its endpoint',R`Describe \(y=3\sqrt{x+2}-1\).`,R`The endpoint is \((-2,-1)\). Radicands 1 and 4 give \((-1,2)\) and \((2,5)\). The domain is \([-2,\infty)\), and the range is \([-1,\infty)\).`,'Exact points establish the shape and scale before sketching.'),E('A reflected input',R`Find the domain and endpoint of \(y=\sqrt{5-x}+2\).`,R`Require \(5-x\ge0\), so \(x\le5\). The endpoint is \((5,2)\), and the curve extends left with range \([2,\infty)\).`,'A negative coefficient inside the radical reverses the horizontal direction.')],['Read the horizontal shift from x − h, not from the sign alone.','The square-root symbol represents the nonnegative root.','A reflected output changes the range, while a reflected input changes the domain direction.'],'Locate the endpoint, solve the domain inequality, and plot exact reference points.','Uses inverse-function branches and prepares for radical equations.');
Q(4,1,R`Choose the graph of \(y=\sqrt{x-2}+1\).`,null,'B',[],R`The graph begins at \((2,1)\), extends right, and passes through \((3,2)\) and \((6,3)\).`,'These points distinguish the horizontal and vertical shifts.',{window:[-5,9,-5,7],choices:[root(2,1,-2,1),root(2,1,2,1),root(2,-1,2,1),root(2,1,2,-1)].map(c=>({curves:[c]}))});
Q(4,2,R`For \(f(x)=-2\sqrt{x+3}+4\), find its largest output and its smallest allowed input.`,[R`Largest output 4; smallest input 3`,R`Largest output −4; smallest input −3`,R`Largest output 4; smallest input −3`,R`No largest output; smallest input −3`],'C',[N('maximum','Largest output',4),N('minimumInput','Smallest allowed input',-3)],R`The radicand requires x ≥ −3. Since the square root is nonnegative, \(-2\sqrt{x+3}+4\le4\), with equality at x = −3.`,'The endpoint gives both requested values, but they describe different axes.');
Q(4,3,R`A function \(f(x)=a\sqrt{x-h}+k\) has endpoint \((1,-2)\) and passes through \((10,4)\). Find a, h, and k.`,[R`\((a,h,k)=(2,1,-2)\)`,R`\((3,1,-2)\)`,R`\((2,-1,-2)\)`,R`\((-2,1,2)\)`],'A',[N('a','a',2),N('h','h',1),N('k','k',-2)],R`The endpoint gives h = 1, k = −2. Substitute the other point: \(4=a\sqrt9-2\), so \(6=3a\) and a = 2.`,'Use the endpoint before solving for the scale factor.');
Q(4,4,R`Choose the square-root graph that starts at \((-1,3)\), extends right, and passes through \((3,-1)\).`,null,'D',[],R`In \(y=a\sqrt{x+1}+3\), the second point gives \(-1=2a+3\), so a = −2.`,'The negative multiplier makes the graph decrease from its endpoint.',{window:[-5,8,-6,7],choices:[root(2,2,-1,3),root(2,-1,-1,3),root(2,-2,1,3),root(2,-2,-1,3)].map(c=>({curves:[c]}))});
Q(4,5,R`Let \(f_h(x)=\sqrt{x-h}+\sqrt{10-x}\), with \(h<10\). Choose h so that the maximum value of f is 6, and find the input where that maximum occurs.`,[R`\(h=-8,\ x=1\)`,R`\(h=-26,\ x=-8\)`,R`\(h=1,\ x=6\)`,R`\(h=-8,\ x=5\)`],'A',[N('h','h',-8),N('x','Input at the maximum',1)],R`Set u = x − h and v = 10 − x, so u,v ≥ 0 and u + v = 10 − h. Since \((\sqrt u-\sqrt v)^2\ge0\), \((\sqrt u+\sqrt v)^2\le2(u+v)=2(10-h)\). Equality occurs when u = v. Thus the maximum is \(\sqrt{2(10-h)}=6\), giving h = −8. Equal radicands then give x + 8 = 10 − x, so x = 1.`,'The fixed sum of the radicands gives a sharp bound; checking its equality condition identifies the input.');

L(5,'Graphing Cube Root Functions',34,'Graph cube-root transformations and use their one-to-one behavior to connect them with cubic inverses.',R`\[y=a\sqrt[3]{x-h}+k.\] For nonzero a, the domain and range are both all real numbers; the center is \((h,k)\).`,R`Every real number has exactly one real cube root, including negative numbers. The parent graph passes through (−8,−2), (−1,−1), (0,0), (1,1), and (8,2). Shift and scale these reference points to graph a transformation. The center is not an endpoint: the curve continues in both directions. A nonzero multiplier preserves one-to-one behavior, so an inverse can be found by isolating the cube root and cubing. When an equation relates two cube roots, substitution can reveal a useful difference-of-cubes identity.`,[E('Transform reference points',R`Find three points on \(y=2\sqrt[3]{x+1}-4\).`,R`Choose x + 1 = −8, 0, 8. This gives points \((-9,-8)\), \((-1,-4)\), and \((7,0)\).`,'The center is the middle reference point, not a domain boundary.'),E('Invert a cube-root function',R`Find the inverse of \(f(x)=\sqrt[3]{x-5}+2\).`,R`Swap x and y: \(x-2=\sqrt[3]{y-5}\). Cube both sides: \(y=(x-2)^3+5\).`,'Cubing is one-to-one on real numbers, so no ± branch is needed.')],['The cube root of a negative number is real and negative.','Do not treat the center as an endpoint.','Cube the entire isolated expression, including parentheses.'],'Use perfect-cube reference inputs and retain both branches of the continuous real graph.','Connects odd-degree polynomials, inverses, and radical equations.');
Q(5,1,R`Choose the graph of \(y=\sqrt[3]x+1\).`,null,'C',[],R`The center is \((0,1)\), and reference points include \((-1,0)\), \((1,2)\), and \((8,3)\).`,'The curve extends through the center in both directions.',{window:[-9,9,-5,5],choices:[root(3,1,1,0),root(3,-1,0,1),root(3,1,0,1),root(3,1,0,-1)].map(c=>({curves:[c]}))});
Q(5,2,R`For \(f(x)=2\sqrt[3]{x-1}-3\), find f(−26).`,['−9','3','−6','9'],'A',[N('value','f(−26)',-9)],R`\(f(-26)=2\sqrt[3]{-27}-3=2(-3)-3=-9\).`,'Evaluate the input inside the radical before taking the cube root.');
Q(5,3,R`The inverse of \(f(x)=2\sqrt[3]{x-1}+3\) has the form \(a(x-h)^3+k\). Find a, h, and k.`,[R`\((a,h,k)=(2,3,1)\)`,R`\((1/8,3,1)\)`,R`\((1/2,3,1)\)`,R`\((1/8,-3,-1)\)`],'B',[N('a','a','1/8'),N('h','h',3),N('k','k',1)],R`After swapping, \((x-3)/2=\sqrt[3]{y-1}\). Cubing gives \(y-1=(x-3)^3/8\), hence the inverse is \((x-3)^3/8+1\).`,'The factor 2 must also be cubed when undoing the cube root.');
Q(5,4,R`The graph of \(f(x)=a\sqrt[3]{x-h}+k\) has center \((2,-1)\) and passes through \((10,5)\). Find a and f(−6).`,[R`\(a=2,\ f(-6)=-5\)`,R`\(a=3,\ f(-6)=5\)`,R`\(a=-3,\ f(-6)=5\)`,R`\(a=3,\ f(-6)=-7\)`],'D',[N('a','a',3),N('value','f(−6)',-7)],R`The center gives h = 2 and k = −1. Then \(5=a\sqrt[3]8-1=2a-1\), so a = 3. Finally \(f(-6)=3\sqrt[3]{-8}-1=-7\).`,'Use the center and one known point to determine the entire transformation.');
Q(5,5,R`Solve \(\sqrt[3]{x+7}-\sqrt[3]{x-7}=2\). The real solutions have the form \(x=\pm a\sqrt b\), where a and b are positive integers and b is squarefree. Find a and b.`,[R`\(\pm7\sqrt2\)`,R`\(\pm5\sqrt3\)`,R`\(\pm5\sqrt2\)`,R`\(5\sqrt2\) only`],'C',[N('a','a',5),N('b','b',2)],R`Let \(u=\sqrt[3]{x+7}\), \(v=\sqrt[3]{x-7}\). Then u − v = 2 and \(u^3-v^3=14\). The difference-of-cubes identity gives \(u^2+uv+v^2=7\). Substitute u = v + 2: \(3v^2+6v+4=7\), so \(v=-1\pm\sqrt2\). Cubing gives \(v^3=-7\pm5\sqrt2\), hence \(x=\pm5\sqrt2\). For either sign, u = v + 2 has cube x + 7, so both original radicals agree with the substitution.`,'A substitution converts the radical difference into a quadratic, and the final cube identities verify both solutions.');

L(6,'Solving Radical Equations',41,'Isolate radicals, remove them with appropriate powers, and test every candidate in the original equation.',R`\[\sqrt{A(x)}=B(x)\Rightarrow A(x)=B(x)^2,\quad B(x)\ge0.\] Even powers can introduce extraneous candidates; real odd powers are reversible.`,R`A radical equation requires both algebra and domain control. Isolate one radical before raising both sides to a power. For a square root, the other side must be nonnegative; squaring can erase this condition and create extraneous roots. With two radicals, isolate one, square, simplify, and repeat only if necessary. Check every candidate in the original expression. For cube roots, cubing preserves equality in both directions on real numbers. Parameter questions often become clearer after replacing a nonnegative square root with a new variable and explicitly keeping that variable nonnegative.`,[E('Reject an extraneous root',R`Solve \(\sqrt{x+6}=x\).`,R`Squaring yields \(x^2-x-6=(x-3)(x+2)=0\). The candidates are 3 and −2, but the original right side must be nonnegative. Only x = 3 works.`,'A squared equation is a candidate generator, not a final answer.'),E('A cube-root equation',R`Solve \(\sqrt[3]{2x+1}=3\).`,R`Cube both sides to get 2x + 1 = 27. Thus x = 13, and \(\sqrt[3]{27}=3\) verifies it.`,'No sign restriction is needed for an odd root.')],['Isolate the radical before applying a power.','Squaring a difference creates a cross term.','Check candidates in the original equation, including its sign restrictions.'],'Keep the domain, solve the powered equation, and verify all candidates.','Completes inverse and radical functions; the same domain discipline returns in logarithmic and rational equations.');
Q(6,1,R`Solve \(\sqrt{x+5}=3\).`,['9','4','−2','14'],'B',[N('x','x',4)],R`Square both sides: x + 5 = 9, so x = 4. Substitution gives \(\sqrt9=3\).`,'The isolated radical permits direct squaring.');
Q(6,2,R`Solve \(\sqrt{2x+3}=x\).`,['−1 and 3','−1','3','No real solutions'],'C',[N('x','x',3)],R`Squaring gives \(x^2-2x-3=(x-3)(x+1)=0\). The negative candidate −1 fails because the principal square root cannot equal −1. At x = 3 both sides equal 3.`,'An even power loses the sign information from the original equation.');
Q(6,3,R`Solve \(\sqrt[3]{3x-2}=-2\).`,['−2','2','−10/3','10/3'],'A',[N('x','x',-2)],R`Cube both sides: 3x − 2 = −8. Thus 3x = −6 and x = −2.`,'A negative cube root is valid.');
Q(6,4,R`Solve \(\sqrt{x+6}-\sqrt x=2\).`,['4','1','9/4','1/4'],'D',[N('x','x','1/4')],R`For x ≥ 0, isolate \(\sqrt{x+6}=2+\sqrt x\). Squaring gives \(x+6=4+4\sqrt x+x\), so \(\sqrt x=1/2\), hence x = 1/4. Check: \(\sqrt{25/4}-\sqrt{1/4}=5/2-1/2=2\).`,'Retaining the cross term after the first squaring leads to a simple second step.');
Q(6,5,R`Find all real k for which \(\sqrt{x+4}=x+k\) has exactly one real solution. Express the parameter set as \(( -\infty,a)\cup\{b\}\), and give a and b.`,[R`\(( -\infty,4)\cup\{17/4\}\)`,R`\(( -\infty,17/4]\)`,R`\([4,17/4]\)`,R`\(( -\infty,4]\)`],'A',[N('a','a',4),N('b','b','17/4')],R`Set \(t=\sqrt{x+4}\ge0\), so x = t² − 4 and \(t^2-t+k-4=0\). If k < 4, the product of the two t-roots is negative, giving exactly one positive root. At k = 4 the roots are 0 and 1, both allowed. If 4 < k < 17/4, the discriminant 17 − 4k is positive and both roots are positive. At k = 17/4 there is one repeated root t = 1/2. For larger k there are no real roots. Each allowed t gives exactly one x, so the requested set is \(( -\infty,4)\cup\{17/4\}\).`,'Counting nonnegative radical values avoids treating extraneous roots as solutions and handles the repeated-root boundary separately.');
export const unit5=U;
