import {R,N,T,S,I,P,unitContent,example as E} from '../course-common.mjs';
const U=unitContent(7,'Rational Functions');const {lesson:L,add:Q}=U;
const rec=(a,h,k)=>({kind:'reciprocal',a,h,k});
L(1,'Multiplying and Dividing Rational Expressions',4,'Factor rational expressions, simplify products and quotients, and preserve every original restriction.',R`\[\frac AB\cdot\frac CD=\frac{AC}{BD},\qquad \frac AB\div\frac CD=\frac{AD}{BC}.\] Original denominators and the divisor must be nonzero.`,R`A rational expression is a quotient of polynomials. Factor before canceling, because cancellation applies to common factors rather than individual terms in a sum. For division, take the reciprocal of the complete divisor and multiply. Record restrictions before this step: a divisor can be undefined or equal zero, and both cases are excluded. A canceled factor still leaves an excluded input. The simplified formula describes the same values only on the original domain.`,[E('Cancel factors',R`Simplify \((x^2-9)/(x^2+x-6)\).`,R`Factor to get \((x-3)(x+3)/[(x+3)(x-2)]=(x-3)/(x-2)\), with x ≠ −3,2.`,'The canceled factor leaves a hole at an originally excluded input.'),E('Divide expressions',R`Simplify \((x/4)\div(x^2/8)\).`,R`For x ≠ 0, multiply by 8/x² to get 2/x.`,'The divisor cannot equal zero, even though its own denominator is always nonzero.')],['Cancel factors, not terms joined by addition.','A divisor cannot be zero or undefined.','Record restrictions before cancellation.'],'Factor, restrict the original inputs, multiply by a reciprocal when needed, and cancel common factors.','Extends polynomial factoring and function operations.');
Q(1,1,R`Simplify \((x^2-9)/(x+3)\) as x + c on its original domain. Find c and the excluded input.`,[R`\(c=3;\ x\ne-3\)`,R`\(c=-3;\ x\ne-3\)`,R`\(c=-3;\ x\ne3\)`,R`\(c=3;\ x\ne3\)`],'B',[N('c','c',-3),N('excluded','Excluded input',-3)],R`Factor x² − 9 = (x − 3)(x + 3). Cancel x + 3 to obtain x − 3, retaining x ≠ −3.`,'The original denominator determines the excluded input.');
Q(1,2,R`Simplify \(\frac{x^2-4}{x^2-x-2}\). Its reduced form is \((x+a)/(x+b)\). Find a, b, and every originally excluded input.`,[R`\(a=2,b=1;\ -1,2\)`,R`\(a=-2,b=-1;\ -1,2\)`,R`\(a=2,b=1;\ -1\)`,R`\(a=2,b=-1;\ 1,2\)`],'A',[N('a','a',2),N('b','b',1),S('-1,2','Excluded inputs')],R`Factor to get (x − 2)(x + 2)/[(x − 2)(x + 1)]. The reduced form is (x + 2)/(x + 1), but x = 2 and x = −1 remain excluded.`,'A removable factor still restricts the original expression.');
Q(1,3,R`Evaluate \(\frac{x^2-1}{x^2-4}\cdot\frac{x-2}{x+1}\) at x = 3, and list every input excluded from the original product.`,[R`\(2/5;\ -2,2\)`,R`\(4/5;\ -2,-1,2\)`,R`\(2/5;\ -2,-1,2\)`,R`\(2;\ -1,2\)`],'C',[N('value','Value at x = 3','2/5'),S('-2,-1,2','Excluded inputs')],R`Factoring and canceling gives (x − 1)/(x + 2), with original restrictions x ≠ −2,2,−1. At x = 3 the value is 2/5.`,'Preserve restrictions from both denominators before simplifying.');
Q(1,4,R`For \(F(x)=\frac{x^2-4}{x-1}\div\frac{x+2}{x-3}\), find every excluded input and F(4).`,[R`Exclude 1,3; value 2/3`,R`Exclude −2,1,3; value 2`,R`Exclude −2,1; value 2/3`,R`Exclude −2,1,3; value 2/3`],'D',[S('-2,1,3','Excluded inputs'),N('value','F(4)','2/3')],R`The original denominators exclude 1 and 3; the divisor is zero at −2, also excluded. Multiplying by its reciprocal gives (x − 2)(x − 3)/(x − 1), hence F(4) = 2/3.`,'Division adds the zeros of the divisor to the original denominator restrictions.');
Q(1,5,R`Let \(F(x)=\frac{x^2-1}{x^2-4}\div\frac{x-1}{x+2}\) on its original domain. Find every real k for which F(x) = k has no real solution.`,[R`\(1\) only`,R`\(-2,1/4,1\)`,R`\(-2,1\)`,R`\(-2,-1,1,2\)`],'B',[S('-2,1/4,1','Values of k')],R`The domain excludes −2,2,1. The reduced formula is (x + 1)/(x − 2). For k ≠ 1, solving gives x = (2k + 1)/(k − 1), a unique candidate. It is never 2, but becomes −2 when k = 1/4 and becomes 1 when k = −2; those candidates are excluded. At k = 1 the equation would say x + 1 = x − 2, which is impossible. Thus precisely −2,1/4,1 are omitted outputs.`,'The simplified reciprocal-type function has one missing asymptotic output, and its inherited holes remove two additional outputs.');

L(2,'Adding and Subtracting Rational Expressions',13,'Use a least common denominator and combine complete numerators without losing signs or restrictions.',R`\[\frac AB+\frac CD=\frac{AD+BC}{BD}.\] Factoring denominators first can produce a smaller least common denominator.`,R`Addition and subtraction require matching denominator factors. Factor each denominator, choose a common denominator containing each factor to its highest needed power, and multiply every numerator by its missing factors. Keep parentheses around a subtracted numerator until distributing the negative sign. Combine and factor the resulting numerator, then simplify while retaining all original restrictions. For complex fractions, multiplying the entire numerator and denominator by their common denominator clears the smaller fractions.`,[E('Add fractions with related denominators',R`Simplify \(1/x+2/(3x)\).`,R`Use denominator 3x: 3/(3x) + 2/(3x) = 5/(3x), with x ≠ 0.`,'The numerator must change whenever the denominator is multiplied.'),E('Subtract complete numerators',R`Simplify \((x+2)/(x-1)-(x-3)/(x-1)\).`,R`The numerator is (x + 2) − (x − 3) = 5, so the result is 5/(x − 1), x ≠ 1.`,'The negative sign applies to both terms in the second numerator.')],['Do not add denominators.','Distribute a subtraction sign through the entire numerator.','Simplification cannot restore an originally excluded input.'],'Factor denominators, build the LCD, combine numerators, and retain restrictions.','Prepares for rational equations and inequalities.');
Q(2,1,R`Simplify \(2/x+3/x\) as c/x. Find c.`,['1','6','5','5/2'],'C',[N('c','c',5)],R`The denominators already match, so add the numerators: (2 + 3)/x = 5/x, with x ≠ 0.`,'Only numerators are added when denominators match.');
Q(2,2,R`Express \(1/(x-1)+1/(x+1)\) as \((ax+b)/(x^2-1)\). Find a and b.`,[R`\(a=2,b=0\)`,R`\(a=0,b=2\)`,R`\(a=1,b=0\)`,R`\(a=2,b=2\)`],'A',[N('a','a',2),N('b','b',0)],R`The LCD is (x − 1)(x + 1). The numerator is (x + 1) + (x − 1) = 2x, so a = 2 and b = 0; x ≠ ±1.`,'Each numerator gains the factor missing from its own denominator.');
Q(2,3,R`Express \(3/(x-2)-2/(x+2)\) as \((x+c)/(x^2-4)\). Find c and the value at x = 4.`,[R`\(c=2;\ 1/2\)`,R`\(c=10;\ 7/6\)`,R`\(c=-10;\ -1/2\)`,R`\(c=10;\ 14\)`],'B',[N('c','c',10),N('value','Value at x = 4','7/6')],R`The combined numerator is 3(x + 2) − 2(x − 2) = x + 10. At x = 4, the value is 14/12 = 7/6.`,'Distribute the subtraction through the full second product.');
Q(2,4,R`Simplify \(\frac{1/x+1/y}{1/x-1/y}\) for nonzero x,y with x ≠ y. Evaluate at x = 2,y = 5.`,['−7/3','3/7','7/10','7/3'],'D',[N('value','Value','7/3')],R`Multiplying the numerator and denominator by xy gives (x + y)/(y − x). At (2,5), this is 7/3.`,'The denominator becomes y − x, not x − y, because the first term is 1/x.');
Q(2,5,R`For which real k does \(1/(x-1)+1/(x+1)=k/(x-2)\) have exactly one real solution?`,['0 only','2 only','0 and 2','Every real k'],'C',[S('0,2','Values of k')],R`The domain excludes −1,1,2. Clearing denominators gives (2 − k)x² − 4x + k = 0. If k = 2, it is linear and has the valid root 1/2. Otherwise its discriminant is 4[(k − 1)² + 3] > 0, giving two distinct real candidates. Neither ±1 ever satisfies it; x = 2 is a candidate only when k = 0. At k = 0 the other root is 0, so exactly one remains. For all other k both candidates are valid.`,'There are two different ways to get a single valid solution: the quadratic can become linear, or one of its roots can be an excluded input.');

L(3,'Graphing Reciprocal Functions',20,'Transform the reciprocal parent graph and identify its center, branches, domain, and range.',R`\[f(x)=\frac a{x-h}+k,\quad a\ne0.\] Asymptotes: x = h and y = k. Domain: x ≠ h. Range: y ≠ k.`,R`The parent reciprocal function y = 1/x has two branches and never touches either coordinate axis. A transformation moves the asymptote intersection to (h,k); the sign of a determines which opposite regions contain the branches. Use points whose input offsets from h divide a conveniently. The asymptotes describe limiting behavior, not extra parts of the graph. Solving the function equation for x also shows why its shifted horizontal asymptote is absent from the range.`,[E('Locate transformed branches',R`Describe \(y=-4/(x+2)+1\).`,R`The asymptotes are x = −2 and y = 1. At x = −1, y = −3; at x = −3, y = 5. The negative coefficient places branches above-left and below-right of the center.`,'Use positions relative to the asymptotes, rather than the original axes.'),E('Find an inverse',R`Invert \(f(x)=3/(x-1)+2\).`,R`From x = 3/(y − 1) + 2, obtain y = 3/(x − 2) + 1, with x ≠ 2.`,'The two shift values swap as the graph reflects across y = x.')],['Do not connect branches across a vertical asymptote.','An asymptote is a guide, not a drawn segment of the function.','The horizontal shift is the value making the denominator zero.'],'Identify both asymptotes and plot points on each side of the excluded input.','Leads to general rational graphs and variation models.');
Q(3,1,R`Choose the graph of \(y=1/(x-2)+1\).`,null,'B',[],R`The asymptotes are x = 2 and y = 1; the graph passes through (3,2) and (1,0).`,'The positive numerator places the right branch above its horizontal asymptote.',{window:[-5,7,-5,7],choices:[rec(1,-2,1),rec(1,2,1),rec(-1,2,1),rec(1,2,-1)].map(c=>({curves:[c]}))});
Q(3,2,R`For \(f(x)=-3/(x+4)+2\), give the vertical asymptote x = h and the missing output k.`,[R`\(h=4,k=2\)`,R`\(h=-4,k=-2\)`,R`\(h=-4,k=2\)`,R`\(h=4,k=-2\)`],'C',[N('h','Vertical asymptote h',-4),N('k','Missing output k',2)],R`The denominator vanishes at x = −4. The fraction never equals zero, so f never equals 2.`,'The excluded input and output come from different shifts.');
Q(3,3,R`Find the x- and y-intercepts of \(f(x)=6/(x-1)-2\), as points.`,[R`\((4,0),(0,-8)\)`,R`\((3,0),(0,-6)\)`,R`\((-2,0),(0,4)\)`,R`\((4,0),(0,4)\)`],'A',[P('(4,0);(0,-8)')],R`Set y = 0: 6/(x − 1) = 2 gives x = 4. At x = 0, y = −6 − 2 = −8.`,'Set the opposite coordinate equal to zero for each intercept.');
Q(3,4,R`Choose the reciprocal graph with asymptotes x = 3 and y = −2 that passes through (5,4).`,null,'D',[],R`Write y = a/(x − 3) − 2. The point gives 4 = a/2 − 2, so a = 12.`,'The asymptotes determine the shifts and the point determines the scale.',{window:[-5,11,-10,10],choices:[rec(6,3,-2),rec(-12,3,-2),rec(12,-3,-2),rec(12,3,-2)].map(c=>({curves:[c]}))});
Q(3,5,R`Let \(f(x)=a/(x-2)+k\), a ≠ 0. Suppose f is its own inverse and f(3) = 5. Find a,k and the number of intersections of its graph with y = x.`,[R`\(a=3,k=2;\ 2\)`,R`\(a=3,k=2;\ 0\)`,R`\(a=2,k=3;\ 2\)`,R`\(a=-3,k=2;\ 2\)`],'A',[N('a','a',3),N('k','k',2),N('count','Number of intersections',2)],R`The inverse is 2 + a/(x − k). If it equals f as a function, their excluded inputs agree, forcing k = 2. The point then gives a + 2 = 5, so a = 3; this formula is indeed self-inverse. Intersections satisfy (x − 2)² = 3, giving two real inputs 2 ± √3, neither excluded.`,'Equality with the inverse forces agreement of domains before coefficient information is used.');

L(4,'Graphing Rational Functions',28,'Distinguish holes from vertical asymptotes and use degrees and division to describe end behavior.',R`For \(f=P/Q\), factor first. Canceled denominator zeros are holes; remaining denominator zeros may be vertical asymptotes. Polynomial division reveals horizontal or slant end behavior.`,R`A rational graph must retain the domain of the original quotient. Cancel common factors to identify the curve away from excluded inputs. At a canceled input with a finite limiting output, mark an open hole; at a remaining denominator zero, examine unbounded behavior. Compare numerator and denominator degrees: a smaller numerator degree gives horizontal asymptote zero, equal degrees give the ratio of leading coefficients, and a degree difference of one yields a slant asymptote by division. Check intercepts against the domain.`,[E('Find a hole',R`Analyze \((x^2-4)/(x-2)\).`,R`The reduced formula is x + 2 for x ≠ 2. Its graph is that line with the point (2,4) removed.`,'A denominator zero does not automatically create a vertical asymptote.'),E('Find a slant asymptote',R`Divide \((x^2+1)/(x-1)\).`,R`The result is x + 1 + 2/(x − 1). As |x| grows, the remainder term approaches zero, giving slant asymptote y = x + 1.`,'The vertical asymptote x = 1 and slant asymptote describe different limits.')],['Check for cancellation before labeling vertical asymptotes.','Draw holes as open points.','An x-intercept must belong to the original domain.'],'Factor, mark exclusions, find intercepts, and use degree or division for end behavior.','Combines polynomial division with reciprocal transformations.');
Q(4,1,R`For \(f(x)=(x^2-1)/(x-1)\), give the coordinates of the hole.`,[R`\((1,0)\)`,R`\((-1,0)\)`,R`\((1,2)\)`,R`\((-1,2)\)`],'C',[P('(1,2)')],R`Cancel x − 1 to obtain y = x + 1 away from x = 1. Its limiting value there is 2, so the hole is (1,2).`,'The reduced formula locates the missing output at the excluded input.');
Q(4,2,R`Find the horizontal asymptote y = k of \(f(x)=(3x^2+1)/(2x^2-5)\).`,['0','3/2','2/3','−1/5'],'B',[N('k','k','3/2')],R`The degrees are equal, so the limiting ratio is the leading-coefficient ratio 3/2.`,'The lower-degree terms become negligible relative to x² at large input magnitude.');
Q(4,3,R`Choose the graph of \(f(x)=(x^2-1)/(x-1)\), including its missing point.`,null,'A',[],R`The graph follows y = x + 1 except for an open hole at (1,2).`,'Cancellation leaves the original excluded input visible as an open point.',{window:[-4,6,-4,8],choices:[{curves:[{kind:'polynomial',coeff:[1,1],holes:[[1,2]]}]},{curves:[{kind:'polynomial',coeff:[1,1],holes:[[-1,0]]}]},{curves:[{kind:'polynomial',coeff:[1,-1],holes:[[1,0]]}]},{curves:[{kind:'polynomial',coeff:[1,1]}]}]});
Q(4,4,R`For \(f(x)=(x^2+1)/(x-1)\), express its slant asymptote as y = mx + b and give its vertical asymptote x = h.`,[R`\(m=1,b=-1,h=1\)`,R`\(m=0,b=1,h=1\)`,R`\(m=1,b=1,h=-1\)`,R`\(m=1,b=1,h=1\)`],'D',[N('m','m',1),N('b','b',1),N('h','h',1)],R`Polynomial division gives x + 1 + 2/(x − 1). The final term approaches zero for large |x| and is unbounded near x = 1. Thus the asymptotes are y = x + 1 and x = 1.`,'The nonzero remainder confirms the denominator factor does not cancel.');
Q(4,5,R`Find the smallest positive integer a for which \(f(x)=(x^2+ax+1)/(x^2-1)\) takes every real output value on its original domain.`,['1','2','3','4'],'C',[N('a','Smallest positive integer a',3)],R`Setting f(x) = y gives (y − 1)x² − ax − (y + 1) = 0. For y ≠ 1, its discriminant is a² + 4(y² − 1). If a > 2 this is positive for every y. Substituting x = 1 or −1 into this equation gives −a − 2 or a − 2, so neither excluded input can be a root. At y = 1 the linear solution is x = −2/a, also allowed. For a = 1 the value y = 0 has negative discriminant; for a = 2, f simplifies to (x + 1)/(x − 1) and never equals 1. Thus 3 is the smallest positive integer that works.`,'A claim about every output is converted into existence of a valid input for each y, including the special case where the quadratic becomes linear.');

L(5,'Variation Functions',37,'Translate direct, inverse, joint, and combined variation into equations and compare scale changes.',R`Direct: y = kx. Inverse: y = k/x. Joint: y = kxz. Combined examples include \(y=kx/z^2\).`,R`Variation statements specify how one quantity changes with others while a constant k stays fixed. “Directly” places a factor in the numerator, “inversely” places it in the denominator, and “jointly” combines several direct factors. A stated power applies to its complete variable factor. Use one known data point to determine k, then substitute the new conditions. For comparisons, ratios often cancel k and expose the change factors without first calculating the constant. Keep physical domains such as positive lengths in mind.`,[E('Find an inverse model',R`If y varies inversely with x and y = 8 when x = 3, find y when x = 12.`,R`k = xy = 24, so y = 24/12 = 2.`,'Increasing x by a factor of four reduces y by the same factor.'),E('Use combined variation',R`If \(y=kx/z^2\), how does y change when x doubles and z triples?`,R`The scale factor is 2/3² = 2/9.`,'Apply the square before comparing the new output.')],['Inverse variation is a reciprocal relation, not a negative slope rule.','Apply every stated power to the scale factor.','Keep the same variation constant within a model.'],'Translate the wording, determine k when needed, and compare multiplicative factors.','Connects reciprocal functions with physical and geometric models.');
Q(5,1,R`If y varies directly with x and y = 12 when x = 3, find y when x = 5.`,['15','20','7.2','60'],'B',[N('y','y',20)],R`k = 12/3 = 4, so y = 4(5) = 20.`,'Direct variation keeps the output-to-input ratio constant.');
Q(5,2,R`If y varies inversely with x and y = 6 when x = 4, find y when x = 8.`,['3','12','2','48'],'A',[N('y','y',3)],R`The product xy = 24 stays constant, so y = 24/8 = 3.`,'Doubling the input halves the output in inverse variation.');
Q(5,3,R`Suppose y varies jointly with x and z. If y = 30 when x = 2,z = 3, find y when x = 4,z = 5.`,['50','60','100','150'],'C',[N('y','y',100)],R`30 = k(2)(3), so k = 5. The new value is 5(4)(5) = 100.`,'Joint variation multiplies both direct factors.');
Q(5,4,R`For \(y=kx^2/z\), x increases by 50% while z decreases by 25%. By what factor does y change?`,['2','9/8','3/2','3'],'D',[N('factor','Multiplicative factor',3)],R`The factor is (1.5)²/0.75 = 2.25/0.75 = 3.`,'A 25% decrease gives a factor of 0.75, not 0.25.');
Q(5,5,R`A positive model has the form \(y=kx^a z^b\). Doubling x and tripling z multiplies y by 12; quadrupling x and tripling z multiplies y by 48. Find a,b and the output factor when x is tripled and z is halved.`,[R`\(a=2,b=1;\ 9/2\)`,R`\(a=1,b=2;\ 3/4\)`,R`\(a=2,b=-1;\ 18\)`,R`\(a=2,b=1;\ 6\)`],'A',[N('a','a',2),N('b','b',1),N('factor','New output factor','9/2')],R`The observations give 2ᵃ3ᵇ = 12 and 4ᵃ3ᵇ = 48. Dividing yields 2ᵃ = 4, so a = 2. Then 4·3ᵇ = 12 gives b = 1. The requested factor is 3²(1/2) = 9/2.`,'Comparing controlled changes eliminates the unknown constant and then one exponent, allowing the model structure to be inferred.');

L(6,'Solving Rational Equations and Inequalities',45,'Clear denominators in equations and use sign intervals for inequalities without including undefined inputs.',R`For rational equations, multiply by the LCD on the original domain. For inequalities, place everything on one side and test intervals separated by numerator and denominator zeros.`,R`Write denominator restrictions before doing algebra. Multiplication by a common denominator removes fractions from an equation, but candidate solutions at excluded inputs must be rejected. In an inequality, multiplying by a variable denominator is unsafe unless its sign is known, because a negative multiplier reverses the comparison. A sign chart avoids this problem: factor the single rational expression, mark its zeros and undefined points, and test each interval. Include allowed numerator zeros for non-strict inequalities and never include denominator zeros.`,[E('Solve an equation',R`Solve \(3/(x-1)=1\).`,R`Require x ≠ 1. Multiplying gives 3 = x − 1, so x = 4, which is allowed.`,'Clearing the denominator is valid on the original domain.'),E('Use a sign chart',R`Solve \((x-2)/(x+1)<0\).`,R`The critical inputs are −1 and 2. Testing the three intervals shows negativity only between them, so the solution is (−1,2).`,'Strict inequality excludes the zero; the denominator boundary is always excluded.')],['Never include an input that makes an original denominator zero.','Do not multiply an inequality by a variable expression without controlling its sign.','Even-multiplicity factors do not switch signs at their zeros.'],'Restrict the domain, solve carefully, and verify equations or test inequality intervals.','Completes rational-function analysis and reinforces algebraic domain reasoning.');
Q(6,1,R`Solve \(2/(x-1)=1\).`,['1','2','3','−1'],'C',[N('x','x',3)],R`For x ≠ 1, multiplying gives 2 = x − 1, so x = 3.`,'The result satisfies the denominator restriction.');
Q(6,2,R`Solve \(1/x+1/(x+2)=3/4\).`,['2 only','−4/3 only','−2 and 0','2 and −4/3'],'D',[S('2,-4/3')],R`Exclude 0 and −2. Multiply by 4x(x + 2): 4(x + 2) + 4x = 3x(x + 2), giving 3x² − 2x − 8 = (3x + 4)(x − 2) = 0. Both roots are allowed.`,'Check both roots against the original domain after clearing fractions.');
Q(6,3,R`Solve \((x-2)/(x+1)\le0\).`,[R`\((-1,2]\)`,R`\([-1,2]\)`,R`\((-1,2)\)`,R`\([2,\infty)\)`],'A',[I('(-1,2]')],R`The quotient is negative on (−1,2), zero at 2, and undefined at −1. Thus the solution is (−1,2].`,'An included zero and an excluded pole have different endpoint notation.');
Q(6,4,R`Solve \((x+1)/(x-2)=3/(x-2)\). How many real solutions does the original equation have?`,['1','0','2','Infinitely many'],'B',[N('count','Number of real solutions',0)],R`The domain requires x ≠ 2. Clearing the denominator gives x + 1 = 3, whose only candidate is x = 2. It is excluded, so there are no solutions.`,'A solution of the cleared equation need not solve the original rational equation.');
Q(6,5,R`For which real k does \((x^2-1)/(x-1)=k/(x-1)\) have exactly one real solution?`,['−1 only','0 only','−1 and 0','Every k ≥ −1'],'C',[S('-1,0','Values of k')],R`The domain excludes x = 1. Clearing gives x² = k + 1. For k < −1 there are no candidates; k = −1 gives the single allowed root 0. For k > −1 there are two distinct roots, except that at k = 0 the positive root 1 is excluded and the root −1 remains. No other positive-radicand case loses a root. Hence k = −1 or 0.`,'Count distinct roots first and then remove excluded inputs; a repeated root and a lost root create different single-solution cases.');
export const unit7=U;
