import {R,N,T,S,I,P,unitContent,example as E} from '../course-common.mjs';
const U=unitContent(3,'Quadratic Functions');const {lesson:L,add:Q}=U;
const poly=coeff=>({kind:'polynomial',coeff});
L(1,'Graphing Quadratic Functions',4,
'Connect a quadratic equation to its vertex, axis of symmetry, intercepts, and maximum or minimum value.',
R`\[f(x)=ax^2+bx+c=a(x-h)^2+k,\quad a\ne0,\quad h=-\frac b{2a},\quad k=f(h).\] The axis is \(x=h\). The vertex is a minimum when \(a>0\) and a maximum when \(a<0\).`,
R`A quadratic graph is a parabola. Start with the vertex and axis, then find the y-intercept and a reflected point. Equal horizontal distances from the axis give equal outputs. The sign of \(a\) controls the opening direction, while its magnitude controls vertical stretch. A graph's output range is determined by the vertex only when the stated domain includes it. In a model, first restrict the inputs to meaningful values: time may be nonnegative, and a number of price increases must be an integer. Compare adjacent integer inputs when the continuous vertex lies between them.`,
[E('Read vertex form',R`Describe \(f(x)=2(x-3)^2-8\).`,R`The vertex is \((3,-8)\), the axis is \(x=3\), and the minimum is \(-8\). Solve \(2(x-3)^2-8=0\): \((x-3)^2=4\), so \(x=1,5\). The y-intercept is \(f(0)=10\).`,'The graph opens upward and has range [−8, ∞). The roots lie equally far from the axis.'),E('Interpret a height model',R`For \(h(t)=-t^2+6t+7\), find the peak and when the object reaches ground level.`,R`Complete the square: \(h(t)=-(t-3)^2+16\). The peak is 16 at \(t=3\). Factoring gives \(-(t-7)(t+1)=0\), so the nonnegative ground time is \(t=7\).`,'The physical part of this model uses 0 ≤ t ≤ 7. The negative root is not a future landing time.')],
['The vertex is an ordered pair; its x-coordinate is not the maximum or minimum output.','Do not assume the vertex is feasible when the domain is restricted.','For integer decisions, compare both neighboring integers.'],
'Identify the domain, find the vertex, use symmetry, and interpret the result with its units.',
'Builds on Unit 2 transformations and extrema; prepares for quadratic equations and inequalities.');
Q(1,1,R`Which graph represents \(f(x)=(x-2)^2-3\)?`,null,'B',[],R`The vertex is \((2,-3)\), the axis is \(x=2\), and the parabola opens upward. These three features identify B.`,R`Changing \(x-2\) to \(x+2\) moves the vertex left. A negative leading coefficient flips the opening direction; adding 3 instead of subtracting it raises the vertex.`,{window:[-5,8,-6,12],choices:[{curves:[poly([1,4,1])]},{curves:[poly([1,-4,1])]},{curves:[poly([-1,4,-7])]},{curves:[poly([1,-4,7])]}]});
Q(1,2,R`Find the maximum value of \(f(x)=-2x^2+12x-7\) and the input where it occurs.`,[R`\(11\) at \(x=3\)`,R`\(3\) at \(x=11\)`,R`\(-7\) at \(x=0\)`,R`\(29\) at \(x=-3\)`],'A',[N('value','Maximum value',11),N('x','Input x',3)],R`\(f(x)=-2(x-3)^2+11\). The squared term is nonnegative, so its contribution is nonpositive. Equality occurs at \(x=3\).`,'The downward opening makes this an absolute maximum on the real domain.');
Q(1,3,R`A quadratic has zeros \(-1\) and \(5\), and \(f(0)=-10\). Find its minimum value and the input where it occurs.`,[R`\(-9\) at \(2\)`,R`\(-10\) at \(0\)`,R`\(-18\) at \(2\)`,R`\(-18\) at \(-2\)`],'C',[N('value','Minimum value',-18),N('x','Input x',2)],R`Write \(f(x)=a(x+1)(x-5)\). Substituting 0 gives \(-5a=-10\), hence \(a=2\). The axis lies midway between the roots, at \(x=2\), and \(f(2)=2(3)(-3)=-18\).`,'Recover the vertical scale before evaluating the vertex. The zeros alone do not determine the minimum.');
Q(1,4,R`A fundraiser charges \(24+3n\) dollars per ticket and sells \(120-8n\) tickets, where \(n\) is a nonnegative integer and sales cannot be negative. Find every revenue-maximizing \(n\) and the maximum revenue.`,[R`\(n=3\); \(3168\) dollars`,R`\(n=4\); \(3168\) dollars`,R`\(n=3.5\); \(3174\) dollars`,R`\(n=3,4\); \(3168\) dollars`],'D',[S('3,4','Every optimal integer n'),N('revenue','Maximum revenue in dollars',3168)],R`\(R(n)=(24+3n)(120-8n)=2880+168n-24n^2=-24(n-3.5)^2+3174\). The feasible integers are 0 through 15. The two closest integers to 3.5 are 3 and 4, and both give \(3174-24(0.5)^2=3168\).`,'The continuous vertex is not a permissible ticket-price decision. Symmetry makes the two neighboring integer decisions tie.');
Q(1,5,R`Find all real \(m\) such that \(x^2-2mx+m+2\ge0\) for **every** \(x\ge0\).`,[R`\([-2,2]\)`,R`\([-1,2]\)`,R`\((-2,2)\)`,R`\(( -\infty,2]\)`],'A',[I('[-2,2]')],R`The vertex input is \(x=m\). If \(m\le0\), the minimum on \([0,\infty)\) occurs at 0, so \(m+2\ge0\), giving \(-2\le m\le0\). If \(m>0\), the vertex is allowed and the minimum is \(m+2-m^2=-(m-2)(m+1)\). It is nonnegative for \(0<m\le2\). Combining the cases gives \([-2,2]\). At both endpoints the minimum is zero, so both are included.`,'A condition on every allowed input requires finding the minimum on the restricted domain. Using the unrestricted vertex for negative m would wrongly exclude valid parameters.');

L(2,'Solving Quadratic Equations by Graphing',16,
'Interpret real solutions as x-intercepts or as x-coordinates of intersections of two graphs.',
R`\[f(x)=0\iff (x,0)\text{ lies on the graph of }f.\] More generally, \(f(x)=g(x)\) is solved by the x-coordinates where their graphs meet.`,
R`Put a quadratic equation into a form whose solutions can be read from a graph. For \(f(x)=0\), inspect the x-axis: a parabola can cross twice, touch once, or miss it. For \(f(x)=g(x)\), graph both sides or graph their difference and find its zeros. A plotted intersection is a point, but the solution of an equation in x is its x-coordinate. A graphing window can hide distant roots, and a graph generally gives approximations; substitute candidates into the equation to check them. Repeated contact at the vertex counts as one distinct real solution.`,
[E('Translate crossings into solutions',R`The graph of \(y=x^2-x-6\) crosses the x-axis at \((-2,0)\) and \((3,0)\). Solve \(x^2-x-6=0\).`,R`The required outputs are zero, so the solutions are \(x=-2\) and \(x=3\). Direct substitution gives \(4+2-6=0\) and \(9-3-6=0\).`,'Report the inputs −2 and 3 rather than two ordered pairs.'),E('Intersect two functions',R`Solve \(x^2-4=x+2\).`,R`The intersections of \(y=x^2-4\) and \(y=x+2\) satisfy \(x^2-x-6=0=(x-3)(x+2)\). Thus \(x=-2,3\), with intersection points \((-2,0)\) and \((3,5)\).`,'The same x-values solve the equation even though the common y-values differ.')],
['An intersection point and a solution x-value are different requested outputs.','A tangent contact is one distinct solution, not two different points.','Do not trust a small graphing window to prove that no other roots exist.'],
'Choose the appropriate graphs, read every intersection, and verify candidate inputs.',
'Uses Unit 2 graph intersections and prepares for exact algebraic solution methods.');
Q(2,1,R`A quadratic graph crosses the x-axis at \((-3,0)\) and \((2,0)\). What are the solutions of \(f(x)=0\)?`,[R`\(0\)`,R`\(-3,2\)`,R`\(3,-2\)`,R`\(-3,0,2\)`],'B',[S('-3,2')],R`At each x-intercept the output is zero. The corresponding inputs are \(-3\) and \(2\).`,'Only the x-coordinates solve the equation in x.');
Q(2,2,R`Which panel correctly graphs **both** \(y=x^2-4\) (blue) and \(y=x+2\) (gray)?`,null,'C',[],R`The parabola has vertex \((0,-4)\), and the line has slope 1 and y-intercept 2. They intersect at \((-2,0)\) and \((3,5)\). Panel C meets all of these conditions.`,'Both formulas must match, not merely the general appearance of a line and a parabola.',{window:[-5,6,-7,12],choices:[{curves:[poly([1,0,4]),{...poly([1,2]),color:'gray'}]},{curves:[poly([1,0,-4]),{...poly([-1,2]),color:'gray'}]},{curves:[poly([1,0,-4]),{...poly([1,2]),color:'gray'}]},{curves:[poly([-1,0,-4]),{...poly([1,2]),color:'gray'}]}]});
Q(2,3,R`The graphs \(y=(x-1)^2\) and \(y=9\) intersect. Find all x-coordinates of their intersections.`,[R`\(-3,3\)`,R`\(-2,4\)`,R`\(2,4\)`,R`\(1,9\)`],'B',[S('-2,4')],R`Intersections satisfy \((x-1)^2=9\), so \(x-1=\pm3\), giving \(x=-2,4\).`,'The horizontal line is 9 units high; the square has both a positive and a negative square-root case.');
Q(2,4,R`An object's height is \(h(t)=-5t^2+20t+25\) meters after \(t\ge0\) seconds. Its graph meets the line \(h=40\) twice. Find both meeting times and how long the height is at least 40 meters.`,[R`\(1,3\); 2 seconds`,R`\(-1,5\); 6 seconds`,R`\(1,3\); 4 seconds`,R`\(2\); 0 seconds`],'A',[S('1,3','Meeting times'),N('duration','Duration in seconds',2)],R`Set \(-5t^2+20t+25=40\), giving \(t^2-4t+3=0\), or \((t-1)(t-3)=0\). The downward-opening parabola is on or above 40 between these crossings. The duration is \(3-1=2\) seconds.`,'The two intersections mark the beginning and end of the time interval, not two separate durations.');
Q(2,5,R`For which real \(k\ge0\) does the equation \(|x^2-4|=k\) have **exactly three distinct real solutions**?`,[R`\(0\)`,R`\(2\)`,R`\(4\)`,R`\(8\)`],'C',[N('k','k',4)],R`Split into \(x^2=4+k\) and \(x^2=4-k\). For \(0<k<4\), both positive right sides give four distinct roots. At \(k=4\), the first gives \(\pm\sqrt8\), while the second gives only 0: three roots. At \(k=0\), the two equations coincide and give two roots. For \(k>4\), only the first has real roots.`,'A root count must account for coinciding equations and for the two symmetric roots merging at zero.');

L(3,'Complex Numbers',25,
'Extend real-number arithmetic using i, simplify complex expressions, and use conjugates to divide.',
R`\[i^2=-1,\quad (a+bi)(a-bi)=a^2+b^2,\quad |a+bi|=\sqrt{a^2+b^2}.\] The powers of i repeat every four exponents.`,
R`A complex number has a real part and an imaginary coefficient. Combine like parts when adding, and use ordinary distributive multiplication before replacing \(i^2\) by \(-1\). The conjugate changes the sign of the imaginary part. Multiplying a quotient by the conjugate of its denominator produces a real denominator and leaves its value unchanged. Equality of two complex numbers requires equality of both real parts and both imaginary coefficients. For polynomials with real coefficients, nonreal roots occur in conjugate pairs, because conjugating every term preserves the equation.`,
[E('Multiply in standard form',R`Simplify \((2+3i)(4-i)\).`,R`\(8-2i+12i-3i^2=11+10i\).`,'Replace i² only after distributing every term; the last term contributes +3.'),E('Divide using a conjugate',R`Simplify \((3+i)/(2-i)\).`,R`Multiply numerator and denominator by \(2+i\): \((6+3i+2i+i^2)/(4-i^2)=(5+5i)/5=1+i\).`,'The denominator becomes a sum of squares, so the final expression is in a + bi form.')],
['i² is −1, not 1.','Conjugate only the imaginary sign; the real part stays the same.','Distribute a denominator over both real and imaginary terms.'],
'Reduce powers of i, combine real and imaginary parts, and use conjugates for division.',
'Explains the nonreal roots of quadratics that have no real x-intercepts.');
Q(3,1,R`Write \(i^{27}\) in the form \(a+bi\).`,[R`\(1\)`,R`\(i\)`,R`\(-1\)`,R`\(-i\)`],'D',[N('a','Real part a',0),N('b','Imaginary coefficient b',-1)],R`Since \(27=4(6)+3\), \(i^{27}=(i^4)^6i^3=-i\).`,'The remainder after division by four determines the power.');
Q(3,2,R`Write \((3-2i)(1+4i)\) as \(a+bi\).`,[R`\(11+10i\)`,R`\(-5+10i\)`,R`\(11-10i\)`,R`\(-5-10i\)`],'A',[N('a','Real part a',11),N('b','Imaginary coefficient b',10)],R`\(3+12i-2i-8i^2=3+10i+8=11+10i\).`,'The product of the imaginary terms contributes a positive real 8.');
Q(3,3,R`Write \(\dfrac{4+3i}{1-2i}\) as \(a+bi\).`,[R`\(2+11i\)`,R`\(-\frac25+\frac{11}5i\)`,R`\(\frac25-\frac{11}5i\)`,R`\(\frac{10}5+\frac{11}5i\)`],'B',[N('a','Real part a','-2/5'),N('b','Imaginary coefficient b','11/5')],R`Multiply by \((1+2i)/(1+2i)\). The numerator is \(4+8i+3i+6i^2=-2+11i\), and the denominator is \(1+4=5\).`,'The conjugate rationalizes the denominator without changing the complex value.');
Q(3,4,R`A complex number \(z=a+bi\), with \(b>0\), satisfies \(z+\overline z=6\) and \(z\overline z=25\). Find z.`,[R`\(6+5i\)`,R`\(3-4i\)`,R`\(3+4i\)`,R`\(4+3i\)`],'C',[N('a','Real part a',3),N('b','Imaginary coefficient b',4)],R`The first condition gives \(2a=6\), so \(a=3\). The second gives \(a^2+b^2=25\), hence \(b^2=16\). The stated condition \(b>0\) selects \(b=4\).`,'Both algebraic conditions and the sign restriction are needed to select one conjugate.');
Q(3,5,R`A nonreal number \(z=x+yi\) is a root of \(z^2-6z+a=0\), where a is real. Also \(|z-1|^2=13\). Find a, x, and \(|y|\).`,[R`\((a,x,|y|)=(18,3,3)\)`,R`\((13,3,2)\)`,R`\((18,6,3)\)`,R`\((9,3,0)\)`],'A',[N('a','a',18),N('x','Real part x',3),N('y','Absolute imaginary coefficient',3)],R`The imaginary part of the polynomial equation is \((2x-6)y=0\). Because \(y\ne0\), \(x=3\). The distance condition gives \((x-1)^2+y^2=13\), so \(y^2=9\). The real part gives \(x^2-y^2-6x+a=0\), hence \(9-9-18+a=0\) and \(a=18\).`,'Using the nonreal condition avoids the invalid branch y = 0. Both conjugate roots 3 ± 3i satisfy the distance constraint.');

L(4,'Solving Quadratic Equations by Factoring',32,
'Use the zero-product property, factor completely, and check solutions in the original model.',
R`\[AB=0\iff A=0\text{ or }B=0.\] First write the equation with zero on one side. For roots r and s, a quadratic has factored form \(a(x-r)(x-s)\).`,
R`Factoring changes a sum into a product whose zeros are easier to identify. Remove a greatest common factor first, then look for a trinomial, difference of squares, or common binomial. The zero-product property applies only when the product equals zero. Dividing by a variable expression can discard a solution whenever that expression might be zero. After solving an application, test roots against length, time, or other physical restrictions. A repeated factor gives a repeated root but only one distinct solution.`,
[E('Factor a nonmonic quadratic',R`Solve \(2x^2-7x-4=0\).`,R`\(2x^2-8x+x-4=(2x+1)(x-4)=0\), so \(x=-1/2\) or \(x=4\).`,'Both factors can be zero, and both candidates satisfy the original equation.'),E('Keep a shared factor',R`Solve \(x(x-3)=4(x-3)\).`,R`Subtract the right side and factor: \((x-3)(x-4)=0\). Therefore \(x=3,4\).`,'Dividing by x − 3 would remove the valid root 3.')],
['A product equal to a nonzero number does not allow setting each factor to zero.','Do not divide by a factor before considering its zero case.','Reject a negative length because of the model, not because negative algebraic roots are always invalid.'],
'Set the equation equal to zero, factor, solve every zero-factor case, and interpret the roots.',
'Connects the graph’s intercepts to exact factors and prepares for higher-degree polynomial equations.');
Q(4,1,R`Solve \(x^2-5x+6=0\).`,[R`\(-2,-3\)`,R`\(2,3\)`,R`\(1,6\)`,R`\(5,6\)`],'B',[S('2,3')],R`\(x^2-5x+6=(x-2)(x-3)\). Set either factor equal to zero.`,'The factor signs are opposite to the signs of the roots.');
Q(4,2,R`Solve \(2x^2-7x-4=0\).`,[R`\(1/2,4\)`,R`\(-1/2,-4\)`,R`\(-1/2,4\)`,R`\(-2,4\)`],'C',[S('-1/2,4')],R`Factor as \((2x+1)(x-4)=0\). Thus \(2x+1=0\) or \(x-4=0\).`,'The coefficient 2 must be included when solving the first linear factor.');
Q(4,3,R`Find every solution of \(x(x-3)=4(x-3)\).`,[R`\(4\) only`,R`\(3\) only`,R`\(0,3,4\)`,R`\(3,4\)`],'D',[S('3,4')],R`Move all terms to one side: \(x(x-3)-4(x-3)=(x-3)(x-4)=0\). The complete solution set is \(\{3,4\}\).`,'Cancelling x − 3 is not valid at x = 3 and would lose a solution.');
Q(4,4,R`A rectangular garden is 3 meters longer than it is wide. A 1-meter-wide path surrounds all four sides. The total outside area is 88 square meters. Find the garden's width and its area, excluding the path.`,[R`Width 6 m; area 54 m²`,R`Width 8 m; area 88 m²`,R`Width 6 m; area 88 m²`,R`Width 13 m; area 208 m²`],'A',[N('width','Garden width in meters',6),N('area','Garden area in square meters',54)],R`Let the garden width be w, so its length is \(w+3\). The outside dimensions are \(w+2\) and \(w+5\). Thus \((w+2)(w+5)=88\), or \(w^2+7w-78=(w+13)(w-6)=0\). Reject \(w=-13\). The garden area is \(6(9)=54\).`,'The path adds one meter to each side, increasing each overall dimension by two meters.');
Q(4,5,R`The quadratics \(x^2-(k+2)x+2k\) and \(x^2-(k+3)x+3k\) must each have two distinct real zeros. Across both polynomials there must be exactly three distinct zeros, and those three numbers, in increasing order, must form an arithmetic progression. Find all k.`,[R`\(2,3\)`,R`\(1,5/2,4\)`,R`\(5/2\) only`,R`\(-1,5/2,6\)`],'B',[S('1,5/2,4','All parameter values k')],R`Factor the polynomials as \((x-2)(x-k)\) and \((x-3)(x-k)\). Distinct roots require \(k\ne2,3\), and their union is \(\{2,3,k\}\). If k is smallest, \(2-k=3-2\), so \(k=1\). If k lies between 2 and 3, \(k-2=3-k\), so \(k=5/2\). If k is largest, \(3-2=k-3\), so \(k=4\). Each satisfies the restrictions.`,'The unknown can occupy any of the three positions in the ordered progression; assuming it is the middle term misses two cases.');

L(5,'Solving Quadratic Equations by Completing the Square',44,
'Turn a quadratic into a perfect square to solve equations, expose a vertex, and prove minimum values.',
R`\[x^2+bx=\left(x+\frac b2\right)^2-\left(\frac b2\right)^2,\qquad u^2=d\Rightarrow u=\pm\sqrt d\ (d\ge0).\] Divide by the leading coefficient before completing the square in an equation.`,
R`Completing the square works even when integer factoring fails. Isolate the variable terms, normalize the leading coefficient, and add the square of half the linear coefficient to both sides. When rewriting an expression, add and subtract the same quantity instead so the value stays unchanged. The resulting square reveals a vertex or a lower bound. For a constrained problem, first use the constraint to express the quantity in one variable; a minimum of the unconstrained expression may not be attainable on the allowed set.`,
[E('Solve an irrational-root equation',R`Solve \(x^2-4x-1=0\).`,R`\(x^2-4x=1\), so \(x^2-4x+4=5\). Therefore \((x-2)^2=5\) and \(x=2\pm\sqrt5\).`,'Both square-root signs are required.'),E('Expose a vertex',R`Rewrite \(2x^2-12x+7\) in vertex form.`,R`\(2(x^2-6x)+7=2[(x-3)^2-9]+7=2(x-3)^2-11\).`,'The 9 inserted inside the brackets is multiplied by 2, so the outside adjustment is −18.')],
['Half the coefficient of x first, then square it.','Account for a leading coefficient outside the completed square.','Include both signs when taking square roots in an equation.'],
'Complete a square without changing the equation or expression, then solve or interpret its vertex.',
'Links quadratic graphs to algebra and leads directly to the quadratic formula.');
Q(5,1,R`Solve \(x^2+6x+5=0\) by completing the square.`,[R`\(-5,-1\)`,R`\(5,1\)`,R`\(-3\pm\sqrt5\)`,R`\(-6,-1\)`],'A',[S('-5,-1')],R`\(x^2+6x=-5\). Adding 9 gives \((x+3)^2=4\), so \(x+3=\pm2\) and \(x=-5,-1\).`,'The same added quantity must appear on both sides.');
Q(5,2,R`Write \(2x^2-12x+7=2(x-h)^2+k\). Find h and k.`,[R`\((h,k)=(-3,-11)\)`,R`\((3,7)\)`,R`\((3,-2)\)`,R`\((3,-11)\)`],'D',[N('h','h',3),N('k','k',-11)],R`\(2[x^2-6x]+7=2[(x-3)^2-9]+7=2(x-3)^2-11\).`,'The correction inside the brackets is multiplied by the leading coefficient.');
Q(5,3,R`The solutions of \(x^2-4x-1=0\) are \(x=a\pm\sqrt b\), with b a positive integer. Find a and b.`,[R`\((a,b)=(2,3)\)`,R`\((2,5)\)`,R`\((-2,5)\)`,R`\((4,17)\)`],'B',[N('a','a',2),N('b','b',5)],R`Adding 4 to \(x^2-4x=1\) gives \((x-2)^2=5\). Thus \(x=2\pm\sqrt5\).`,'The number under the radical comes from the new right-hand side, not just the original constant.');
Q(5,4,R`The quadratic \(ax^2+12x+c\), with \(a>0\), has vertex \((-2,-1)\). Find a and c.`,[R`\((a,c)=(6,11)\)`,R`\((3,-13)\)`,R`\((3,11)\)`,R`\((-3,11)\)`],'C',[N('a','a',3),N('c','c',11)],R`Its vertex form is \(a(x+2)^2-1=ax^2+4ax+4a-1\). Matching the linear coefficient gives \(4a=12\), so \(a=3\). Then \(c=4a-1=11\).`,'Matching coefficients uses both the horizontal and vertical coordinates of the vertex.');
Q(5,5,R`Subject to \(x+y=1\), find the greatest constant C such that \(x^2+y^2-6x+8y+30\ge C\) for every allowed pair. Also find the pair where equality holds.`,[R`\(C=5\), at \((3,-4)\)`,R`\(C=7\), at \((4,-3)\)`,R`\(C=7\), at \((3,-2)\)`,R`\(C=39\), at \((0,1)\)`],'B',[N('C','Greatest lower bound C',7),N('x','Equality input x',4),N('y','Equality input y',-3)],R`Use \(y=1-x\). The expression becomes \(2x^2-16x+39=2(x-4)^2+7\). It is at least 7, with equality at \(x=4,y=-3\), which satisfies the constraint. Because equality is attained, no larger constant works.`,'Completing separate squares without using the constraint gives a lower value that cannot be attained on the line x + y = 1.');

L(6,'The Quadratic Formula and the Discriminant',52,
'Solve any quadratic and use coefficients to determine the number and type of roots.',
R`\[ax^2+bx+c=0,\ a\ne0:\quad x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}.\] The discriminant \(D=b^2-4ac\) is positive for two distinct real roots, zero for one repeated real root, and negative for two nonreal conjugate roots.`,
R`First collect every term on one side and identify a, b, and c with their signs. The discriminant tells you what kind of solutions to expect before you simplify the formula. A positive nonsquare discriminant gives irrational roots when the coefficients are rational; a negative value leads to i. Parameter questions require conditions, not a single substitution. If root signs matter, combine the discriminant with the sum \(-b/a\) and product \(c/a\): two real roots are both positive exactly when their sum and product are positive. Distinctness additionally requires D > 0.`,
[E('Use the formula with irrational roots',R`Solve \(x^2-3x-2=0\).`,R`\(D=(-3)^2-4(1)(-2)=17\). Thus \(x=(3\pm\sqrt{17})/2\).`,'Keep the entire numerator over 2a.'),E('Recognize nonreal roots',R`Classify the roots of \(2x^2+4x+5=0\).`,R`\(D=4^2-4(2)(5)=-24\), so there are two nonreal conjugate roots. The formula gives \(x=-1\pm(\sqrt6/2)i\).`,'No real x-intercept does not mean there are no complex solutions.')],
['Use the sign of b as written; −b reverses it.','The denominator 2a applies to both numerator terms.','D ≥ 0 permits a repeated root; use D > 0 for distinct real roots.'],
'Identify the coefficients, inspect the discriminant, and use all additional root conditions.',
'Combines complex numbers, completing the square, and graph-based root interpretation.');
Q(6,1,R`Solve \(x^2-3x-2=0\). Write the answers as \(x=(a\pm\sqrt b)/2\), where b is a positive integer.`,[R`\((3\pm\sqrt1)/2\)`,R`\((-3\pm\sqrt{17})/2\)`,R`\((3\pm\sqrt{17})/2\)`,R`\((3\pm\sqrt{17})/4\)`],'C',[N('a','a',3),N('b','b',17)],R`The coefficients are \(1,-3,-2\). The discriminant is \(9+8=17\), and \(-b=3\).`,'The negative constant makes the −4ac contribution positive.');
Q(6,2,R`Find the discriminant of \(2x^2+4x+5=0\) and state the number of distinct **real** solutions.`,[R`\(24\); 2`,R`\(-24\); 0`,R`\(-24\); 2`,R`\(0\); 1`],'B',[N('D','Discriminant',-24),N('count','Distinct real solutions',0)],R`\(D=4^2-4(2)(5)=16-40=-24\). A negative discriminant gives no real solutions.`,'The equation still has two complex roots; the question specifically asks for real ones.');
Q(6,3,R`Solve \(3x^2-4x-1=0\). Express the solutions as \(x=(a\pm\sqrt b)/3\) with b a positive integer.`,[R`\((2\pm\sqrt7)/3\)`,R`\((4\pm\sqrt7)/3\)`,R`\((2\pm\sqrt{13})/3\)`,R`\((-2\pm\sqrt7)/3\)`],'A',[N('a','a',2),N('b','b',7)],R`\(D=16+12=28\). The formula gives \((4\pm\sqrt{28})/6=(4\pm2\sqrt7)/6=(2\pm\sqrt7)/3\).`,'Simplify the common factor in the entire numerator and denominator.');
Q(6,4,R`The equation \(x^2-2(k+1)x+k^2=0\) has two distinct real roots exactly when \(k>c\). Find c.`,[R`\(c=-1\)`,R`\(c=0\)`,R`\(c=1/2\)`,R`\(c=-1/2\)`],'D',[N('c','Threshold c','-1/2')],R`\(D=4(k+1)^2-4k^2=4(2k+1)\). Two distinct real roots require \(D>0\), so \(k>-1/2\). At equality, the two roots coincide.`,'The strict inequality follows from the word distinct.');
Q(6,5,R`Find every real p for which \(x^2-(p+2)x+2p+1=0\) has two **distinct positive** roots. Express the parameter set as \((a,b)\cup(c,\infty)\).`,[R`\((-2,0)\cup(4,\infty)\)`,R`\((-1/2,0)\cup(4,\infty)\)`,R`\((0,4)\)`,R`\([-1/2,0]\cup[4,\infty)\)`],'B',[N('a','a','-1/2'),N('b','b',0),N('c','c',4)],R`Distinct real roots require \(D=(p+2)^2-4(2p+1)=p(p-4)>0\), so \(p<0\) or \(p>4\). Their sum is \(p+2\), which must be positive; their product is \(2p+1\), which must also be positive. These require \(p>-2\) and \(p>-1/2\). Intersecting all conditions gives \((-1/2,0)\cup(4,\infty)\).`,'Real and distinct is not enough: the sum and product eliminate nonpositive roots. Each excluded endpoint violates strict positivity or distinctness.');

L(7,'Quadratic Inequalities',62,
'Use roots and opening direction to solve one-variable inequalities and boundary curves to shade two-variable inequalities.',
R`For \(a(x-r)(x-s)\) with \(r<s\), the sign is the sign of a outside the roots and its opposite between them. Include roots for \(\le\) or \(\ge\), and exclude them for strict inequalities.`,
R`Find the roots first and use them to divide the number line into intervals. A test point determines the sign on each interval; a graph provides the same information through regions above or below the x-axis. With two variables, graph the boundary parabola and shade the side whose points satisfy the inequality. Use a solid curve when equality is allowed and a dashed curve when it is not. Systems require intersection of all solution sets. In parameter problems on a restricted domain, the minimum may occur at an endpoint or at the vertex, depending on the parameter.`,
[E('Solve a strict inequality',R`Solve \(-x^2+4x+5>0\).`,R`The roots are \(-1\) and \(5\). The parabola opens downward, so it is above the axis between the roots. The solution is \((-1,5)\).`,'The roots themselves give zero and therefore are excluded.'),E('Intersect two conditions',R`Solve \(x^2-4x-5\le0\) and \(x^2-2x-3>0\) together.`,R`The first gives \([-1,5]\); the second gives \(( -\infty,-1)\cup(3,\infty)\). Their intersection is \((3,5]\).`,'The endpoint −1 is rejected by the strict second condition, while 5 remains valid.')],
['A downward-opening parabola is positive between its real roots, not outside.','Use intersection for simultaneous conditions.','A dashed or solid boundary must agree with whether equality is allowed.'],
'Find boundary values, determine signs on intervals, and apply all endpoint and domain restrictions.',
'Combines Unit 1 inequality logic with quadratic graphs, roots, and vertex reasoning.');
Q(7,1,R`Solve \(x^2-5x+6\le0\).`,[R`\((2,3)\)`,R`\((-\infty,2]\cup[3,\infty)\)`,R`\([-3,-2]\)`,R`\([2,3]\)`],'D',[I('[2,3]')],R`The roots are 2 and 3. The upward-opening parabola is at or below the axis between them, including the roots.`,'Equality permits both endpoints.');
Q(7,2,R`Solve \(-x^2+4x+5>0\).`,[R`\((-1,5)\)`,R`\([-1,5]\)`,R`\((-\infty,-1)\cup(5,\infty)\)`,R`\((1,5)\)`],'A',[I('(-1,5)')],R`\(-x^2+4x+5=-(x-5)(x+1)\). It is positive strictly between its roots −1 and 5.`,'A strict inequality excludes the points where the expression is zero.');
Q(7,3,R`Which graph shows the solution region of \(y\ge x^2-4x+1\)?`,null,'C',[],R`The boundary is \(y=(x-2)^2-3\), with vertex \((2,-3)\). Equality requires a solid curve. The inequality requires shading above the curve, including the boundary.`,'The correct panel must have the right parabola, the right shaded side, and the correct boundary inclusion.',{window:[-5,8,-6,12],choices:[{curves:[poly([1,-4,1])],shade:{curve:poly([1,-4,1]),side:'below'}},{curves:[{...poly([1,-4,1]),dashed:true}],shade:{curve:poly([1,-4,1]),side:'above'}},{curves:[poly([1,-4,1])],shade:{curve:poly([1,-4,1]),side:'above'}},{curves:[poly([1,4,1])],shade:{curve:poly([1,4,1]),side:'above'}}]});
Q(7,4,R`Solve both inequalities simultaneously: \(x^2-4x-5\le0\) and \(x^2-2x-3>0\).`,[R`\([-1,5]\)`,R`\((3,5]\)`,R`\([3,5]\)`,R`\([-1,3)\)`],'B',[I('(3,5]')],R`The first factors as \((x-5)(x+1)\le0\), giving \([-1,5]\). The second is \((x-3)(x+1)>0\), giving \(x<-1\) or \(x>3\). The common part is \((3,5]\).`,'Each endpoint must satisfy both original inequalities, not just one.');
Q(7,5,R`Find all real k such that \(x^2-2kx+k+6>0\) for every \(x\in[0,2]\).`,[R`\((-2,3)\)`,R`\([-6,10/3]\)`,R`\((-6,10/3)\)`,R`\((-\infty,10/3)\)`],'C',[I('(-6,10/3)')],R`The vertex input is k. For \(k<0\), the minimum on the interval is at 0 and equals \(k+6\), requiring \(k>-6\). For \(0\le k\le2\), the vertex minimum is \(6+k-k^2\), which is positive throughout that parameter interval (its least endpoint value is 4). For \(k>2\), the minimum is at 2 and equals \(10-3k\), requiring \(k<10/3\). Combining the cases gives \((-6,10/3)\). At either excluded endpoint the expression reaches zero.`,'The domain is a closed interval, but the positivity requirement is strict. The vertex changes from outside to inside and then outside the domain, so one unrestricted discriminant test would be incorrect.');
export const unit3=U;
