import {R,N,T,S,I,P,unitContent,example as E} from '../course-common.mjs';
const U=unitContent(9,'Trigonometric Functions');const {lesson:L,add:Q}=U;
const trig=(fn,a=1,b=1,h=0,k=0)=>({kind:'trig',fn,a,b,h,k});
L(1,'Trigonometric Functions in Right Triangles',5,'Use side ratios, special triangles, and elevation or depression angles to solve right-triangle problems.',R`\[\sin\theta=\frac{\text{opposite}}{\text{hypotenuse}},\quad\cos\theta=\frac{\text{adjacent}}{\text{hypotenuse}},\quad\tan\theta=\frac{\text{opposite}}{\text{adjacent}}.\] The reciprocal ratios are csc, sec, and cot.`,R`Label sides relative to the chosen acute angle, because “opposite” and “adjacent” change when the angle changes. The hypotenuse always lies opposite the right angle. Use the Pythagorean theorem to find a missing side before forming ratios. Special 45–45–90 and 30–60–90 triangles give exact values without a calculator. In a word problem, draw a horizontal reference line for an angle of elevation or depression and identify the actual horizontal distance rather than assuming a slanted length is the adjacent side.`,[E('Read a side ratio',R`A right triangle has legs 5 and 12 and hypotenuse 13. For the angle opposite the side 5, find sin θ and tan θ.`,R`sin θ = 5/13 and tan θ = 5/12.`,'Each ratio uses sides identified relative to the specified angle.'),E('Use a special triangle',R`A 30° angle has opposite side 7 in a right triangle. Find the hypotenuse and other leg.`,R`The 30–60–90 ratio is 1:√3:2, so the hypotenuse is 14 and the other leg is 7√3.`,'The side opposite 30° is the shortest side.')],['Identify sides relative to the given angle.','The hypotenuse is never an adjacent leg in the tangent ratio.','Use degrees or radians consistently on a calculator.'],'Draw and label the triangle, choose a ratio, and check that the resulting lengths fit the geometry.','Extends triangle geometry to general-angle trigonometry.');
Q(1,1,R`In a 3–4–5 right triangle, θ is opposite the side of length 3. Find sin θ.`,['3/4','4/5','3/5','5/3'],'C',[N('sin','sin θ','3/5')],R`The opposite side is 3 and the hypotenuse is 5, so sin θ = 3/5.`,'Sine uses opposite over hypotenuse.');
Q(1,2,R`An acute angle has tan θ = 5/12. Find cos θ.`,['5/13','12/13','13/12','12/5'],'B',[N('cos','cos θ','12/13')],R`Use legs 5 and 12. The hypotenuse is √(25 + 144) = 13, so cos θ = 12/13.`,'A ratio fixes triangle shape even when its scale is unspecified.');
Q(1,3,R`A ladder 10 units long makes a 60° angle with level ground. Its vertical reach is \(a\sqrt b\), with b squarefree. Find a,b and its horizontal distance from the wall.`,[R`\(a=5,b=3;\ 5\)`,R`\(a=5,b=2;\ 5\)`,R`\(a=10,b=3;\ 10\)`,R`\(a=5,b=3;\ 10\)`],'A',[N('a','a',5),N('b','b',3),N('distance','Horizontal distance',5)],R`Height = 10sin60° = 10(√3/2) = 5√3. Horizontal distance = 10cos60° = 5.`,'The ladder is the hypotenuse, not the vertical side.');
Q(1,4,R`An observer stands 24 meters horizontally from a tower. The angle of elevation to the top is θ with tan θ = 7/24. The observer's eye is 1.5 meters above the tower's base level. Find the tower's height.`,['7 m','5.5 m','25 m','8.5 m'],'D',[N('height','Height in meters','8.5')],R`The rise above eye level is 24tan θ = 7 meters. Add the 1.5-meter eye height to obtain 8.5 meters.`,'The trigonometric triangle begins at eye level, not at the ground.');
Q(1,5,R`On level ground, an observer measures the angle of elevation to a tower's top as 45°. After moving 20 meters directly toward the tower, the angle is 60°. Ignore eye height. Express the tower height as \(a+b\sqrt3\) and find a and b.`,[R`\(a=20,b=20\)`,R`\(a=30,b=10\)`,R`\(a=10,b=30\)`,R`\(a=30,b=-10\)`],'B',[N('a','a',30),N('b','b',10)],R`Let the nearer horizontal distance be d and height be H. The 45° observation gives H = d + 20. The 60° observation gives H = d√3. Thus d(√3 − 1) = 20, so d = 10(√3 + 1). Then H = d + 20 = 30 + 10√3.`,'The two triangles share a height but have different horizontal distances. Their simultaneous relationships determine the height exactly.');

L(2,'Angles and Angle Measure',15,'Convert degrees and radians and use radian measure in arc-length and sector-area formulas.',R`\[180^\circ=\pi\text{ radians},\quad s=r\theta,\quad A=\tfrac12r^2\theta\] when θ is in radians. Coterminal angles differ by a whole multiple of 2π.`,R`Radian measure compares arc length with radius: an angle of one radian cuts off an arc as long as the radius. A full turn is 2π radians or 360 degrees. Multiply by the appropriate conversion factor so units cancel. Positive angles rotate counterclockwise and negative angles clockwise; coterminal angles end on the same ray. Arc and sector formulas require radian measure. In optimization problems, a fixed perimeter can be used to eliminate the angle and turn area into a quadratic in the radius.`,[E('Convert an angle',R`Convert 150° to radians.`,R`150·π/180 = 5π/6.`,'The conversion factor is π radians per 180 degrees.'),E('Find an arc',R`A circle has radius 6 and a central angle π/3. Find the intercepted arc length.`,R`s = 6(π/3) = 2π.`,'The angle is already in radians, so the formula applies directly.')],['Use radians in s = rθ and sector-area formulas.','Coterminal does not mean equal numerical measure.','An arc length and a sector area have different units.'],'Convert units deliberately and relate angles to the geometry of their circle.','Prepares for unit-circle and periodic-function models.');
Q(2,1,R`Convert 225° to \(c\pi\) radians. Find c.`,['5/4','4/5','3/4','5/2'],'A',[N('c','Coefficient of π','5/4')],R`225·π/180 = 5π/4.`,'Reduce the degree-to-radian ratio.');
Q(2,2,R`Find the angle in [0,2π) coterminal with −7π/6. Write it as cπ and give c.`,['−1/6','7/6','5/6','11/6'],'C',[N('c','Coefficient of π','5/6')],R`Add 2π = 12π/6 to get 5π/6, which lies in the required interval.`,'A full turn preserves the terminal ray.');
Q(2,3,R`A sector has radius 9 and angle 2π/3. Write its arc length as aπ and its area as bπ. Find a and b.`,[R`\(a=3,b=27\)`,R`\(a=6,b=27\)`,R`\(a=6,b=54\)`,R`\(a=18,b=81\)`],'B',[N('a','Arc coefficient a',6),N('b','Area coefficient b',27)],R`Arc length = 9(2π/3) = 6π. Area = (1/2)·81·(2π/3) = 27π.`,'The sector area has an extra factor of radius and one-half.');
Q(2,4,R`A wheel of radius 0.5 meter rolls without slipping through 12π meters. How many full revolutions does it make?`,['6','24','12π','12'],'D',[N('turns','Revolutions',12)],R`One revolution travels the circumference 2π(0.5) = π meter. Thus 12π/π = 12 revolutions.`,'Rolling distance equals the circumference times the number of turns.');
Q(2,5,R`A circular sector has perimeter 20, including its two radii and arc. Among such sectors with positive radius and angle at most 2π, find the maximum area, the radius achieving it, and the angle in radians.`,[R`\(25;5;2\)`,R`\(50;5;2\)`,R`\(25;10;1\)`,R`\(100;5;4\)`],'A',[N('area','Maximum area',25),N('radius','Radius',5),N('angle','Angle in radians',2)],R`The perimeter condition gives rθ = 20 − 2r. Thus area = (1/2)r(rθ) = 10r − r² = 25 − (r − 5)² ≤ 25. Equality occurs at r = 5, when θ = (20 − 10)/5 = 2 radians. This angle is positive and less than 2π, so the maximizing sector is allowed.`,'Eliminating the angle creates a quadratic bound, and checking the geometric constraint confirms its equality case is feasible.');

L(3,'Trigonometric Functions of General Angles',23,'Use terminal-ray coordinates, reference angles, and quadrant signs to evaluate trigonometric functions.',R`For a point (x,y) on the terminal ray, \(r=\sqrt{x^2+y^2}\), \(\sin\theta=y/r\), \(\cos\theta=x/r\), and \(\tan\theta=y/x\) when x ≠ 0.`,R`General angles can extend beyond acute triangles and beyond one full turn. A reference angle provides the acute-triangle magnitudes, while the terminal quadrant determines signs. On a circle, r is positive even when a coordinate is negative. Sine follows the y-coordinate, cosine the x-coordinate, and tangent their ratio. Functions with a zero denominator are undefined. Coterminal angles have the same trigonometric values, so reduce by full turns when helpful without changing the quadrant.`,[E('Use a terminal point',R`A terminal ray passes through (−8,6). Find sine and cosine.`,R`r = √(64 + 36) = 10, so sin θ = 3/5 and cos θ = −4/5.`,'The point lies in Quadrant II, consistent with the signs.'),E('Use a reference angle',R`Evaluate cos 210°.`,R`The reference angle is 30° and the ray is in Quadrant III, where cosine is negative. Thus cos210° = −√3/2.`,'The reference angle determines magnitude, while the quadrant determines sign.')],['The radius r is always nonnegative.','Reference-angle values need the correct quadrant signs.','A reciprocal trigonometric function can be undefined when its denominator is zero.'],'Find a reference angle or terminal point, then apply signs and domain checks.','Connects right-triangle ratios to the full unit circle.');
Q(3,1,R`A terminal ray passes through (−3,4). Find sin θ and cos θ.`,[R`\(-3/5,4/5\)`,R`\(4/5,3/5\)`,R`\(4/5,-3/5\)`,R`\(-4/5,-3/5\)`],'C',[N('sin','sin θ','4/5'),N('cos','cos θ','-3/5')],R`r = 5, so sine is y/r = 4/5 and cosine is x/r = −3/5.`,'The point is in Quadrant II.');
Q(3,2,R`Evaluate sin 150° and cos 240°.`,[R`\(1/2,-1/2\)`,R`\(-1/2,1/2\)`,R`\(1/2,1/2\)`,R`\(-1/2,-1/2\)`],'A',[N('sin','sin 150°','1/2'),N('cos','cos 240°','-1/2')],R`The first angle has reference angle 30° in Quadrant II, so its sine is 1/2. The second has reference angle 60° in Quadrant III, so its cosine is −1/2.`,'Different reference angles can produce equal magnitudes for different functions.');
Q(3,3,R`If sin θ = −5/13 and θ lies in Quadrant IV, find cos θ and tan θ.`,[R`\(-12/13,5/12\)`,R`\(12/13,-5/12\)`,R`\(12/13,5/12\)`,R`\(-12/13,-5/12\)`],'B',[N('cos','cos θ','12/13'),N('tan','tan θ','-5/12')],R`Using r = 13,y = −5 gives x² = 169 − 25 = 144. Quadrant IV requires x = 12. Thus cos θ = 12/13 and tan θ = −5/12.`,'The quadrant selects the positive x-coordinate after taking a square root.');
Q(3,4,R`An angle is coterminal with 11π/6. Find sec θ and csc θ. Write sec θ as \(a\sqrt3/b\) in lowest terms, and give a,b,csc θ.`,[R`\(a=-2,b=3;\ -2\)`,R`\(a=2,b=3;\ 2\)`,R`\(a=1,b=2;\ -2\)`,R`\(a=2,b=3;\ -2\)`],'D',[N('a','a',2),N('b','b',3),N('csc','csc θ',-2)],R`At 11π/6, cosine is √3/2 and sine is −1/2. Their reciprocals are 2/√3 = 2√3/3 and −2.`,'Coterminal angles preserve the values; taking reciprocals preserves their signs.');
Q(3,5,R`An angle θ in Quadrant II satisfies sin θ + cos θ = 1/2. Find sin θ cos θ and express sin θ − cos θ as \(\sqrt a/b\), with positive integers a,b and a squarefree.`,[R`\(-3/8;\ a=7,b=2\)`,R`\(3/8;\ a=1,b=2\)`,R`\(-3/8;\ a=7,b=4\)`,R`\(-1/4;\ a=3,b=2\)`],'A',[N('product','sin θ cos θ','-3/8'),N('a','a',7),N('b','b',2)],R`Square the given sum: 1 + 2sin θ cos θ = 1/4, so the product is −3/8. Then (sin θ − cos θ)² = 1 − 2(−3/8) = 7/4. In Quadrant II, sine is positive and cosine negative, so their difference is positive: √7/2.`,'The unit-circle relation supplies the magnitudes, and the quadrant determines the square-root sign.');

L(4,'Circular and Periodic Functions',31,'Relate motion around a circle to sine and cosine and identify periods and angular speed.',R`On a circle of radius r, \(x=r\cos\theta,\ y=r\sin\theta\). With constant angular speed ω, \(\theta(t)=\theta_0+\omega t\) and period \(T=2\pi/|\omega|\).`,R`Circular motion repeats after a full revolution, so its coordinate functions are periodic. The unit circle turns an angle into the point (cos θ,sin θ); a larger radius scales both coordinates. Angular speed measures angle per unit time, while linear speed measures arc length per time and equals r|ω|. A periodic function repeats after a positive period, and its least positive period describes the fundamental cycle. When comparing two rotating objects, use their relative angular speed and initial angular separation rather than comparing their individual periods alone.`,[E('Read a unit-circle point',R`Find the unit-circle coordinates at θ = π/2.`,R`The point is (0,1), so cosine is 0 and sine is 1.`,'Cosine is the horizontal coordinate and sine the vertical coordinate.'),E('Find speed and period',R`A point rotates at π/4 radians per second on a circle of radius 3.`,R`Its period is 2π/(π/4) = 8 seconds, and its linear speed is 3π/4 units per second.`,'Angular speed and linear speed have different units.')],['A period is a positive time or input interval.','Linear speed includes the circle radius.','An initial angle affects position even when angular speed is unchanged.'],'Track angle, coordinates, and units through a complete cycle.','Provides the geometric foundation for trigonometric graphs.');
Q(4,1,R`Give the unit-circle point at angle π radians.`,[R`\((1,0)\)`,R`\((0,1)\)`,R`\((0,-1)\)`,R`\((-1,0)\)`],'D',[P('(-1,0)')],R`A half-turn from the positive x-axis reaches the leftmost point (−1,0).`,'The coordinates are (cos π,sin π).');
Q(4,2,R`A point completes a revolution every 12 seconds. Write its positive angular speed as cπ radians per second. Find c.`,['1/12','1/6','6','12'],'B',[N('c','Coefficient of π','1/6')],R`Angular speed is 2π/12 = π/6 radians per second.`,'A full revolution is 2π radians.');
Q(4,3,R`A wheel of radius 4 rotates at 3π/2 radians per second. Write the rim's linear speed as cπ and give c.`,['6','3/8','3/2','8'],'A',[N('c','Coefficient of π',6)],R`Linear speed is rω = 4(3π/2) = 6π.`,'Arc distance scales angular displacement by the radius.');
Q(4,4,R`A point starts at (5,0) on a radius-5 circle and rotates counterclockwise at π/3 radians per second. Give its coordinates after 3 seconds.`,[R`\((0,5)\)`,R`\((5,0)\)`,R`\((-5,0)\)`,R`\((0,-5)\)`],'C',[P('(-5,0)')],R`The angle after 3 seconds is π. Thus (x,y) = (5cos π,5sin π) = (−5,0).`,'The point makes half a revolution in the given time.');
Q(4,5,R`Two points move counterclockwise on the unit circle. Their angles are \(\theta_A(t)=\pi t/6\) and \(\theta_B(t)=\pi/2+\pi t/4\), with t ≥ 0. Find the first time they meet and their common coordinates.`,[R`\(t=6;(-1,0)\)`,R`\(t=12;(1,0)\)`,R`\(t=18;(-1,0)\)`,R`\(t=24;(1,0)\)`],'C',[N('time','First meeting time',18),P('(-1,0)')],R`The angular difference is π/2 + πt/12. Meeting requires this to equal 2πn. Its first attainable nonnegative-time multiple is 2π, giving t = 18. Then θ_A = 3π, so both points are (−1,0).`,'The faster point starts ahead, so it must gain the remainder of a full turn; setting the raw angles equal would give a negative time.');

L(5,'Graphing Trigonometric Functions',38,'Graph sine, cosine, tangent, and their reciprocal functions using cycles, extrema, zeros, and asymptotes.',R`For \(y=a\sin(bx)\) or \(a\cos(bx)\), amplitude is |a| and period is \(2\pi/|b|\). For \(y=a\tan(bx)\), period is \(\pi/|b|\).`,R`Sine and cosine repeat smooth bounded cycles. Plot one cycle at quarter-period intervals, then repeat it. Sine begins at the midline and cosine at an extremum when there is no shift. Tangent is unbounded and has no amplitude; its branches are separated by vertical asymptotes. Reciprocal functions inherit undefined inputs from zeros of their denominator functions: secant from cosine and cosecant from sine. Use exact zeros and signs to position branches instead of connecting across undefined inputs.`,[E('Graph a sine cycle',R`Describe \(y=2\sin(3x)\).`,R`Amplitude is 2 and period is 2π/3. Quarter-period steps of π/6 give values 0,2,0,−2,0 over one cycle.`,'The inside multiplier changes the horizontal period.'),E('Find tangent asymptotes',R`For y = tan x, locate the vertical asymptotes surrounding x = 0.`,R`Cos x is zero at x = ±π/2, so those are the nearest vertical asymptotes. The graph crosses (0,0).`,'The asymptotes separate branches; they are not part of the function.')],['Amplitude is nonnegative and does not apply to tangent.','Sine and cosine use 2π in the period; tangent uses π.','Never connect a curve through a vertical asymptote.'],'Determine the function family, period, key points, and undefined inputs before sketching.','Extends periodic motion to graph transformations.');
Q(5,1,R`Choose the graph of y = sin x. The horizontal axis uses radians.`,null,'A',[],R`Sine crosses (0,0) while increasing, reaches 1 at π/2, and returns to zero at π.`,'The direction at the origin distinguishes sine from negative sine.',{window:[-Math.PI*2,Math.PI*2,-2,2],xPi:true,choices:[trig('sin'),trig('cos'),trig('sin',-1),trig('sin',2)].map(c=>({curves:[c]}))});
Q(5,2,R`For \(y=-3\cos(2x)\), find the amplitude and write its period as cπ.`,[R`\(-3;1\)`,R`\(3;2\)`,R`\(3;1\)`,R`\(3;4\)`],'C',[N('amplitude','Amplitude',3),N('c','Period coefficient of π',1)],R`Amplitude is |−3| = 3. Period is 2π/2 = π.`,'The negative coefficient reflects the graph without making amplitude negative.');
Q(5,3,R`For y = tan(2x), write the period as cπ and the nearest positive vertical asymptote as x = dπ. Find c,d.`,[R`\(1;1/2\)`,R`\(1/2;1/4\)`,R`\(1/2;1/2\)`,R`\(2;1\)`],'B',[N('c','Period coefficient',.5),N('d','Asymptote coefficient',.25)],R`Tangent's period is π/2. Its asymptotes occur when 2x = π/2 + nπ, so the nearest positive one is x = π/4.`,'Period and distance from the origin to the nearest asymptote are different quantities.');
Q(5,4,R`Choose the graph of y = sec x = 1/cos x.`,null,'D',[],R`At x = 0 the value is 1. Vertical asymptotes occur at odd multiples of π/2; the graph stays at or above 1 or at or below −1.`,'The graph is undefined wherever cosine equals zero.',{window:[-Math.PI*2,Math.PI*2,-5,5],xPi:true,choices:[trig('csc'),trig('sec',-1),trig('cos'),trig('sec')].map(c=>({curves:[c]}))});
Q(5,5,R`For positive integer n, the function \(f(x)=\sin(nx)\) has exactly 9 distinct zeros in the closed interval [0,2π]. Find n and the number of maxima equal to 1 in that interval.`,[R`\(n=9;9\)`,R`\(n=4;4\)`,R`\(n=5;5\)`,R`\(n=4;5\)`],'B',[N('n','n',4),N('maxima','Number of maxima',4)],R`Zeros occur at x = kπ/n for k = 0,1,…,2n, giving 2n + 1 distinct zeros including both endpoints. Thus 2n + 1 = 9 and n = 4. Four complete sine cycles fit in the interval, each with one maximum of 1.`,'Counting endpoints correctly determines the frequency; the number of extrema then follows from complete cycles.');

L(6,'Translations of Trigonometric Graphs',46,'Read amplitude, period, phase shift, and midline and construct models from meaningful features.',R`\[y=a\sin[b(x-h)]+k\quad\text{or}\quad y=a\cos[b(x-h)]+k.\] Amplitude = |a|, period = 2π/|b|, phase shift = h, midline y = k.`,R`Factor the inside coefficient before reading the horizontal shift. A form such as sin(2x − π) shifts right by π/2, not π. Determine maximum and minimum from the midline and amplitude, then divide the period into quarter-cycle steps. In a periodic model, use a starting maximum for a cosine form or an upward midline crossing for a positive sine form. A few repeated measurements can fit several frequencies; extra information about the number of intervening cycles is needed to identify the model uniquely.`,[E('Read a phase shift',R`Describe \(y=4\sin(2x-\pi)+1\).`,R`Rewrite as 4sin[2(x − π/2)] + 1. The amplitude is 4, period π, shift π/2 right, and midline y = 1.`,'Factoring the inside multiplier prevents a phase-shift error.'),E('Model a starting maximum',R`A height ranges from 2 to 18 and completes a cycle every 20 seconds, starting at its maximum.`,R`The midline is 10 and amplitude 8. One model is h(t) = 10 + 8cos(πt/10).`,'The initial condition selects the cosine orientation.')],['Factor b before identifying h.','Use half the maximum-minus-minimum difference for amplitude.','Measurements alone may not identify the number of cycles between them.'],'Match geometric features and initial conditions, then verify the model at several key inputs.','Prepares for trigonometric identities and equations.');
Q(6,1,R`For \(y=2\sin(x-\pi/3)+4\), give the amplitude, midline height, and phase shift as cπ to the right.`,[R`\(2,4,1/3\)`,R`\(4,2,1/3\)`,R`\(2,4,-1/3\)`,R`\(2,4,3\)`],'A',[N('amplitude','Amplitude',2),N('midline','Midline height',4),N('c','Shift coefficient of π','1/3')],R`The outside multiplier gives amplitude 2, the added constant gives midline 4, and x − π/3 gives a right shift of π/3.`,'The formula is already in factored transformation form.');
Q(6,2,R`Rewrite \(y=3\cos(2x-\pi)+1\). Write its phase shift as cπ to the right and its period as dπ. Find c,d.`,[R`\(1,1\)`,R`\(1/2,2\)`,R`\(1/2,1\)`,R`\(-1/2,1\)`],'C',[N('c','Shift coefficient','1/2'),N('d','Period coefficient',1)],R`The argument is 2(x − π/2). Therefore the shift is π/2 right and the period is 2π/2 = π.`,'Divide the inside constant by the inside multiplier to find the shift.');
Q(6,3,R`Choose the graph of \(y=2\sin(x-\pi/2)+1\).`,null,'B',[],R`The midline is y = 1 and range is [−1,3]. At x = 0 the value is −1, and at x = π it is 3.`,'The phase shift places a minimum at the origin.',{window:[-Math.PI*2,Math.PI*2,-4,5],xPi:true,choices:[trig('sin',2,1,-Math.PI/2,1),trig('sin',2,1,Math.PI/2,1),trig('sin',1,1,Math.PI/2,2),trig('sin',2,2,Math.PI/2,1)].map(c=>({curves:[c]}))});
Q(6,4,R`A wheel seat's height has minimum 2, maximum 18, period 20 seconds, and starts at its maximum. Write \(h(t)=k+a\cos(c\pi t)\), with a > 0. Find k,a,c.`,[R`\(k=8,a=10,c=1/10\)`,R`\(k=10,a=8,c=1/20\)`,R`\(k=10,a=-8,c=1/10\)`,R`\(k=10,a=8,c=1/10\)`],'D',[N('k','k',10),N('a','a',8),N('c','c','1/10')],R`The midline is (18 + 2)/2 = 10 and amplitude is (18 − 2)/2 = 8. A 20-second period requires cπ = 2π/20 = π/10. Positive cosine starts at the maximum.`,'The range fixes the vertical parameters and the period fixes the angular frequency.');
Q(6,5,R`Let \(f(x)=a\sin(bx)+d\), with a,b > 0. Its range is [−1,5], f(π/3) = 5, and f(π) = −1. There are exactly seven crossings of the midline in the open interval (0,π). Find a,b,d.`,[R`\(a=3,b=3/2,d=2\)`,R`\(a=3,b=15/2,d=2\)`,R`\(a=2,b=15/2,d=3\)`,R`\(a=3,b=7,d=2\)`],'B',[N('a','a',3),N('b','b','15/2'),N('d','d',2)],R`The range gives a = 3 and d = 2. A maximum at π/3 requires bπ/3 = π/2 + 2πn, so b = 3/2 + 6n with integer n ≥ 0. These values also make f(π) = −1. Midline crossings occur at x = kπ/b; in (0,π), their number is the number of positive integers k < b. For b = 3/2 + 6n this is 1 + 6n. Setting it to seven gives n = 1, hence b = 15/2.`,'The two extrema alone allow multiple frequencies. The count of intervening crossings selects the intended frequency without assuming the observed extrema are consecutive.');
export const unit9=U;
