import {R,N,T,S,I,P,unitContent,example as E} from '../course-common.mjs';
const U=unitContent(6,'Exponential and Logarithmic Functions');const {lesson:L,add:Q}=U;
const exp=(a,b,h=0,k=0)=>({kind:'exponential',a,b,h,k});
const log=(b,h=0,k=0,a=1)=>({kind:'log',b,h,k,a});
L(1,'Graphing Exponential Functions',4,'Recognize constant multiplicative change and graph growth, decay, and transformations.',R`\[f(x)=ab^{x-h}+k,\qquad b>0,\ b\ne1.\] The horizontal asymptote is y = k; multiplying the input-step by one multiplies the unshifted output by b.`,R`An exponential function places the variable in the exponent. For a positive initial coefficient, bases greater than one produce growth and bases between zero and one produce decay. The domain is all real inputs, while the graph stays strictly on one side of its horizontal asymptote. Determine shifts and reflections before plotting a few exact points. Equal input steps produce a constant ratio only after subtracting any vertical shift. Comparing an exponential expression with a quadratic in a positive substitution can reveal its behavior for every real input.`,[E('Decay and its asymptote',R`Describe \(f(x)=8(1/2)^x+3\).`,R`Its values at x = 0, 1, 2 are 11, 7, 5. The domain is all real numbers, its range is \((3,\infty)\), and y = 3 is its horizontal asymptote.`,'The shifted output approaches 3 without reaching it.'),E('Find a growth factor',R`For \(f(x)=ab^x\), suppose f(0) = 5 and f(2) = 45, with b > 0.`,R`The first value gives a = 5. Then \(5b^2=45\), so b = 3.`,'A two-step growth factor of 9 corresponds to a one-step factor of 3.')],['Exponential growth is multiplicative, not a constant additive change.','The horizontal asymptote is not included in the range.','Subtract a vertical shift before comparing output ratios.'],'Identify the base, shifts, asymptote, and exact reference values.','Extends function transformations and prepares for logarithms as inverses.');
Q(1,1,R`Choose the graph of \(y=2^x\).`,null,'A',[],R`It passes through \((0,1)\), \((1,2)\), and \((2,4)\), increases, and approaches y = 0 to the left.`,'The base exceeds one and there is no shift.',{window:[-4,4,-2,10],choices:[exp(1,2),exp(1,.5),exp(1,2,0,2),exp(-1,2)].map(c=>({curves:[c]}))});
Q(1,2,R`For \(f(x)=3(1/2)^x+2\), find f(−2) and the horizontal asymptote y = k.`,[R`\(f(-2)=14,\ k=0\)`,R`\(f(-2)=11/4,\ k=2\)`,R`\(f(-2)=14,\ k=2\)`,R`\(f(-2)=-10,\ k=2\)`],'C',[N('value','f(−2)',14),N('k','Asymptote height k',2)],R`\((1/2)^{-2}=4\), so f(−2) = 3(4) + 2 = 14. The exponential term approaches zero, leaving y = 2.`,'A negative exponent takes a reciprocal; it does not make the output negative.');
Q(1,3,R`Let \(f(x)=ab^x+k\), where b > 0 and b ≠ 1. If f(0) = 3, f(1) = 5, and f(2) = 11, find a, b, and k.`,[R`\((2,3,1)\)`,R`\((1,3,2)\)`,R`\((1,2,2)\)`,R`\((3,1,2)\)`],'B',[N('a','a',1),N('b','b',3),N('k','k',2)],R`Successive differences are 2 and 6. Since \(f(2)-f(1)=b[f(1)-f(0)]\), b = 3. Then a(b − 1) = 2 gives a = 1, and a + k = 3 gives k = 2.`,'Differences eliminate the unknown vertical shift before solving for the base.');
Q(1,4,R`Choose the graph of \(y=-2^{x-1}+3\).`,null,'D',[],R`The graph decreases, approaches y = 3 from below to the left, and passes through \((1,2)\) and \((2,1)\).`,'The negative sign reflects the outputs; the inside shift is one unit right.',{window:[-4,5,-8,6],choices:[exp(1,2,1,3),exp(-1,2,-1,3),exp(-1,2,1,-3),exp(-1,2,1,3)].map(c=>({curves:[c]}))});
Q(1,5,R`Find all real m such that \(4^x-2m\,2^x+m+2>0\) for every real x.`,[R`\((-2,2)\)`,R`\([-2,2)\)`,R`\([-2,2]\)`,R`\(( -\infty,2)\)`],'B',[I('[-2,2)')],R`Set t = 2^x > 0. The expression is \(t^2-2mt+m+2\). If m ≤ 0, it is increasing on t > 0 and its limiting value at 0 is m + 2; strict positivity holds exactly when m ≥ −2, including m = −2 because t = 0 is never attained. If m > 0, the minimum occurs at t = m and equals \(-m^2+m+2=(2-m)(m+1)\), which must be positive. Thus 0 < m < 2. Combining gives \([-2,2)\).`,'The positive substitution domain makes the two endpoint decisions different: one is an unattained limit and the other is an attained zero.');

L(2,'Solving Exponential Equations and Inequalities',14,'Use common bases, monotonicity, and positive substitutions to solve exponential statements.',R`\[b^u=b^v\iff u=v.\] For b > 1, inequalities keep their direction; for 0 < b < 1, they reverse.`,R`If two exponential expressions can be written with a common positive base other than one, compare their exponents. Inequalities require attention to whether that base grows or decays. When both bˣ and b²ˣ occur, replace bˣ with a positive variable and solve the resulting polynomial. Discard nonpositive substitution values, because an exponential never equals zero or a negative number. For equations without a convenient common base, graph both sides to estimate intersections; logarithms in later lessons provide an exact inverse method.`,[E('Match bases',R`Solve \(3^{2x-1}=27\).`,R`Write 27 = 3³. Then 2x − 1 = 3, so x = 2.`,'Equal outputs of a one-to-one exponential have equal exponents.'),E('Reverse a decay inequality',R`Solve \((1/3)^x<1/9\).`,R`Since 1/9 = (1/3)² and the base is decreasing, x > 2.`,'Larger exponents produce smaller values for a base between zero and one.')],['A common base must be positive and different from one.','Reverse an inequality when comparing exponents of a decay base.','A substitution bˣ must stay positive.'],'Compare exponents when possible and retain the positive domain in polynomial substitutions.','Uses exponential graphs and leads to logarithmic equation solving.');
Q(2,1,R`Solve \(2^{x+1}=16\).`,['2','3','4','5'],'B',[N('x','x',3)],R`16 = 2⁴, so x + 1 = 4 and x = 3.`,'The exponential is one-to-one.');
Q(2,2,R`Solve \((1/3)^{2x-1}\ge27\). Give the boundary c in the solution x ≤ c.`,['−1','1','2','−2'],'A',[N('c','Boundary c',-1)],R`27 = (1/3)⁻³. The base is decreasing, so 2x − 1 ≤ −3, yielding x ≤ −1.`,'The inequality reverses when comparing the exponents.');
Q(2,3,R`Solve \(4^x-5\cdot2^x+4=0\).`,['0 only','2 only','−2 and 0','0 and 2'],'D',[S('0,2')],R`Set t = 2^x > 0. Then \(t^2-5t+4=(t-1)(t-4)=0\), so t = 1 or 4. These correspond to x = 0 or 2.`,'Both substitution roots are positive, so both give real exponential solutions.');
Q(2,4,R`Solve \(9^x-10\cdot3^x+9\le0\).`,[R`\(( -\infty,0]\cup[2,\infty)\)`,R`\([1,9]\)`,R`\([0,2]\)`,R`\((0,2)\)`],'C',[I('[0,2]')],R`Let t = 3^x > 0. The inequality \((t-1)(t-9)\le0\) gives 1 ≤ t ≤ 9. Since 3^x is increasing, this is 0 ≤ x ≤ 2.`,'Convert both endpoints back from t to x and include equality.');
Q(2,5,R`For which k ≥ 0 does \(\left|4^x-5\cdot2^x+4\right|=k\) have exactly three distinct real solutions?`,['2','4','9/4','0'],'C',[N('k','k','9/4')],R`Put t = 2^x > 0 and p(t) = t² − 5t + 4. Its minimum is −9/4 at t = 5/2. At k = 0, p = 0 gives two positive roots. For 0 < k < 9/4, each of p = k and p = −k has two positive roots, giving four. At k = 9/4, p = −k is tangent and gives one root, while p = k gives two positive roots, for three. For 9/4 < k < 4 there are two; for k ≥ 4 there is only one positive root (the root t = 0 at k = 4 is excluded).`,'The absolute value gives two level equations. Count distinct positive t-roots and treat tangency separately.');

L(3,'Geometric Sequences and Series',21,'Represent constant-ratio sequences and sum finite or convergent infinite geometric series.',R`\[a_n=a_1r^{n-1},\qquad S_n=\frac{a_1(1-r^n)}{1-r}\ (r\ne1).\] For |r| < 1, \(S_\infty=a_1/(1-r)\). Also \(a_n=ra_{n-1}\) for n ≥ 2, and \(S_n=\sum_{k=1}^{n}a_1r^{k-1}\). When r = 1, \(S_n=na_1\).`,R`A geometric sequence multiplies each term by the same ratio. Its explicit formula uses exponent n − 1 because the first term has undergone no multiplication. Multiplying a finite sum by the ratio and subtracting makes all interior terms cancel, producing the finite-sum formula. An infinite geometric series has a finite sum only when the ratio has absolute value less than one; its remaining tail then approaches zero. Negative ratios alternate signs but can still converge. Geometric models appear in repeated growth, depreciation, and repeating decimals. Sigma notation gives the index, its first and last values, and the term being added; substitute each allowed index to expand it. To insert geometric means between two positive endpoints with a positive common ratio, count the number of ratio steps. For example, inserting two means between 2 and 54 gives 54 = 2r³, so r = 3 and the means are 6 and 18. If a positive ratio is not required, solve the ratio equation for every real ratio; an even power can allow both signs.`,[E('Find a term',R`Find the fifth term of 7, 14, 28, … .`,R`Here a₁ = 7 and r = 2, so a₅ = 7(2⁴) = 112.`,'The fifth term uses four ratio multiplications.'),E('Sum a repeating process',R`Find \(9+3+1+1/3+\cdots\).`,R`The ratio is 1/3, whose absolute value is less than one. The sum is \(9/(1-1/3)=27/2\).`,'The convergence condition must be checked before using the infinite-sum formula.')],['Use n − 1 in the term formula.','A negative ratio is different from a negative first term.','The infinite-sum formula is invalid when |r| ≥ 1.'],'Identify the first term and ratio, then distinguish a term from a finite or infinite sum.','Connects exponential patterns with series and later probability calculations.');
Q(3,1,R`Find the sixth term of the geometric sequence 3, 6, 12, … .`,['48','96','192','63'],'B',[N('term','Sixth term',96)],R`a₁ = 3 and r = 2, so a₆ = 3(2⁵) = 96.`,'Six terms require five multiplications by the ratio.');
Q(3,2,R`Find the sum of the first five terms of 2, 6, 18, … .`,['162','240','242','486'],'C',[N('sum','Sum',242)],R`\(S_5=2(1-3^5)/(1-3)=242\). Directly, 2 + 6 + 18 + 54 + 162 = 242.`,'A sum includes every term, not just the last one.');
Q(3,3,R`Find the sum of \(12-6+3-3/2+\cdots\).`,['8','24','6','18'],'A',[N('sum','Infinite sum',8)],R`The ratio is −1/2, with absolute value less than one. Thus \(S=12/(1+1/2)=8\).`,'The alternating sign is included in the common ratio.');
Q(3,4,R`A geometric sequence has a₂ = 6 and a₅ = 162. Its ratio is positive. Find a₁ and the sum of its first four terms.`,[R`\(a_1=3,\ S_4=120\)`,R`\(a_1=2,\ S_4=26\)`,R`\(a_1=6,\ S_4=240\)`,R`\(a_1=2,\ S_4=80\)`],'D',[N('first','First term',2),N('sum','Sum of first four terms',80)],R`Dividing gives r³ = 162/6 = 27, so r = 3 and a₁ = 2. Then S₄ = 2 + 6 + 18 + 54 = 80.`,'The ratio of nonadjacent terms counts the number of steps between their indices.');
Q(3,5,R`A real geometric series has positive first term a and |r| < 1. Its infinite sum is 12, and the sum of the squares of all its terms is 48. Find a and r.`,[R`\(a=6,\ r=1/2\)`,R`\(a=18,\ r=-1/2\)`,R`\(a=4,\ r=2/3\)`,R`\(a=8,\ r=1/3\)`],'A',[N('a','First term a',6),N('r','Ratio r','1/2')],R`The conditions give \(a/(1-r)=12\) and \(a^2/(1-r^2)=48\). Substitute a = 12(1 − r) into the second: \(144(1-r)/(1+r)=48\). Hence 3 − 3r = 1 + r, so r = 1/2 and a = 6. Both series converge and satisfy the specified sums.`,'Squaring the terms creates another geometric series with first term a² and ratio r²; it does not square the original sum.');

L(4,'Logarithms and Logarithmic Functions',28,'Interpret a logarithm as an exponent and graph it as the inverse of an exponential function.',R`\[\log_b x=y\iff b^y=x,\qquad b>0,\ b\ne1,\ x>0.\]`,R`A logarithm answers the question “what exponent gives this positive output?” Exponential and logarithmic forms express the same relationship. Their graphs reflect across y = x, swapping domain and range. For an unshifted logarithm, the domain is positive inputs, the range is all real outputs, and the vertical asymptote is x = 0. A base greater than one gives an increasing graph; a base between zero and one gives a decreasing graph. Shifts move the asymptote, so solve the argument inequality to find the new domain.`,[E('Change forms',R`Evaluate \(\log_3(1/27)\).`,R`Since \(3^{-3}=1/27\), the logarithm equals −3.`,'The logarithm can be negative even though its argument must be positive.'),E('Shift a logarithm',R`Describe \(y=\log_2(x+4)-1\).`,R`The domain is x > −4 and the vertical asymptote is x = −4. The point with argument 1 is (−3,−1); argument 2 gives (−2,0).`,'Reference arguments 1 and the base give exact points.')],['The argument must be positive; the logarithm itself may have either sign.','A logarithm is an exponent, not a division by the base.','A shifted logarithm has a shifted vertical asymptote.'],'Translate to exponential form and use inverse-function geometry.','Builds on inverses and leads to logarithm properties.');
Q(4,1,R`Choose the graph of \(y=\log_2 x\).`,null,'C',[],R`The domain is x > 0. The graph increases through (1,0), (2,1), and (4,2), with vertical asymptote x = 0.`,'It is the reflection of y = 2ˣ across y = x.',{window:[-3,9,-5,5],choices:[log(.5),log(2,-2),log(2),log(2,0,2)].map(c=>({curves:[c]}))});
Q(4,2,R`If \(\log_b81=4\) and b is a valid real logarithm base, find b.`,['9','−3','4','3'],'D',[N('b','Base b',3)],R`The exponential form is b⁴ = 81. The real roots are ±3, but a logarithm base must be positive, so b = 3.`,'The base restriction eliminates the negative algebraic candidate.');
Q(4,3,R`Find the domain of \(f(x)=\log_3(2x-6)\).`,[R`\((3,\infty)\)`,R`\([3,\infty)\)`,R`\(( -\infty,3)\)`,R`\((0,\infty)\)`],'A',[N('boundary','Domain is x > c. Enter c.',3)],R`Require 2x − 6 > 0, giving x > 3.`,'A logarithm cannot accept a zero argument.');
Q(4,4,R`The graph \(f(x)=\log_2(x-h)+k\) has vertical asymptote x = 3 and passes through (5,4). Find h, k, and f(11).`,[R`\(h=3,\ k=2,\ f(11)=5\)`,R`\(h=3,\ k=3,\ f(11)=6\)`,R`\(h=-3,\ k=3,\ f(11)=6\)`,R`\(h=3,\ k=3,\ f(11)=7\)`],'B',[N('h','h',3),N('k','k',3),N('value','f(11)',6)],R`The asymptote gives h = 3. At x = 5, \(4=\log_2 2+k=1+k\), so k = 3. Then \(f(11)=\log_2 8+3=6\).`,'The asymptote determines the inside shift independently of the vertical shift.');
Q(4,5,R`Solve \(\log_4x+\log_x4=5/2\) for all valid real x.`,['4 and 16','2 and 16','2 only','1 and 16'],'B',[S('2,16')],R`The domain is x > 0, x ≠ 1. Put t = log₄x, so t ≠ 0 and logₓ4 = 1/t. Then \(t+1/t=5/2\), giving \(2t^2-5t+2=(2t-1)(t-2)=0\). Thus t = 1/2 or 2, and x = 4¹ᐟ² = 2 or 4² = 16. Both satisfy the original equation.`,'A variable logarithm base imposes an extra restriction and makes the two logarithms reciprocals.');

L(5,'Modeling Data',36,'Use patterns, scatter plots, regression, and residuals to choose and assess a model.',R`Linear: \(y=mx+b\); quadratic: \(y=ax^2+bx+c\); exponential: \(y=ab^x\); power: \(y=ax^b\). Residual = observed value − predicted value.`,R`Begin by examining the direction, shape, and strength of a scatter plot. Equal input steps suggest a linear model when first differences are constant, a quadratic model when second differences are constant, and an exponential model when positive-output ratios are constant. Regression estimates coefficients from data; a correlation coefficient describes linear association, with strength related to its absolute value. Inspect residuals and the context as well as numerical fit. A model that fits a few points can still extrapolate poorly, and correlation alone does not establish causation.`,[E('Recognize a model',R`At inputs 0, 1, 2, 3 the outputs are 5, 15, 45, 135. Find an exponential model.`,R`The ratio is 3 and the value at input 0 is 5, so y = 5·3ˣ.`,'Constant ratios, rather than constant differences, identify this exponential pattern.'),E('Read a residual',R`A model predicts 42 while the observed value is 38. Find and interpret the residual.`,R`Residual = 38 − 42 = −4. The model overestimates this observation by 4.`,'The sign depends on using observed minus predicted.')],['Use |r| when comparing strengths of linear association.','A strong association does not prove causation.','Extrapolation beyond the measured range needs a contextual justification.'],'Compare patterns, fit a model, inspect residuals, and state the limits of its predictions.','Brings function families together and prepares for the statistical reasoning in Unit 8.');
Q(5,1,R`At x = 0, 1, 2, 3, the outputs are 3, 6, 12, 24. In the model \(y=ab^x\), find a and b.`,[R`\(a=2,b=3\)`,R`\(a=3,b=2\)`,R`\(a=3,b=3\)`,R`\(a=6,b=2\)`],'B',[N('a','a',3),N('b','b',2)],R`At x = 0 the value is a = 3, and each output is twice the previous one, so b = 2.`,'Equal input increments produce a constant output ratio.');
Q(5,2,R`For x = 0, 1, 2, 3, the outputs are 2, 5, 10, 17. Fit \(y=ax^2+bx+c\) and predict the value at x = 4.`,['24','25','26','34'],'C',[N('value','Predicted value at x = 4',26)],R`First differences are 3, 5, 7; second differences are 2, so a = 1. The first two values give c = 2 and b = 2. Thus y = x² + 2x + 2, which gives 26 at x = 4.`,'The constant second difference is 2a for unit-spaced inputs.');
Q(5,3,R`A model predicts values 10, 15, 20 for observations 12, 14, 19. Find the sum of the squared residuals.`,['6','0','4','8'],'A',[N('sse','Sum of squared residuals',6)],R`Residuals are 2, −1, −1. Their squared sum is 4 + 1 + 1 = 6.`,'Squaring prevents positive and negative errors from canceling.');
Q(5,4,R`Two linear fits have correlation coefficients r = −0.96 and r = 0.72. Which has stronger linear association, and what is the first fit's coefficient of determination r²?`,[R`Second; 0.9216`,R`First; −0.9216`,R`Second; 0.5184`,R`First; 0.9216`],'D',[T('fit','Stronger fit: first or second','first',['1']),N('r2','First fit r squared','0.9216')],R`The first has larger absolute correlation: 0.96 > 0.72. Its r² is (−0.96)² = 0.9216.`,'The sign indicates direction; magnitude indicates strength. Squaring removes the sign.');
Q(5,5,R`Both \(E(x)=2\cdot2^x\) and \(P(x)=x^2+x+2\) match the data (0,2), (1,4), and (2,8). Find the smallest integer n > 2 for which \(E(n)\ge2P(n)\), and give both predictions at that n.`,[R`\(n=4;\ E=32,\ P=22\)`,R`\(n=5;\ E=64,\ P=32\)`,R`\(n=3;\ E=16,\ P=14\)`,R`\(n=6;\ E=128,\ P=44\)`],'B',[N('n','Smallest integer n',5),N('exponential','E(n)',64),N('polynomial','P(n)',32)],R`At n = 3, E = 16 and 2P = 28, so the condition fails. At n = 4, E = 32 and 2P = 44, so it fails again. At n = 5, E = 64 and 2P = 64, so it holds. These exhaust the smaller allowed integers, establishing n = 5.`,'Two models can fit every observed point and still disagree substantially outside the data range. The calculations establish the first threshold without assuming that a perfect initial fit identifies the correct model.');

L(6,'Properties of Logarithms',47,'Expand and combine logarithms with product, quotient, and power properties while preserving domains.',R`\[\log_b(MN)=\log_bM+\log_bN,\quad\log_b(M/N)=\log_bM-\log_bN,\quad\log_b(M^r)=r\log_bM\] for positive M and N.`,R`Logarithm properties come from the exponent rules for multiplication, division, and powers. Products become sums, quotients become differences, and exponents become coefficients. These properties do not distribute over addition inside an argument. When expanding expressions with variables, state positivity assumptions or use absolute values where appropriate; for example, log(x²) = 2log|x| for nonzero real x. When combining several logarithms, retain the original requirement that every argument is positive, even if the combined expression would allow extra inputs.`,[E('Expand a product and power',R`For x > 0, expand \(\log_2(8x^3)\).`,R`\(\log_2 8+3\log_2 x=3+3\log_2x\).`,'The coefficient 3 comes from the exponent on x.'),E('Combine a difference',R`Combine \(\log_5(x+2)-\log_5(x-1)\).`,R`The result is \(\log_5((x+2)/(x-1))\), with the original domain x > 1.`,'The quotient form must retain both original argument restrictions.')],['There is no rule log(M + N) = log M + log N.','A coefficient becomes an exponent when combining.','A combined argument can conceal restrictions from separate logarithms.'],'Apply the matching exponent rule and carry the original positivity conditions through every step.','Supports logarithmic equations and change-of-base calculations.');
Q(6,1,R`Evaluate \(\log_2 8+\log_2 4\).`,['12','6','5','2'],'C',[N('value','Value',5)],R`The values are 3 and 2, so the sum is 5; equivalently, log₂(8·4) = log₂32 = 5.`,'A sum of logarithms corresponds to a product of arguments.');
Q(6,2,R`If \(\log_b2=u\) and \(\log_b3=v\), write \(\log_b72=au+cv\). Find a and c.`,[R`\(a=3,c=2\)`,R`\(a=2,c=3\)`,R`\(a=6,c=6\)`,R`\(a=1,c=1\)`],'A',[N('a','Coefficient of u',3),N('c','Coefficient of v',2)],R`72 = 2³·3², so log_b72 = 3log_b2 + 2log_b3 = 3u + 2v.`,'Prime-power factorization exposes the logarithm coefficients.');
Q(6,3,R`Evaluate \(\log_3 45-\log_3 5+2\log_3 3\).`,['2','3','6','4'],'D',[N('value','Value',4)],R`The difference is log₃9 = 2, and 2log₃3 = 2. The total is 4.`,'A logarithmic difference becomes a quotient before evaluation.');
Q(6,4,R`Solve \(\log_2(x-1)+\log_2(x+1)=3\).`,['−3 and 3','3','−3','2'],'B',[N('x','x',3)],R`The original domain is x > 1. Combine to get log₂(x² − 1) = 3, hence x² − 1 = 8 and x = ±3. Only x = 3 belongs to the original domain.`,'The combined product is positive at −3, but each original logarithm is undefined there.');
Q(6,5,R`For which positive k does \(\log_2(x-1)+\log_2(5-x)=\log_2 k\) have exactly one real solution? Give k and that solution.`,[R`\(k=0,\ x=1\)`,R`\(k=8,\ x=3\)`,R`\(k=4,\ x=3\)`,R`\(k=4,\ x=2\)`],'C',[N('k','k',4),N('x','Solution x',3)],R`The domain is 1 < x < 5. Combining and using injectivity gives \((x-1)(5-x)=k\), or \(4-(x-3)^2=k\). On the domain this expression has maximum 4 at x = 3. Every 0 < k < 4 gives two symmetric allowed inputs; k = 4 gives one, and k > 4 gives none.`,'The original log domain excludes the zero-height endpoints, and the unique solution occurs at the maximum of the argument product.');

L(7,'Common Logarithms',54,'Use base-ten logarithms, change of base, and logarithmic scales to compare magnitudes.',R`\[\log x=\log_{10}x,\qquad \log_b a=\frac{\log a}{\log b}.\] For a positive integer N, its number of decimal digits is \(\lfloor\log N\rfloor+1\).`,R`Common logarithms relate numbers to powers of ten. In scientific notation, log(a·10ⁿ) = log a + n, separating the significant factor from its order of magnitude. The change-of-base formula lets a calculator evaluate logarithms with any valid base. Logarithmic scales convert multiplicative ratios into additive differences; always use the definition and reference quantity supplied by the problem. For digit counts and threshold questions, keep enough precision to decide which side of an integer boundary a logarithm lies on.`,[E('Use scientific notation',R`Given log 2 ≈ 0.3010, estimate log 2000.`,R`2000 = 2·10³, so log 2000 ≈ 0.3010 + 3 = 3.3010.`,'The integer part reflects the power-of-ten scale.'),E('Change the base',R`Express \(\log_7 20\) using common logarithms.`,R`\(\log_7 20=\log20/\log7\).`,'Use the same logarithm base in both numerator and denominator.')],['log without a written base means base ten in this lesson.','Change of base divides by the logarithm of the base.','Round only after making a threshold or digit-count decision.'],'Translate multiplicative magnitude into additive logarithms and keep threshold precision.','Connects logarithm properties to natural logs and exponential applications.');
Q(7,1,R`Evaluate \(\log 0.001\).`,['−3','3','−1000','1/3'],'A',[N('value','Value',-3)],R`0.001 = 10⁻³, so its common logarithm is −3.`,'A positive number less than one has a negative common logarithm.');
Q(7,2,R`Given log 2 ≈ 0.3010, estimate log 200 to four decimal places.`,['0.6020','3.3010','2.3010','1.3010'],'C',[N('value','Approximation','2.3010')],R`200 = 2·10², so log 200 = log 2 + 2 ≈ 2.3010.`,'The power of ten adds to the logarithm.');
Q(7,3,R`A sound-level difference is defined by \(D=10\log(I_2/I_1)\). If D = 30, find the intensity ratio \(I_2/I_1\).`,['30','100','3','1000'],'D',[N('ratio','Intensity ratio',1000)],R`Divide by 10 to get log(I₂/I₁) = 3. Therefore I₂/I₁ = 10³ = 1000.`,'An additive scale difference represents a multiplicative intensity ratio.');
Q(7,4,R`Using log 2 ≈ 0.3010299957, determine the number of decimal digits in \(2^{50}\).`,['15','16','17','50'],'B',[N('digits','Number of digits',16)],R`log(2⁵⁰) = 50log 2 ≈ 15.051499785. Thus 10¹⁵ < 2⁵⁰ < 10¹⁶, so it has 16 digits.`,'A logarithm between 15 and 16 describes a 16-digit positive integer.');
Q(7,5,R`Using log 2 ≈ 0.3010299957, find the smallest positive integer n for which \(2^n\) has exactly 100 decimal digits.`,['328','330','333','329'],'D',[N('n','Smallest n',329)],R`Exactly 100 digits requires \(99\le n\log2<100\). The first allowed integer is the ceiling of 99/log 2, which lies between 328 and 329. Check the boundary values: 328log 2 ≈ 98.73783859, while 329log 2 ≈ 99.03886859 < 100. Therefore n = 329.`,'The lower bound locates the first candidate, and the upper bound confirms that this candidate has not skipped the requested digit range.');

L(8,'Natural Logarithms',61,'Use base e and natural logarithms to describe continuous growth and invert exponential expressions.',R`\[\ln x=\log_e x,\quad \ln(e^x)=x,\quad e^{\ln x}=x\ (x>0),\quad A=Pe^{rt}.\]`,R`The number e is approximately 2.71828 and is the natural base for continuous growth. Its inverse is the natural logarithm, which has the same domain and properties as other logarithms. Isolate an exponential before taking natural logs, or combine logarithms before exponentiating. In the continuous-growth formula, r is a decimal rate per time unit and t must use that same unit. Comparing two growing quantities often simplifies after dividing, because the exponent rates subtract. Logarithms give an exact expression for the crossing time.`,[E('Invert an exponential',R`Solve \(e^{3x}=7\).`,R`Take natural logs to obtain 3x = ln 7, so x = (ln 7)/3.`,'Natural log directly undoes the base-e exponential.'),E('Compare continuous growth',R`If \(A(t)=200e^{0.05t}\), express its doubling time exactly.`,R`Set 400 = 200e⁰·⁰⁵ᵗ, divide by 200, and take ln: t = (ln 2)/0.05 = 20ln 2.`,'Doubling time depends on the growth rate, not on the initial amount.')],['ln is base e, not base ten.','Isolate the exponential before taking a logarithm.','A percent rate must be converted to a decimal.'],'Use inverse identities and keep rates and time units consistent.','Prepares for exponential applications and logistic models.');
Q(8,1,R`Evaluate \(\ln(e^5)\).`,['e','5','1','0'],'B',[N('value','Value',5)],R`Natural logarithm and base-e exponentiation are inverse operations, so the value is 5.`,'The inverse identity applies to every real exponent.');
Q(8,2,R`Solve \(\ln(x-2)=0\).`,['2','0','3','1'],'C',[N('x','x',3)],R`Exponentiating gives x − 2 = e⁰ = 1, so x = 3. The argument is positive.`,'A zero logarithm corresponds to an argument of one.');
Q(8,3,R`For \(A(t)=500e^{0.04t}\), the doubling time is \(c\ln2\). Find c.`,['25','50','4','0.04'],'A',[N('c','Coefficient c',25)],R`Set e⁰·⁰⁴ᵗ = 2. Then 0.04t = ln 2, so t = 25ln 2.`,'Divide by the continuous rate to undo its effect on time.');
Q(8,4,R`Solve \(\ln x+\ln(x-3)=\ln10\).`,['−2 and 5','−2','2','5'],'D',[N('x','x',5)],R`The domain is x > 3. Combine to get x(x − 3) = 10, so (x − 5)(x + 2) = 0. Only x = 5 is allowed.`,'The original logarithms reject the negative root of the product equation.');
Q(8,5,R`Two quantities follow \(A(t)=100e^{0.04t}\) and \(B(t)=80e^{0.06t}\), with t ≥ 0. Their unique crossing time has the form \(c\ln(5/4)\). Find c and the common value at that time.`,[R`\(c=50;\ A=B=156.25\)`,R`\(c=20;\ A=B=125\)`,R`\(c=50;\ A=B=125\)`,R`\(c=-50;\ A=B=64\)`],'A',[N('c','Time coefficient c',50),N('value','Common value','156.25')],R`Equating and dividing yields e⁰·⁰²ᵗ = 5/4, so t = 50ln(5/4). Then e⁰·⁰⁴ᵗ = (5/4)², giving A = 100·25/16 = 156.25. The ratio B/A = (4/5)e⁰·⁰²ᵗ increases strictly from 4/5, so there is exactly one nonnegative crossing.`,'Eliminating the time between exponentials gives the exact common value, and monotonicity establishes uniqueness.');

L(9,'Solving Logarithmic Equations and Inequalities',68,'Combine logarithms, apply inverse functions, and intersect solutions with every original domain restriction.',R`For b > 1, \(\log_b u<\log_b v\iff u<v\) when u,v > 0. For 0 < b < 1, reverse the inequality.`,R`Start by writing the positivity conditions for all logarithm arguments. Use product and quotient properties when several logs occur, then use exponential form or the one-to-one property. A resulting polynomial equation can have roots that violate the original domain. For inequalities, decide whether the log base is increasing or decreasing before comparing arguments; finish by intersecting the algebraic solution with the domain. A logarithmic substitution can also turn powers of a logarithm into a familiar quadratic, with each real substitution value mapping back to one positive input.`,[E('Solve with a domain check',R`Solve \(\log_3(x-2)=2\).`,R`The domain is x > 2. Exponential form gives x − 2 = 9, hence x = 11, which is valid.`,'Checking the argument is part of solving the original equation.'),E('A decreasing-base inequality',R`Solve \(\log_{1/2}(x+1)>-1\).`,R`The domain is x > −1. Since the base is decreasing, x + 1 < (1/2)⁻¹ = 2, giving x < 1. The solution is (−1,1).`,'Both the domain boundary and the comparison boundary are strict.')],['Keep each original argument positive.','A decreasing log base reverses comparisons.','Do not combine sums inside a single logarithm using a nonexistent addition rule.'],'State the domain first, solve the transformed statement, then intersect with the domain.','Combines inverse functions, inequalities, and logarithm properties.');
Q(9,1,R`Solve \(\log_2(x-1)=3\).`,['7','8','9','4'],'C',[N('x','x',9)],R`x − 1 = 2³ = 8, so x = 9, which satisfies x > 1.`,'Convert logarithmic form to exponential form.');
Q(9,2,R`Solve \(\log_{1/2}(x+2)\ge-2\).`,[R`\((-2,2]\)`,R`\([2,\infty)\)`,R`\([-2,2]\)`,R`\((-2,4]\)`],'A',[I('(-2,2]')],R`The domain is x > −2. The base is decreasing, so x + 2 ≤ (1/2)⁻² = 4, or x ≤ 2. Intersecting gives (−2,2].`,'The logarithm domain excludes the left endpoint even though the inequality permits equality at the right.');
Q(9,3,R`Solve \(\log_3x+\log_3(x-2)=1\).`,['−1 and 3','1','−1','3'],'D',[N('x','x',3)],R`The domain is x > 2. Combining gives x(x − 2) = 3, so (x − 3)(x + 1) = 0. Only 3 remains.`,'Both original arguments must be positive.');
Q(9,4,R`Solve \((\log_2x)^2-3\log_2x+2=0\).`,['1 and 2','2 and 4','−1 and −2','4 and 8'],'B',[S('2,4')],R`Let t = log₂x. Then (t − 1)(t − 2) = 0, so t = 1 or 2. Therefore x = 2 or 4.`,'Convert the substitution values back to inputs of the original equation.');
Q(9,5,R`For which real k does \(\log_2(x-1)=\log_2(k-x)+1\) have a real solution? Express the parameter condition as k > c, and the solution as \(x=(ak+b)/d\) with positive integers a,b,d having no common factor. Find c,a,b,d.`,[R`\(c=1;\ (a,b,d)=(2,1,3)\)`,R`\(c=0;\ (2,1,3)\)`,R`\(c=1;\ (1,1,2)\)`,R`\(c=1;\ (2,-1,3)\)`],'A',[N('c','Parameter boundary c',1),N('a','a',2),N('b','b',1),N('d','d',3)],R`The domain requires 1 < x < k, so k > 1 is necessary. Rewrite the right side as log₂[2(k − x)], giving x − 1 = 2k − 2x and x = (2k + 1)/3. For k > 1, its distances from the domain endpoints are 2(k − 1)/3 and (k − 1)/3, both positive. Thus the condition is also sufficient, and the linear equation gives a unique solution.`,'Derive a parameter condition from the domain, then prove the algebraic candidate lies inside it for every allowed parameter.');

L(10,'Using Logarithms to Solve Exponential Problems',76,'Solve growth, decay, logistic, and cooling models while interpreting the parameters and limits.',R`Exponential: \(Q(t)=Q_0e^{kt}\). Logistic: \(P(t)=L/(1+Ae^{-kt})\), with L,A,k > 0. Cooling: \(T(t)=T_a+(T_0-T_a)e^{-kt}\), k > 0.`,R`Exponential growth assumes a constant relative rate and has no upper bound. A logistic model adds a limiting level L, which the growing quantity approaches without reaching at a finite time. In a cooling model, the temperature difference from the surroundings decays exponentially; the absolute temperature does not generally halve at a constant rate. Isolate the exponential factor before taking logs. Check whether a requested level is in the model's attainable range and whether a computed time satisfies the stated time domain. Predictions remain conditional on the model and its context.`,[E('Use a half-life',R`A sample has half-life 6 hours. What fraction remains after 18 hours?`,R`There are 18/6 = 3 half-lives, so the remaining fraction is (1/2)³ = 1/8.`,'Half-life describes multiplicative decay over equal time intervals.'),E('Interpret a logistic limit',R`For \(P(t)=600/(1+5e^{-0.2t})\), find the initial value and limiting level.`,R`P(0) = 600/6 = 100. As t grows, e⁻⁰·²ᵗ approaches zero, so P approaches 600 from below.`,'The limiting level is approached, not attained at a finite time.')],['Take logarithms only after isolating a positive exponential expression.','Cooling halves the temperature difference from the surroundings.','A logistic carrying limit is not reached at a finite time.'],'Choose the model, isolate its exponential, solve with logarithms, and interpret the resulting time and range.','Connects function models with data analysis and later periodic modeling.');
Q(10,1,R`A quantity starts at 80 and doubles every 3 hours. What is its value after 9 hours?`,['240','320','640','720'],'C',[N('value','Value after 9 hours',640)],R`Nine hours contains three doubling periods, so the value is 80·2³ = 640.`,'Count the number of complete growth periods.');
Q(10,2,R`A sample falls from 160 grams to 20 grams in 18 hours under exponential decay. Find its half-life in hours.`,['3','6','9','12'],'B',[N('halfLife','Half-life in hours',6)],R`20/160 = 1/8 = (1/2)³, so three half-lives take 18 hours. Each half-life is 6 hours.`,'The amount ratio determines how many half-lives elapsed.');
Q(10,3,R`For \(P(t)=1000/(1+9e^{-kt})\), k > 0, find P(0) and the limiting population as t increases.`,[R`\(100,1000\)`,R`\(1000,100\)`,R`\(900,1000\)`,R`\(100,900\)`],'A',[N('initial','Initial population',100),N('limit','Limiting population',1000)],R`At t = 0 the denominator is 10, giving 100. As t increases the exponential approaches zero, so the denominator approaches 1 and P approaches 1000.`,'The numerator is the carrying limit, not the starting population.');
Q(10,4,R`An object cools in a 20°C room according to an exponential model. It starts at 100°C and reaches 60°C after 5 minutes. What is its temperature after 15 minutes?`,['12.5°C','25°C','35°C','30°C'],'D',[N('temperature','Temperature in °C',30)],R`The excess above room temperature falls from 80 to 40 in 5 minutes, so it halves every 5 minutes. After 15 minutes the excess is 80/8 = 10, giving 20 + 10 = 30°C.`,'Apply decay to the difference from the surrounding temperature.');
Q(10,5,R`A logistic population \(P(t)=L/(1+Ae^{-kt})\) has limiting level L = 900, P(0) = 100, and P(2) = 300. Find A and the exact time when the population reaches 600.`,[R`\(A=8;\ t=4\)`,R`\(A=9;\ t=4\)`,R`\(A=8;\ t=6\)`,R`\(A=8;\ t=3\)`],'A',[N('A','A',8),N('time','Time at population 600',4)],R`From 100 = 900/(1 + A), A = 8. At t = 2, 300 = 900/(1 + 8e⁻²ᵏ), so e⁻²ᵏ = 1/4 and k = ln 2. For P = 600, the denominator must equal 3/2, hence 8e⁻ᵏᵗ = 1/2 and e⁻ᵏᵗ = 1/16 = 2⁻⁴. Since k = ln 2, t = 4.`,'The population ratios themselves are not constant in logistic growth. Transforming the denominator reveals the exponential relationship needed to calibrate and solve the model.');
export const unit6=U;
