import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {ADAPTIVE,initialState,normalizeScope,eligibleQuestions,weightedPick,selectQuestion,seededRandom,startSession,changeScope,issueQuestion,recordAnswer,weight,difficultyWeights,updateQuestionWeight,questionPower} from '../server/engine.mjs';
import {grade,gradeQuestion,numberValue,linearRelation} from '../server/grading.mjs';
const allBank=JSON.parse(readFileSync(new URL('../content/questions.json',import.meta.url),'utf8'));
const bank=allBank.filter(q=>q.active!==false);
const now='2026-09-12T12:00:00.000Z';
const scope=(lessons=['1-1'],difficulties=[1,2,3,4,5],courses=['chapter-1'])=>({answerMode:'both',selectedCourseIds:courses,selectedLessonIds:lessons,difficultyMode:'custom',selectedDifficulties:difficulties});
const full=scope([...new Set(bank.map(q=>q.lessonId))],[1,2,3,4,5],[...new Set(bank.map(q=>q.courseId))]);
function stateFor(s=full){const state=initialState(bank,now);startSession(state,bank,s,{id:'session',now});return state;}
function submit(state,q,correct,config=ADAPTIVE){const id=`a-${state.attempts.length}`;state.session.current={instanceId:id,questionId:q.questionId,shownAt:now,decision:{test:true}};const values=Object.fromEntries(q.fields.map(f=>[f.key,correct?f.value:f.type==='choice'?f.options.find(([v])=>v!==f.value)[0]:'999']));const details=q.fields.map(f=>({key:f.key,label:f.label,studentAnswer:String(values[f.key]),correctAnswer:f.value,isCorrect:correct}));return recordAnswer(state,bank,id,values,{isCorrect:correct,details},'2026-09-12T12:00:05.000Z',config);}

test('question bank is complete and every declared answer grades correctly',()=>{assert.equal(bank.length,360);assert.equal(new Set(bank.map(q=>q.questionId)).size,360);for(const q of bank){assert.equal(grade(q.fields,Object.fromEntries(q.fields.map(f=>[f.key,f.value]))).isCorrect,true,q.questionId);assert.ok(q.promptHtml.includes('katex')||q.promptHtml.length>20);assert.ok(q.explanationHtml.length>50);}});
test('every lesson has precisely the explicit ebook mapping',()=>{const pages={'1-1':2,'1-2':10,'1-3':18,'1-4':25,'1-5':32,'1-6':39,'1-7':49,'1-8':57,'1-9':64,'2-1':4,'2-2':12,'2-3':20,'2-4':28,'2-5':35,'2-6':42,'2-7':50};for(const q of bank.filter(q=>q.lessonId in pages)){assert.equal(q.ebookPage,pages[q.lessonId]);assert.equal(q.ebookUrl,`/ebook/chapter${q.lessonId[0]}/p${pages[q.lessonId]}`);}});
test('scope intersects courses, lessons, and levels before all weighting',()=>{const extra=bank.map(q=>({...q,questionId:'extra-'+q.questionId,courseId:'chapter-2',lessonId:'2-'+q.lessonId}));const mixed=[...bank,...extra],state=initialState(mixed),s=scope(['1-2','1-4'],[2,4]);for(const q of mixed){state.weights.questions[q.questionId]={power:q.courseId==='chapter-2'?10000:-10000};}state.weights.courses['chapter-2']=1e12;const rng=seededRandom(27);for(let i=0;i<20000;i++){const q=selectQuestion(mixed,state,s,rng).question;assert.equal(q.courseId,'chapter-1');assert.ok(s.selectedLessonIds.includes(q.lessonId));assert.ok(s.selectedDifficulties.includes(q.difficulty));}});
test('one chosen difficulty is absolute, including extremes',()=>{for(const d of [1,5]){const s=scope(['1-1','1-8'],[d]);const state=stateFor(s);state.difficultyShift['1-1']=d===1?1.5:-1.5;for(let i=0;i<1000;i++)assert.equal(selectQuestion(bank,state,s,seededRandom(i)).question.difficulty,d);}});
test('no selected lessons, no course, or no levels yields no question and cannot start',()=>{for(const s of [scope([], [1]),scope(['1-1'],[]),scope(['1-1'],[1],[])]){assert.deepEqual(eligibleQuestions(bank,s),[]);assert.equal(selectQuestion(bank,initialState(bank),s),null);assert.throws(()=>stateFor(s));}});
test('multiple selected courses work, and a course without selected lessons is excluded',()=>{const mixed=[...bank,...bank.map(q=>({...q,courseId:'chapter-2',lessonId:'2-'+q.lessonId,questionId:'2-'+q.questionId}))];const s=scope(['1-1','2-1-1'],[1],['chapter-1','chapter-2']);const state=initialState(mixed);const chosen=new Set();const rng=seededRandom('multi');for(let i=0;i<100;i++)chosen.add(selectQuestion(mixed,state,s,rng).question.courseId);assert.equal(chosen.size,2);s.selectedLessonIds=['1-1'];assert.ok(eligibleQuestions(mixed,s).every(q=>q.courseId==='chapter-1'));});
test('correct and wrong answers apply the exact question multipliers and unchanged lesson/course deltas',()=>{for(let difficulty=1;difficulty<=5;difficulty++)for(const correct of [true,false]){const state=stateFor();const q=bank.find(q=>q.lessonId==='1-1'&&q.difficulty===difficulty);const a=submit(state,q,correct);const multiplier=ADAPTIVE.evidence[difficulty][correct?'correct':'incorrect'];assert.equal(a.questionWeightBefore,1);assert.equal(a.questionWeightAfter,correct?.5:2);for(const kind of ['lesson','course']){const rule=ADAPTIVE.weights[kind];const expected=Math.max(rule.min,Math.min(rule.max,rule.initial+(correct?-1:1)*rule.step*multiplier));assert.ok(Math.abs(a[kind+'WeightAfter']-expected)<1e-6);assert.equal(a[kind+'WeightBefore'],rule.initial);}assert.equal(a.evidenceMultiplier,multiplier);assert.equal(a.responseTime,5000);}});
test('question weights do not clamp; lesson and course bounds are preserved',()=>{const state=stateFor(),q=bank[0];for(let i=0;i<1100;i++)submit(state,q,false);assert.equal(weight(state,'question',q.questionId),'2^1100');for(const kind of ['lesson','course'])assert.equal(weight(state,kind,q[kind+'Id']),ADAPTIVE.weights[kind].max);for(let i=0;i<2200;i++)submit(state,q,true);assert.equal(weight(state,'question',q.questionId),'2^-1100');for(const kind of ['lesson','course'])assert.equal(weight(state,kind,q[kind+'Id']),ADAPTIVE.weights[kind].min);});
test('weighted draws approximate normalized weights, not uniform selection',()=>{const rng=seededRandom('distribution'),counts={a:0,b:0,c:0};for(let i=0;i<60000;i++)counts[weightedPick(['a','b','c'],id=>({a:1,b:3,c:6}[id]),rng)]++;for(const [id,p]of Object.entries({a:.1,b:.3,c:.6}))assert.ok(Math.abs(counts[id]/60000-p)<.012,JSON.stringify(counts));});
test('course then lesson then question weights affect hierarchy independently',()=>{const mixed=[...bank,...bank.map(q=>({...q,courseId:'chapter-2',lessonId:'2-'+q.lessonId,questionId:'2-'+q.questionId}))];const state=initialState(mixed);state.weights.courses={'chapter-1':1,'chapter-2':3};const s=scope(['1-1','2-1-1'],[1],['chapter-1','chapter-2']);const rng=seededRandom('hierarchy');let second=0;for(let i=0;i<30000;i++)if(selectQuestion(mixed,state,s,rng,{...ADAPTIVE,exploration:0}).question.courseId==='chapter-2')second++;assert.ok(Math.abs(second/30000-.75)<.015);});
test('recent questions do not immediately repeat when alternatives exist; saved weights are unchanged',()=>{const state=stateFor(),rng=seededRandom(91);const before=JSON.stringify(state.weights);let previous='';for(let i=0;i<100;i++){state.session.current=null;const next=issueQuestion(state,bank,{id:'q'+i,now,rng});assert.notEqual(next.questionId,previous);previous=next.questionId;}assert.equal(JSON.stringify(state.weights),before);assert.equal(state.recentQuestions.length,8);});
test('one-question scope repeats only that eligible question',()=>{const s=scope(['1-1'],[1]),state=stateFor(s);for(let i=0;i<10;i++){state.session.current=null;assert.equal(issueQuestion(state,bank,{id:String(i),now}).questionId,'1-1-q1');}});
test('unseen exploration remains active even when seen questions have huge weights',()=>{const state=stateFor(),unseen=bank.at(-1);for(const q of bank){if(q!==unseen)state.seen[q.questionId]=1;state.weights.questions[q.questionId]={power:q===unseen?-10:30};}const rng=seededRandom('explore');let fresh=0;for(let i=0;i<10000;i++)if(selectQuestion(bank,state,full,rng).question.questionId===unseen.questionId)fresh++;assert.ok(fresh>1700&&fresh<2400,`Unseen selected ${fresh} times`);});
test('mistake records are unique, require three consecutive correct answers, and survive mastery',()=>{const state=stateFor(),q=bank[0];submit(state,q,false);submit(state,q,false);assert.equal(Object.keys(state.mistakes).length,1);assert.equal(state.mistakes[q.questionId].wrongCount,2);submit(state,q,true);assert.equal(state.mistakes[q.questionId].isMastered,false);submit(state,q,false);assert.equal(state.mistakes[q.questionId].correctStreak,0);for(let i=0;i<2;i++)submit(state,q,true);assert.equal(state.mistakes[q.questionId].isMastered,false);submit(state,q,true);assert.equal(state.mistakes[q.questionId].isMastered,true);assert.equal(Object.keys(state.mistakes).length,1);submit(state,q,false);assert.equal(state.mistakes[q.questionId].isMastered,false);});
test('deselection and session-scope changes preserve all learning and attempt state',()=>{const state=stateFor();submit(state,bank[0],false);const saved=JSON.stringify({weights:state.weights,mastery:state.mastery,mistakes:state.mistakes,attempts:state.attempts});changeScope(state,bank,scope(['1-7'],[5]),now);assert.equal(state.session.questionsAnswered,1);assert.equal(state.session.current,null);assert.equal(JSON.stringify({weights:state.weights,mastery:state.mastery,mistakes:state.mistakes,attempts:state.attempts}),saved);changeScope(state,bank,scope(['1-1'],[1]),now);assert.equal(weight(state,'question','1-1-q1'),2);});
test('out-of-scope mistake reviews fail without expanding scope',()=>{const state=stateFor();submit(state,bank[0],false);changeScope(state,bank,scope(['1-9'],[5]),now);assert.throws(()=>issueQuestion(state,bank,{id:'review',now,reviewQuestionId:'1-1-q1'}),/outside/);assert.deepEqual(state.session.selectedLessonIds,['1-9']);});
test('answering a stale or excluded question is rejected without weight changes',()=>{const state=stateFor();issueQuestion(state,bank,{id:'old',now,rng:seededRandom(1)});changeScope(state,bank,scope(['1-9'],[5]),now);const before=JSON.stringify(state.weights);assert.throws(()=>recordAnswer(state,bank,'old',{}, {isCorrect:false,details:[]},now));assert.equal(JSON.stringify(state.weights),before);});
test('duplicate answer instance is idempotent',()=>{const state=stateFor(),a=submit(state,bank[0],false);recordAnswer(state,bank,a.instanceId,{}, {isCorrect:true,details:[]},now);assert.equal(state.attempts.length,1);assert.equal(state.session.questionsAnswered,1);assert.equal(state.mistakes[bank[0].questionId].wrongCount,1);});
test('auto difficulty moves gradually and independently of mastery',()=>{const state=stateFor();const before=difficultyWeights(state,'1-1',[1,2,3,4,5]);submit(state,bank[0],true);const after=difficultyWeights(state,'1-1',[1,2,3,4,5]);assert.ok(state.difficultyShift['1-1']>0&&state.difficultyShift['1-1']<.1);assert.ok(after[4].weight>before[4].weight);assert.ok(after[0].weight<before[0].weight);assert.ok(state.mastery['1-1'].correctEvidence>1);for(let i=0;i<100;i++)submit(state,bank[0],false);assert.ok(state.difficultyShift['1-1']>=-ADAPTIVE.auto.maxShift);});
test('fixed random seeds reproduce the entire selection sequence',()=>{const make=()=>{const state=stateFor(),rng=seededRandom('stable');return Array.from({length:50},(_,i)=>{state.session.current=null;return issueQuestion(state,bank,{id:String(i),now,rng}).questionId;});};assert.deepEqual(make(),make());});
test('numeric grading accepts equivalent fractions and safely rejects executable input',()=>{assert.equal(numberValue('2/4'),.5);assert.equal(numberValue('-(3+1)/2'),-2);for(const value of ['alert(1)','process.exit()','1/0','x','NaN','1e100'])assert.throws(()=>numberValue(value));});
test('equivalent line forms, interval endpoints, and unordered vertices grade accurately',()=>{const q=bank.find(q=>q.questionId==='1-4-q2');assert.equal(grade(q.fields,{equation:'y - 5 = -3(x - 2)'}).isCorrect,true);assert.equal(grade(q.fields,{equation:'y = -3x + 12'}).isCorrect,false);const interval=bank.find(q=>q.questionId==='1-2-q5');assert.equal(grade(interval.fields,{interval:'(-11/3, 19/3]'}).isCorrect,true);assert.equal(grade(interval.fields,{interval:'[-11/3, 19/3]'}).isCorrect,false);const pts={fields:[{key:'vertices',label:'Vertices',type:'points',value:'(0,0);(0,8);(8,0)'}]};assert.equal(grade(pts.fields,{vertices:'(0,8), (0,0), (8,0)'}).isCorrect,true);assert.equal(grade(pts.fields,{vertices:'(0,8), (0,8), (8,0)'}).isCorrect,false);});
test('lesson weighting and question weighting each approximate expected distributions',()=>{
 const variant={...bank[0],questionId:'variant-1'};const pool=[bank[0],bank[5],variant];const state=initialState(pool),rng=seededRandom('lesson-and-question');state.weights.lessons={'1-1':.1,'1-2':.4};state.weights.questions={'1-1-q1':{power:0},'variant-1':{power:3}};const s=scope(['1-1','1-2'],[1]);let first=0,variantCount=0;for(let i=0;i<40000;i++){const q=selectQuestion(pool,state,s,rng,{...ADAPTIVE,exploration:0}).question;if(q.lessonId==='1-1'){first++;if(q.questionId==='variant-1')variantCount++;}}assert.ok(Math.abs(first/40000-(.1*4.5/(.1*4.5+.4)))<.015);assert.ok(Math.abs(variantCount/first-8/9)<.02);
});
test('clearing an active scope immediately makes every question ineligible without erasing work',()=>{const state=stateFor();submit(state,bank[0],false);changeScope(state,bank,scope([],[]),now,{allowEmpty:true});assert.equal(eligibleQuestions(bank,state.session).length,0);assert.equal(state.session.questionsAnswered,1);assert.equal(state.attempts.length,1);assert.equal(Object.keys(state.mistakes).length,1);assert.throws(()=>issueQuestion(state,bank,{id:'empty',now}));});

test('a question weight affects frequency even with one question per difficulty',()=>{
 const s=scope(['1-1'],[1,2]),state=stateFor(s);state.weights.questions['1-1-q1']={power:-4};state.weights.questions['1-1-q2']={power:2};const rng=seededRandom('single-per-level');let first=0;
 for(let i=0;i<20000;i++)if(selectQuestion(bank,state,s,rng,{...ADAPTIVE,exploration:0}).question.questionId==='1-1-q1')first++;
 const expected=(.15/16)/(.15/16+.3*4);assert.ok(Math.abs(first/20000-expected)<.004);
});
test('graph questions cannot appear in written-only scope, regardless of weight',()=>{const s={...full,answerMode:'written'},state=stateFor(s);for(const q of bank)state.weights.questions[q.questionId]={power:q.isGraph?100000:0};const rng=seededRandom('graph-scope');for(let i=0;i<2000;i++)assert.equal(selectQuestion(bank,state,s,rng).question.isGraph,false);assert.equal(eligibleQuestions(bank,{...scope(['1-5']),answerMode:'written'}).length,0);});
test('MC, Written Response, and matching Both answers update one shared question exactly once',()=>{
 const q=bank[0],state=stateFor();for(const mode of ['mc','written','both']){changeScope(state,bank,{...scope(['1-1'],[1]),answerMode:mode},now);const current=issueQuestion(state,bank,{id:mode,now});const answer={method:mode,choice:q.correctChoice,written:{x:'14/2'}};const result=gradeQuestion(q,answer,state.session);recordAnswer(state,bank,current.instanceId,answer,result,now);recordAnswer(state,bank,current.instanceId,answer,result,now);}
 assert.equal(state.attempts.length,3);assert.equal(state.session.questionsAnswered,3);assert.equal(state.session.correctCount,3);assert.equal(weight(state,'question',q.questionId),.125);assert.deepEqual(Object.keys(state.weights.questions),[q.questionId]);
});
test('unsupported method submissions are rejected',()=>{const q=bank[0];assert.throws(()=>gradeQuestion(q,{method:'mc',choice:q.correctChoice},{answerMode:'written'}),/method/);});
test('Both grades all four correctness combinations once, using the specified Wrong rule',()=>{
 for(const mcCorrect of [true,false])for(const writtenCorrect of [true,false]){
  const q=bank[0],state=stateFor({...scope(['1-1'],[1]),answerMode:'both'});const current=issueQuestion(state,bank,{id:'both-case',now});
  const answer={method:'both',choice:mcCorrect?'A':'B',written:{x:writtenCorrect?'7':'8'}};
  const result=gradeQuestion(q,answer,state.session);const correct=mcCorrect&&writtenCorrect;
  assert.equal(result.isCorrect,correct);recordAnswer(state,bank,current.instanceId,answer,result,now);recordAnswer(state,bank,current.instanceId,answer,result,now);
  assert.equal(state.attempts.length,1);assert.equal(state.session.questionsAnswered,1);assert.equal(state.session.correctCount,correct?1:0);assert.equal(state.session.incorrectCount,correct?0:1);assert.equal(weight(state,'question',q.questionId),correct?.5:2);assert.equal(Object.keys(state.mistakes).length,correct?0:1);
 }
});
