import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
const require=createRequire(process.env.FIELDNOTES_PLAYWRIGHT_PACKAGE || new URL('../package.json',import.meta.url));
const {chromium}=require('playwright');
const base=process.argv[2]||'http://127.0.0.1:4173';
const out=new URL('../verification/',import.meta.url);
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const checks=[];
const errors=[];
const pages=[1,25,5,26,80];
for(const n of pages){
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 const path=`/ebook/chapter1/p${n}`;
 const response=await page.goto(base+path,{waitUntil:'networkidle'});
 assert.equal(response.status(),200,`${path} HTTP status`);
 assert.equal(await page.locator('body').getAttribute('data-page'),String(n));
 assert.equal(await page.locator('#page-input').inputValue(),String(n));
 assert.equal(new URL(page.url()).pathname,path);
 assert.ok(await page.locator('.scan-frame img').evaluate(img=>img.complete&&img.naturalWidth>0));
 assert.equal(await page.locator('.scan-frame').getAttribute('class'),`scan-frame ${n%2?'left':'right'}`);
 await page.reload({waitUntil:'networkidle'});
 assert.equal(await page.locator('body').getAttribute('data-page'),String(n));
 checks.push(`Fresh browser context + refresh: ${path}`);
 if(n===25) await page.screenshot({path:fileURLToPath(new URL('desktop.png',out)),fullPage:true});
 await context.close();
}
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/ebook/chapter1/p24');
await page.locator('[data-nav="next"]').click();await page.waitForURL('**/ebook/chapter1/p25');
await page.locator('[data-nav="next"]').click();await page.waitForURL('**/ebook/chapter1/p26');
await page.goBack();assert.equal(await page.locator('#page-input').inputValue(),'25');
await page.goBack();assert.equal(await page.locator('#page-input').inputValue(),'24');
await page.goForward();assert.equal(await page.locator('#page-input').inputValue(),'25');
checks.push('Next navigation: 24 → 25 → 26; Back → 25 → 24; Forward → 25');
await page.locator('#page-input').fill('63');await page.locator('#page-input').press('Enter');
await page.waitForURL('**/ebook/chapter1/p63');
checks.push('Typed page selector: 25 → 63');
await page.getByRole('button',{name:'Choose a page',exact:true}).click();
await page.getByRole('link',{name:'Page 7:',exact:false}).click();await page.waitForURL('**/ebook/chapter1/p7');
checks.push('Page grid selector: 63 → 7');
await page.locator('#page-input').fill('81');await page.locator('#page-input').press('Tab');
assert.equal(await page.locator('#page-error').isVisible(),true);assert.ok(page.url().endsWith('/p7'));
checks.push('Invalid page input rejected without changing current route');
await page.goto(base+'/ebook/chapter1/p25');
await page.getByRole('button',{name:'Zoom in',exact:true}).click();
assert.equal(await page.locator('#zoom-label').innerText(),'125%');
await page.getByRole('button',{name:'Fit page to width'}).click();
assert.equal(await page.locator('#zoom-label').innerText(),'Fit page');
checks.push('Zoom and fit controls');
await page.goto(base+'/ebook/chapter1/p1');
assert.equal(await page.locator('[data-nav="previous"]').count(),0);
await page.goto(base+'/ebook/chapter10/p46');
assert.equal(await page.locator('[data-nav="next"]').count(),0);
checks.push('First / last page boundary controls');
await page.goto(base+'/ebook/chapter1/p999');
assert.ok((await page.locator('h1').innerText()).includes('find your page'));
checks.push('Unavailable address shows a helpful reader page');
await context.close();
const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:2,hasTouch:true});
const m=await mobile.newPage();
await m.goto(base+'/ebook/chapter1/p25',{waitUntil:'networkidle'});
assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await m.screenshot({path:fileURLToPath(new URL('mobile.png',out)),fullPage:true});
await m.getByRole('button',{name:'Contents',exact:true}).click();
assert.equal(await m.locator('#mobile-toc').evaluate(d=>d.open),true);
await m.locator('#mobile-toc').getByRole('link',{name:'Rate of Change and Slope 18'}).click();
await m.waitForURL('**/ebook/chapter1/p18');
checks.push('Mobile layout: no page overflow; contents drawer navigates correctly');
await mobile.close();
const nojs=await browser.newContext({javaScriptEnabled:false});const nj=await nojs.newPage();
await nj.goto(base+'/ebook/chapter1/p25');
assert.equal(await nj.locator('h1').innerText(),'Writing Linear Equations');
await nj.locator('[data-nav="next"]').click();await nj.waitForURL('**/ebook/chapter1/p26');
checks.push('Direct reading and next-page links work with JavaScript disabled');
await nojs.close();
await browser.close();
assert.deepEqual(errors,[]);
await writeFile(new URL('results.json',out),JSON.stringify({base,time:new Date().toISOString(),checks,errors},null,2));
console.log(JSON.stringify({base,checks,errors},null,2));
